### ISSUE TITLE
Mxnet C API CPU Mode segmentation fault

### ISSUE THREAD

**Issue by pitLog** [apache/incubator-mxnet#9378] opened 2018-01-11 17:01 UTC
## Description
I try to use mxnet c_api but it crashes.

## Environment info (Required)
Win 10 64 bits, VS 2015

This is my sample :

`...
        mx_uint * shape = NULL;
        mx_uint shape_len = 0;
        MXPredSetInput(m_predictor, "data", in_data.data(), static_cast<mx_uint>(size));
        MXPredForward(m_predictor);
        MXPredGetOutputShape(m_predictor, 0, &shape, &shape_len);
        mx_uint tt_size = 1;
        for (mx_uint i = 0; i < shape_len; ++i) tt_size *= shape[i];
        assert(tt_size % 6 == 0);
        std::vector<float> outputs(tt_size);
        MXPredGetOutput(m_predictor, 0, outputs.data(), tt_size);
....
`

It works well in GPU mode, but not in CPU mode, I have a segmentation fault when MXPredGetOutput is called, and it appears it's the function NDArray::WaitToRead() that causes the segmentation fault.

Anybody have a solution ?

**Comment by lupesko** [comment] 2018-01-11 18:44
hey @pitLog - as a first step, can you please try [this example](https://github.com/apache/incubator-mxnet/tree/master/example/image-classification/predict-cpp) on CPU and see if it is working?

**Comment by lupesko** [comment] 2018-01-11 18:45
@nswamy please label as:
- Pending Requester Info
- C++
- Triaged

**Comment by pitLog** [comment] 2018-01-12 10:15
I tried your example.

First data model doesn't work and crashes for another reason : 
`mxnet\dmlc-core\include\dmlc/logging.h:308: [11:01:34] d:\dev\3rdparty\ms\axel\logiroad\all_mxnet\training\mxnet\src\operator\./concat-inl.h:184: Check failed: shape_assign(&(*in_shape)[i], dshape) Incompatible input shape: expected (1,0,14,14), got (1,320,13,13)`

But the second works well if I remove NDListHandle (because there is any mean file in this case).

So, What does it means ?
- my model is bad ? I use a SSD512 model
- Another idea ?

Thanks for your help

**Comment by pitLog** [comment] 2018-01-12 10:22
It appears the problem come from my model/param, because I find the same bug if I load my model with the predict example code.
But why ?

**Comment by lupesko** [comment] 2018-01-16 00:31
Thanks @pitLog 
@nswamy can you please label as:
- Bug
- Windows
- Crash

**Comment by lupesko** [comment] 2018-01-17 07:42
@pitLog it is reasonable to assume the problem is in your model.
Try building w/o MKL and see if the issue goes away.

**Comment by lupesko** [comment] 2018-02-20 07:32
@pitLog I verified today that the C API with the example code works perfectly well.
It is most likely that the problem is in your model, and/or with the model input shape.

We will be closing the issue, feel free to re-open if you think this was closed in error.

**Comment by lupesko** [comment] 2018-02-20 07:32
@sandeep-krishnamurthy can you please close?

**Closed** 2018-02-20 18:36 UTC
Labels: Bug, C++, Pending Requester Info, Windows
