### ISSUE TITLE
mxnet-mkl (v0.12.0) crash when using (conda-installed) numpy with MKL

### ISSUE THREAD

**Issue by fhieber** [apache/incubator-mxnet#8532] opened 2017-11-03 15:22 UTC
We have observed crashes with any mkl-enabled pip package of mxnet-0.12.0 in combination with numpy if installed through conda (which by default also uses MKL).

In this case, mxnet trainings crash with the following error message:
```
OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

Numpy from conda links against the libmkl_rt.so, distributed through conda:
```
libmkl_rt.so => /opt/conda/lib/python3.6/site-packages/numpy/core/../../../../libmkl_rt.so (0x00007f05256e0000)
	libmkl_rt.so => /opt/conda/lib/python3.6/site-packages/numpy/linalg/../../../../libmkl_rt.so (0x00007f367e1d5000)
	libmkl_rt.so => /opt/conda/lib/python3.6/site-packages/numpy/linalg/../../../../libmkl_rt.so (0x00007fd39e751000)
```

whereas MXNet links to its own .so:
```
ldd /opt/conda/lib/python3.6/site-packages/mxnet/libmxnet.so
[...]
	libmklml_intel.so => /opt/conda/lib/python3.6/site-packages/mxnet/libmklml_intel.so (0x00007f8c85b94000)
	libiomp5.so => /opt/conda/lib/python3.6/site-packages/mxnet/libiomp5.so (0x00007f8c857f1000)
[...]
```

This prevents people from using numpy w/ MKL in combination with mxnet-mkl==0.12.0.

**Comment by zhreshold** [comment] 2017-11-03 18:24
@szha

**Comment by szha** [comment] 2017-11-03 21:40
@ykim362 what's your recommendation on this? MKL2018 doesn't distribute .a, which means that I can't hide any of its symbols when loading.

**Comment by srochel** [comment] 2017-11-04 17:07
@b0noI - how do we resolve the issue on DLAMI?

**Comment by ykim362** [comment] 2017-11-04 19:34
@szha I am discussing with MKL team to figure out how to handle this situation. I will get back to you, soon.

**Comment by ykim362** [comment] 2017-11-06 23:17
@fhieber Could you provide your numpy (conda) version?

**Comment by cjolivier01** [comment] 2018-01-06 00:20
@szha, Can we link libiomp5.a statically and then strip the symbols from the final libmxnet.so?  I am theorizing (I think correctly) that two completely separate versions of openmp can coexist when they apply only to two different modules.

**Comment by larroy** [comment] 2018-01-06 00:31
@cjolivier01 how can this work, when the data structures passed to the functions of the library change? This would only work if both versions of openmp would guarantee binary compatibility. Is that the case?

**Comment by cjolivier01** [comment] 2018-01-06 00:37
@larroy Not sure what you're trying to say here.  If the symbols are stripped from libmxnet.so, then the libnumpy.so (or whatever it's called)'s omp.so and libmxnet.so (with its internal omp pool) won't see each other at all, much less call into each other.

**Comment by ykim362** [comment] 2018-01-06 00:44
@cjolivier01 When I discussed this issue with MKL team, it is not much feasible to make static MKLML given that it has lots of binary dependencies. Another aspect is that there is a possibility that two separate OpenMP calls (from numpy and from MXNet with MKLML) could degrade the performance. We are working on several experimentations. I would like to update the result next week.

**Comment by larroy** [comment] 2018-01-06 13:09
@cjolivier01 I see. I thought the problem was linking with the same symbols.  I found this related to the issue: https://software.intel.com/en-us/inference-engine-devguide-known-issues

**Comment by ykim362** [comment] 2018-01-10 01:24
@cjolivier01 From the experimentations, the behavior varies case by case. Some combinations of versions work fine. Some are not. So, the workaround @larroy pointed (LD_PRELOAD env variable) might be a good option. Also, it is recommended to use MKL-enabled MXNet with non-MKL python to get the best performance for neural network workloads.

**Comment by szha** [comment] 2018-01-10 02:16
@ykim362 our goal is to be able to provide good out-of-the-box experience for MKL-enabled mxnet. Though the workaround might be good for experienced users, we cannot control the environment in which mxnet runs for pip users. Thus, I'm still leaning towards the way @cjolivier01 proposed above if possible.

Do you mind sharing more on the dependencies of mklml to help figure out the feasibility of static-linking?

**Comment by ykim362** [comment] 2018-01-10 23:08
@szha I totally agree with you regarding the OOB experience! Actually, our concern is that static linking doesn't solve the problem. How about trying rpath compile option? 

@fhieber Could you provide some more detailed information to re-generate this situation? The behavior varies, so I would like to test with the exactly same environment.

**Comment by szha** [comment] 2018-01-10 23:23
@ykim362 could you elaborate? Currently I'm using '${ORIGIN}' in rpath for mkl builds already, and shipping mkl shared objects along with libmxnet.so. I don't think this prevents other omp from being loaded first and hence doesn't solve our problem. Are you referring to a different solution that's based on rpath?

**Comment by rsdubtso** [comment] 2018-01-11 00:36
MKL dev here. Can somebody please verify that the pip packages are not linked to OpenMP (Intel's libiomp5) statically? If any one of them is, then this would be a problem. If every single package links to OpenMP dynamically, this should probably work (disclaimer: this needs to be verified; the libmkl_rt.so on Linux loads libiomp5.so via dlopen and I'm not 100% sure what would happen if the library is loaded multiple times for example using RTLD_LOCAL...)

**Comment by szha** [comment] 2018-01-11 01:06
@rsdubtso Hi. I can verify that mxnet pip package is linked dynamically to `libiomp5.so`. We include `libiomp5.so` in the pip package using the rpath trick described above.

**Comment by rsdubtso** [comment] 2018-01-11 03:40
Hm. Seems like the numpy package also uses dynamic linking to libiomp5. Do you have a small repro that I could try? (Please do include all the necessary package installation steps -- I'm pretty new to all this stuff...)

PS. I also tried installing mxnet for python2.7 conda and it seems to be missing libmxnet.so completely... should I be using conda for python3?

**Comment by ykim362** [comment] 2018-01-22 22:23
@fhieber Could you provide the conda version you used or some more detailed environment when you got this problem? mxnet-mkl==0.12.0 and 0.12.1 work fine with conda in my tests.

**Comment by fhieber** [comment] 2018-01-23 10:21
@ykim362 I just tried this again in a Docker image with `mxnet-cu90mkl==1.0.0.post4` and the following `conda info` output:
```
               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.9.58-18.51.amzn1.x86_64 / glibc/2.17
                UID:GID : 0:0
```

I still observe the same crash:
```
> OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
> OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

**Comment by pengzhao-intel** [comment] 2018-03-13 05:55
@fhieber could you try the new build of 1.1.0
https://github.com/apache/incubator-mxnet/releases/tag/1.1.0

**Comment by pengzhao-intel** [comment] 2018-03-13 13:49
@fhieber we have tried the latest release the problem is gone. 
Would you mind to try again?

```

[chenxiny@mlt-ace Downloads]$ conda activate
(base) [chenxiny@mlt-ace Downloads]$ pip install mxnet_cu80mkl-1.1.0-py2.py3-none-manylinux1_x86_64.whl
Processing ./mxnet_cu80mkl-1.1.0-py2.py3-none-manylinux1_x86_64.whl
Requirement already satisfied: graphviz==0.8.1 in /home/chenxiny/anaconda3/lib/python3.6/site-packages (from mxnet-cu80mkl==1.1.0)
Requirement already satisfied: requests==2.18.4 in /home/chenxiny/anaconda3/lib/python3.6/site-packages (from mxnet-cu80mkl==1.1.0)
Requirement already satisfied: numpy<=1.13.3 in /home/chenxiny/anaconda3/lib/python3.6/site-packages (from mxnet-cu80mkl==1.1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/chenxiny/anaconda3/lib/python3.6/site-packages (from requests==2.18.4->mxnet-cu80mkl==1.1.0)
Requirement already satisfied: idna<2.7,>=2.5 in /home/chenxiny/anaconda3/lib/python3.6/site-packages (from requests==2.18.4->mxnet-cu80mkl==1.1.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/chenxiny/anaconda3/lib/python3.6/site-packages (from requests==2.18.4->mxnet-cu80mkl==1.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/chenxiny/anaconda3/lib/python3.6/site-packages (from requests==2.18.4->mxnet-cu80mkl==1.1.0)
Installing collected packages: mxnet-cu80mkl
Successfully installed mxnet-cu80mkl-1.1.0
(base) [chenxiny@mlt-ace Downloads]$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx

Intel python distribution
[chenxiny@mlt-ace Downloads]$ conda activate idp
(idp) [chenxiny@mlt-ace Downloads]$ pip install mxnet_cu80mkl-1.1.0-py2.py3-none-manylinux1_x86_64.whl
Processing ./mxnet_cu80mkl-1.1.0-py2.py3-none-manylinux1_x86_64.whl
Requirement already satisfied: numpy<=1.13.3 in /home/chenxiny/anaconda3/envs/idp/lib/python3.6/site-packages (from mxnet-cu80mkl==1.1.0)
Requirement already satisfied: requests==2.18.4 in /home/chenxiny/anaconda3/envs/idp/lib/python3.6/site-packages (from mxnet-cu80mkl==1.1.0)
Requirement already satisfied: graphviz==0.8.1 in /home/chenxiny/anaconda3/envs/idp/lib/python3.6/site-packages (from mxnet-cu80mkl==1.1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/chenxiny/anaconda3/envs/idp/lib/python3.6/site-packages (from requests==2.18.4->mxnet-cu80mkl==1.1.0)
Requirement already satisfied: idna<2.7,>=2.5 in /home/chenxiny/anaconda3/envs/idp/lib/python3.6/site-packages (from requests==2.18.4->mxnet-cu80mkl==1.1.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/chenxiny/anaconda3/envs/idp/lib/python3.6/site-packages (from requests==2.18.4->mxnet-cu80mkl==1.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/chenxiny/anaconda3/envs/idp/lib/python3.6/site-packages/certifi-2017.7.27.1-py3.6.egg (from requests==2.18.4->mxnet-cu80mkl==1.1.0)
Installing collected packages: mxnet-cu80mkl
Successfully installed mxnet-cu80mkl-1.1.0
(idp) [chenxiny@mlt-ace Downloads]$ python
Python 3.6.3 |Intel Corporation| (default, Oct 16 2017, 15:28:36)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import mxnet as mx


```

**Comment by pengzhao-intel** [comment] 2018-03-14 05:41
@fhieber  @rsdubtso is correct. It caused by multiple omp lib. The workaround is to set MP_DUPLICATE_LIB_OK=TRUE .

I am considering the final solution now. Will come back soon :)

Error log:

> [INFO:sockeye.training] Using bucketing. Default max_seq_len=(60, 60)
> [INFO:__main__] Optimizer: adam
> [INFO:__main__] Optimizer Parameters: {'wd': 0.0, 'learning_rate': 0.0003, 'lr_scheduler': LearningRateSchedulerPlateauReduce(reduce_factor=0.50, reduce_num_not_improved=0), 'clip_gradient': 1.0, 'rescale_grad': 1.0}
> [INFO:__main__] kvstore: device
> [INFO:__main__] Gradient Compression: None
> [INFO:__main__] Decode and Evaluate Device(s): cpu(0)
> [INFO:sockeye.model] Saved config to "/home/chenxiny/newstest/wmt_model/config"
> OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
> OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
> Aborted

After setting the environment, the problem is gone.
New log:

> [INFO:sockeye.utils] Sockeye version 1.16.2 commit 762ce78e4e49b9ba5d14eb0a48d97f19c8807707
> [INFO:sockeye.utils] MXNet version 1.1.0
> [INFO:sockeye.utils] Command: /home/chenxiny/anaconda3/lib/python3.6/site-packages/sockeye/train.py -s corpus.tc.BPE.de -t corpus.tc.BPE.en -vs newstest2016.tc.BPE.de -vt newstest2016.tc.BPE.en --num-embed 256 --rnn-num-hidden 512 --rnn-attention-type dot --max-seq-len 60 --decode-and-evaluate 500 -o wmt_model
> [INFO:sockeye.utils] Arguments: Namespace(allow_missing_params=False, batch_size=64, batch_type='sentence', bucket_width=10, checkpoint_frequency=1000, cnn_activation_type='glu', cnn_hidden_dropout=0.0, cnn_kernel_width=(3, 5), cnn_num_hidden=512, cnn_positional_embedding_type='learned', cnn_project_qkv=False, conv_embed_add_positional_encodings=False, conv_embed_dropout=0.0, conv_embed_max_filter_width=8, conv_embed_num_filters=(200, 200, 250, 250, 300, 300, 300, 300), conv_embed_num_highway_layers=4, conv_embed_output_dim=None, conv_embed_pool_stride=5, decode_and_evaluate=500, decode_and_evaluate_device_id=None, decode_and_evaluate_use_cpu=False, decoder='rnn', device_ids=[-1], disable_device_locking=False, embed_dropout=(0.0, 0.0), embed_weight_init='default', encoder='rnn', fill_up='replicate', gradient_clipping_threshold=1.0, gradient_clipping_type='abs', gradient_compression_threshold=0.5, gradient_compression_type=None, initial_learning_rate=0.0003, keep_last_params=-1, kvstore='device', label_smoothing=0.0, layer_normalization=False, learning_rate_decay_optimizer_states_reset='off', learning_rate_decay_param_reset=False, learning_rate_half_life=10, learning_rate_reduce_factor=0.5, learning_rate_reduce_num_not_improved=3, learning_rate_schedule=None, learning_rate_scheduler_type='plateau-reduce', learning_rate_warmup=0, lock_dir='/tmp', loss='cross-entropy', loss_normalization_type='valid', max_num_checkpoint_not_improved=8, max_num_epochs=None, max_seq_len=(60, 60), max_updates=None, metrics=['perplexity'], min_num_epochs=None, momentum=None, monitor_pattern=None, monitor_stat_func='mx_default', no_bucketing=False, num_embed=(256, 256), num_layers=(1, 1), num_words=(50000, 50000), optimized_metric='perplexity', optimizer='adam', optimizer_params=None, output='wmt_model', overwrite_output=False, params=None, prepared_data=None, quiet=False, rnn_attention_coverage_num_hidden=1, rnn_attention_coverage_type='count', rnn_attention_in_upper_layers=False, rnn_attention_mhdot_heads=None, rnn_attention_num_hidden=None, rnn_attention_type='dot', rnn_attention_use_prev_word=False, rnn_cell_type='lstm', rnn_context_gating=False, rnn_decoder_hidden_dropout=0.0, rnn_decoder_state_init='last', rnn_dropout_inputs=(0.0, 0.0), rnn_dropout_recurrent=(0.0, 0.0), rnn_dropout_states=(0.0, 0.0), rnn_encoder_reverse_input=False, rnn_first_residual_layer=2, rnn_forget_bias=0.0, rnn_h2h_init='orthogonal', rnn_num_hidden=512, rnn_residual_connections=False, seed=13, shared_vocab=False, source='corpus.tc.BPE.de', source_vocab=None, target='corpus.tc.BPE.en', target_vocab=None, transformer_activation_type='relu', transformer_attention_heads=8, transformer_dropout_act=0.0, transformer_dropout_attention=0.0, transformer_dropout_prepost=0.0, transformer_feed_forward_num_hidden=2048, transformer_model_size=512, transformer_positional_embedding_type='fixed', transformer_postprocess=('drn', 'drn'), transformer_preprocess=('', ''), use_cpu=False, use_tensorboard=False, validation_source='newstest2016.tc.BPE.de', validation_target='newstest2016.tc.BPE.en', weight_decay=0.0, weight_init='xavier', weight_init_scale=2.34, weight_init_xavier_factor_type='in', weight_init_xavier_rand_type='uniform', weight_normalization=False, weight_tying=False, weight_tying_type='trg_softmax', word_min_count=(1, 1))
> [INFO:sockeye.utils] Attempting to acquire 1 GPUs of 1 GPUs. The requested devices are: [-1]
> [INFO:sockeye.utils] Acquired GPU 0.
> [INFO:__main__] Training Device(s): GPU [0]
> [INFO:sockeye.vocab] Building vocabulary from dataset(s): ['corpus.tc.BPE.de']
> [INFO:sockeye.vocab] Vocabulary: types: 22309/22309/22309/22313 (initial/min_pruned/max_pruned/+special) [min_frequency=1, max_num_types=50000]
> [INFO:sockeye.vocab] Building vocabulary from dataset(s): ['corpus.tc.BPE.en']
> [INFO:sockeye.vocab] Vocabulary: types: 16757/16757/16757/16761 (initial/min_pruned/max_pruned/+special) [min_frequency=1, max_num_types=50000]
> [INFO:sockeye.data_io] ===============================
> [INFO:sockeye.data_io] Creating training data iterator
> [INFO:sockeye.data_io] ===============================
> [INFO:sockeye.data_io] 193369 sequences of maximum length (60, 60) in '/home/chenxiny/newstest/corpus.tc.BPE.de' and '/home/chenxiny/newstest/corpus.tc.BPE.en'.
> [INFO:sockeye.data_io] Mean training target/source length ratio: 0.99 (+-0.45)
> [INFO:sockeye.data_io] Tokens: source 4563838 target 4466824
> [INFO:sockeye.data_io] Vocabulary coverage: source 100% target 100%
> [INFO:sockeye.data_io] 193369 sequences across 6 buckets
> [INFO:sockeye.data_io] 6631 sequences did not fit into buckets and were discarded
> [INFO:sockeye.data_io] Bucket (10, 10): 32318 samples in 505 batches of 64, ~362.2 tokens/batch.
> [INFO:sockeye.data_io] Bucket (20, 20): 46870 samples in 733 batches of 64, ~949.5 tokens/batch.
> [INFO:sockeye.data_io] Bucket (30, 30): 49430 samples in 773 batches of 64, ~1511.9 tokens/batch.
> [INFO:sockeye.data_io] Bucket (40, 40): 35885 samples in 561 batches of 64, ~2070.4 tokens/batch.
> [INFO:sockeye.data_io] Bucket (50, 50): 19636 samples in 307 batches of 64, ~2618.3 tokens/batch.
>

**Comment by szha** [comment] 2018-04-06 05:59
@pengzhao-intel any update?

**Comment by szha** [comment] 2018-04-06 06:02
Unless intel provides a static library for libiomp5 built with -fPIC flag, or drop the dependency on it, I don't see anything we can do from the mxnet side. Suggestions are welcome.

**Comment by pengzhao-intel** [comment] 2018-04-06 15:27
@szha @ashokei is talking with MKL team for using libgomp in mxnet so it can avoid the dependency of libiomp. 

@ashokei any update and please correct me if my understanding is not correct.

**Comment by szha** [comment] 2018-04-06 17:04
@pengzhao-intel thanks for the update. @ashokei let us know how things progress and how this change impacts performance.

**Comment by ashokei** [comment] 2018-04-10 00:35
@zheng-da  is your openmp linking issue related to this in any way; Does your solution/workaround fix this ?

**Comment by tdomhan** [comment] 2018-06-26 13:48
any updates on this?

**Comment by pengzhao-intel** [comment] 2018-06-27 01:11
@tdomhan after several investigations, I realized it's not easy to resolve this issue under the current setting. We have to change some building logic.  
Do you still encounter this error? Does the workaround `KMP_DUPLICATE_LIB_OK=TRUE` make sense?
I will raise the internal discussion with MKL team and back soon.

**Comment by tdomhan** [comment] 2018-06-27 07:05
"**may cause crashes or silently produce incorrect**" in the message stated by Felix above made me not so eager to try this out, rather than using the non-MKL version of MXNet.

**Comment by pengzhao-intel** [comment] 2018-06-27 07:21
Understand, even we don't encounter the crashes and incorrect results by the workaround.
I am working on this item now and hope we can resolve this issue clearly :)

**Comment by tdomhan** [comment] 2018-06-27 08:39
thanks a lot for looking into this! :)

**Comment by pengzhao-intel** [comment] 2018-07-04 08:53
The numpy from conda includes the mkl package which conflicts with MXNET.  
The good news is the latest mkl package resolved this issue from mkl-2018.0.3.

Thus, updating the numpy in conda to 1.14 will resolve this issue.

@tdomhan @fhieber please try again in your environment. 
Feel free to let me know if you encountered any other issues.

> The following packages will be downloaded:
>     package                    |            build
>     ---------------------------|-----------------
>     **mkl-2018.0.3               |                1       198.7 MB**
> The following NEW packages will be INSTALLED:
>     blas:            1.0-mkl                   
>     mkl_fft:         1.0.1-py36h3010b51_0      
>     mkl_random:      1.0.1-py36h629b387_0      
>     numpy-base:      1.14.5-py36hdbf6ddf_0     
> The following packages will be UPDATED:
>     ca-certificates: 2017.08.26-h1d4fec5_0      --> 2018.03.07-0         
>     certifi:         2017.7.27.1-py36h8b7b77e_0 --> 2018.4.16-py36_0     
>     conda:           4.4.11-py36_0              --> 4.5.4-py36_0         
>     llvmlite:        0.20.0-py36_0              --> 0.23.2-py36hdbcaa40_0
>     mkl:             2018.0.0-hb491cac_4        --> 2018.0.3-1           
>     numba:           0.35.0-np113py36_10        --> 0.38.1-py36h04863e7_0
>     **numpy:           1.13.3-py36ha12f23b_0      --> 1.14.5-py36hcd700cb_0**
>     openssl:         1.0.2l-h077ae2c_5          --> 1.0.2o-h20670df_0    
>

**Comment by pengzhao-intel** [comment] 2018-07-19 01:00
@fhieber @tdomhan could you help confirm the fix?
If the problem is solved, we can close this bug finally ;)

**Comment by fhieber** [comment] 2018-09-28 07:40
I finally got back to this after a while. I no longer observe the libomp-related error mentioned in the original issue, but I am observing process deadlocks with the following numpy/mxnet configuration in Sockeye:
```
conda list | grep numpy
numpy                     1.15.1           py36h6a91979_0
numpy-base                1.15.1           py36h8a80b8c_0
conda list | grep mkl
blas                      1.0                         mkl
mkl                       2019.0                      118
mkl_fft                   1.0.4            py36h5d10147_1
mkl_random                1.0.1            py36h5d10147_1
mxnet-mkl                 1.3.0.post0               <pip>
```
If mkl-optimized numpy is installed via anaconda (as shown above) and using mxnet-mkl==1.3.0.post0 on a Mac laptop, the Sockeye subprocess spawned at a checkpoint (to decode the validation data set), is unable to spawn and the main process deterministically hangs. When debugging, it seems that it fails to spawn the subprocess.
However, when using either mxnet==1.3.0.post0 (no mkl) or pip-installed numpy (no mkl), everything works just fine.

**Comment by pengzhao-intel** [comment] 2018-09-28 08:20
@fhieber thanks for the feedback. 
Could you give me a test case to reproduce this issue?

**Comment by fhieber** [comment] 2018-09-28 15:30
```
conda install mkl
conda install numpy
pip install mxnet-mkl
git clone https://github.com/awslabs/sockeye.git
cd sockeye
python -m sockeye.train --num-layers 1 -s setup.py -t setup.py -vs setup.py -vt setup.py -o test_model --batch-size 5 --batch-type sentence --num-embed 8 --transformer-model-size 8 --overwrite-output --use-cpu --transformer-attention-heads 1 --checkpoint-frequency 100 --decode-and-evaluate 2
```
(this will train a tiny model on the setup.py file, but will hang once reached 100 updates and spawns a CheckpointDecoder subprocess to decode 2 sentences of the validation data.
This will hang with the last log line being:
```
[INFO:sockeye.training] Starting process: Decoder-1
```

If you set `--decode-and-evaluate 0`, no decoder subprocess will be started at each checkpoint, and training runs fine.

If you run
```
conda uninstall mkl
conda uninstall numpy
pip install numpy
```
and run the same training with `--decode-and-evaluate > 0`, no hanging will occur.

**Comment by pengzhao-intel** [comment] 2018-09-29 04:47
@fhieber thanks for the details information.

Because this is a new issue, do you mind close this one and open a new one?
BTW, the issue is observed from sockeye first, I suggest we can create an issue in sockeye repo first and go back MXNet repo when we figure out the specific bug.

**Comment by lebeg** [comment] 2018-11-22 12:38
Possibly related https://github.com/apache/incubator-mxnet/pull/12160

**Comment by pengzhao-intel** [comment] 2019-03-14 12:20
The problem has been fixed with the latest numpy in conda.

Closing, feel free to re-open if there is any other issue.

**Closed by pengzhao-intel** 2019-03-14 12:20 UTC
Labels: Installation, MKL
