### ISSUE TITLE
[Flaky] test_convolution_multiple_streams

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#16238] opened 2019-09-22 20:39 UTC
```bash
 48560 test_operator_gpu.test_convolution_multiple_streams ... Starting engine NaiveEngine with 1 streams.
 48561 [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=922281235 to reproduce.
 48562 Setting test np/mx/python random seeds, use MXNET_TEST_SEED=922281235 to reproduce.
 48563 FAIL
```

```
 61405 ======================================================================
 61406 FAIL: test_operator_gpu.test_convolution_multiple_streams
 61407 ----------------------------------------------------------------------
 61408 Traceback (most recent call last):
 61409   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
 61410     self.test(*self.arg)
 61411   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 177, in test_new
 61412     orig_test(*args, **kwargs)
 61413   File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 586, in test_convolution_multiple_streams
 61414     {'MXNET_GPU_WORKER_NSTREAMS' : num_streams, 'MXNET_ENGINE_TYPE' : engine})
 61415   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 313, in run_in_spawned_process
 61416     assert p.exitcode == 0, "Non-zero exit code %d from %s()." % (p.exitcode, func.__name__)
 61417 AssertionError: Non-zero exit code 255 from _conv_with_num_streams().
 61418 -------------------- >> begin captured logging << --------------------
 61419 common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=922281235 to reproduce.
 61420 --------------------- >> end captured logging << ---------------------
```
[log.txt](https://github.com/apache/incubator-mxnet/files/3640152/log.txt)

**Comment by aaronmarkham** [comment] 2019-11-04 18:15
Failed here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-16719/1/pipeline

**Comment by haojin2** [comment] 2019-11-22 21:49
Happening again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-16883/1/pipeline/

**Comment by eric-haibin-lin** [comment] 2019-12-10 21:37
Failed several times here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-17002/11/pipeline/

**Comment by kshitij12345** [comment] 2020-01-23 15:52
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-17325/7/pipeline

**Comment by ChaiBapchya** [comment] 2020-01-24 08:52
Found again - http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/centos-gpu/branches/PR-17399/runs/1/nodes/74/log/?start=0
non-related PR https://github.com/apache/incubator-mxnet/pull/17399

**Comment by szha** [comment] 2020-01-24 10:27
Duplicate of #14329.

**Closed by szha** 2020-01-24 10:27 UTC
Labels: Flaky, Test
