### ISSUE TITLE
Compilation is failed in the newest version b7df20d6be!

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#2675] opened 2016-07-12 08:20 UTC
```
src/operator/./cudnn_convolution-inl.h: In member function ‘virtual void mxnet::op::CuDNNConvolutionOp<DType>::Forward(const mxnet::OpContext&, const std::vector<mshadow::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&)’:
src/operator/./cudnn_convolution-inl.h:137:33: error: ‘out’ was not declared in this scope
                                 out.dptr_ + out_offset_ * g), CUDNN_STATUS_SUCCESS);
```

**Comment by sxjscience** [comment] 2016-07-12 09:57
@starimpact  Seems to be caused by https://github.com/dmlc/mxnet/blob/master/src/operator/cudnn_convolution-inl.h#L137 . Here `out.dptr_` should be `out_ptr`.

**Comment by starimpact** [comment] 2016-07-12 13:13
if the code has problem, it should not be published.

**Comment by sxjscience** [comment] 2016-07-12 13:16
@starimpact Could you help test if the fix above works?

**Comment by starimpact** [comment] 2016-07-12 13:18
@sxjscience this problem I have fixed a few hours ago, but it comes another compilation failure problem. So I give up this newest version and used a version a few months ago.

**Comment by sxjscience** [comment] 2016-07-12 13:30
@starimpact Yes, we need to be more careful in checking compatibility issues (We have not checked the new conv layer in old versions of CuDNN, which causes the previous problem). For compilation failure, a possible cause is that the submodules, e.g, MShadow, are not updated. You can put the failure information here if that still doesn't work.

**Comment by piiswrong** [comment] 2016-07-12 19:19
should be fixed by https://github.com/dmlc/mxnet/pull/2679

**Closed** 2017-09-28 04:22 UTC
