### ISSUE TITLE
optimizer doc error

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12938] opened 2018-10-23 22:58 UTC
## Description
Sphinx throws an error on `optimizer` docs.

## Error
```
/home/ubuntu/incubator-mxnet/python/mxnet/optimizer/__init__.py:docstring of mxnet.optimizer.LBSGD:19: ERROR: Unexpected indentation.
```

**Comment by andrewfayres** [comment] 2018-10-24 17:46
@mxnet-label-bot add [Optimizer,doc]

**Comment by vdantu** [comment] 2018-11-07 20:02
@aaronmarkham : Is this a duplicate of https://github.com/apache/incubator-mxnet/issues/13030 ?

**Comment by aaronmarkham** [comment] 2018-11-07 22:19
Yes, it looks like it.

**Closed** 2018-11-15 20:58 UTC
Labels: Doc, Optimizer
