### ISSUE TITLE
why MKL and MKL-DNN can't be used simultaneously in ChooseBlas.cmake

### ISSUE THREAD

**Issue by luchangli03** [apache/incubator-mxnet#12134] opened 2018-08-11 10:43 UTC
if(MKL_FOUND)
      if(USE_MKLDNN)
      set(BLAS "open")
    else()
      set(BLAS "MKL")
    endif()
  endif()

**Comment by luchangli03** [comment] 2018-08-11 11:15
in the 3rdparty/mshadow/cmake/mshadow.cmake
the codes are also
  if(MKL_FOUND)
    if(USE_MKLML_MKL)
      set(BLAS "open")
    else()
      set(BLAS "MKL")
    endif()
  endif()
I can't understand

**Comment by marcoabreu** [comment] 2018-08-11 12:49
@lebeg

**Comment by pengzhao-intel** [comment] 2018-08-11 13:34
yes, it's a little trick and this is a piece of legacy code which we want to refine for a while.

You can refer this issue and @jinhuang415 can help for the details.
https://github.com/apache/incubator-mxnet/issues/10175

**Comment by jinhuang415** [comment] 2018-08-13 05:33
@luchangli03 Currently cmake BLAS is hard coded based on MKL_FOUND and USE_MKLDNN, we think this is unreasonable and need to change, solutions like to provide an option to select the BLAS type (just like what Makefile does, and users can still use MKL blas even use MKLDNN), this suggestion is also listed in #10175 related slides as well.

**Comment by lanking520** [comment] 2018-08-13 06:26
@mxnet-label-bot could you please label this as [build, cmake, mkldnn]

**Comment by lebeg** [comment] 2018-11-19 14:17
I have fixed this issue with https://github.com/apache/incubator-mxnet/pull/11148 but the PR still has some problems.

**Comment by pengzhao-intel** [comment] 2019-08-04 04:22
The latest CMake refactors the logic of MKL selection. 
The problem is resolved so closing.

**Closed by pengzhao-intel** 2019-08-04 04:22 UTC
Labels: Build, CMake, MKLDNN
