### ISSUE TITLE
error when DataLoader's num_workers is not 0

### ISSUE THREAD

**Issue by mengjiexu** [apache/incubator-mxnet#13313] opened 2018-11-17 08:18 UTC
when I use:
train_data = gluon.data.DataLoader(
        MyImageFolderDataset(label_len).transform_first(transform_train),
        batch_size=batch_size,num_workers=4)
It shows error:
      Can't pickle local object 'Dataset.transform_first.<locals>.base_fn'

when I use:
train_data = gluon.data.DataLoader(
        MyImageFolderDataset(label_len).transform_first(transform_train),
        batch_size=batch_size,**num_workers=0**)
It is ok.

**Comment by zachgk** [comment] 2018-11-19 18:18
@mxnet-label-bot add [Bug, Python, Gluon, Data-loading]

Thank you for submitting the issue! I'm labeling it so the MXNet community members can help resolve it.

**Comment by intgogo** [comment] 2018-11-26 11:17
Same problem in windows server 2016.

**Comment by gaomingnudt** [comment] 2018-12-20 09:23
I got the same problem on Win10
mxnet is latest version
and the same code work fine on mac

**Comment by abhinavs95** [comment] 2019-04-04 17:29
@mengjiexu looks like #14541  is a duplicate issue of this. Acc @zhreshold comment there the issue is fixed in 1.4.0 and master

**Closed** 2019-04-08 17:30 UTC
Labels: Bug, Data-loading, Gluon, Python
