### ISSUE TITLE
CI Error: ClosedChannelException

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#11653] opened 2018-07-11 20:19 UTC
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11587/8/pipeline/

```

java.nio.channels.ClosedChannelException

Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-172-31-8-62.us-west-2.compute.internal/172.31.8.62:42682

		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)

		at hudson.remoting.Request.call(Request.java:202)

		at hudson.remoting.Channel.call(Channel.java:954)

		at hudson.EnvVars.getRemote(EnvVars.java:408)

		at hudson.model.Computer.getEnvironment(Computer.java:1187)

		at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:662)

		at hudson.model.ResourceController.execute(ResourceController.java:97)

		at hudson.model.Executor.run(Executor.java:429)

Caused: hudson.remoting.RequestAbortedException

	at hudson.remoting.Request.abort(Request.java:340)

	at hudson.remoting.Channel.terminate(Channel.java:1038)

	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)

	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)

	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)

	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)

	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)

	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)

	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)

	at hudson.remoting.Channel.close(Channel.java:1450)

	at hudson.remoting.Channel.close(Channel.java:1403)

	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:746)

	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:99)

	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:664)

	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Finished: FAILURE
```

**Comment by haojin2** [comment] 2018-07-11 20:20
Suggest Labels: CI, Bug

**Comment by marcoabreu** [comment] 2018-07-12 09:53
Duplicate of https://github.com/apache/incubator-mxnet/issues/11644

**Closed** 2018-07-12 09:53 UTC
Labels: Bug, CI
