### ISSUE TITLE
ArgSort binds to a float64 array but forward fails

### ISSUE THREAD

**Issue by sbodenstein** [apache/incubator-mxnet#11966] opened 2018-08-01 13:22 UTC
`ArgSort` should work on any type, or at least fail during binding if an invalid type is given. But:
```
import numpy as np
import mxnet as mx

t = "float64"
s=mx.sym.argsort(mx.sym.Variable("data", dtype=t))
d=mx.nd.ones((1,2,6,6), dtype=t)
e=s.bind(mx.cpu(), {'data': d})

<mxnet.executor.Executor at 0x1a13610a20>
```
But then:
```
e.forward()

MXNetError: [16:25:29] include/mxnet/./tensor_blob.h:203: Check failed: mshadow::DataType<DType>::kFlag == type_flag_ TBlob.get_with_shape: data type do not match specified type.Expected: 1 v.s. given 0
```
This works if `t="float32"`.

**Comment by Roshrini** [comment] 2018-08-01 17:59
Thanks for finding and reporting this issue.
@anirudh2290 Can you please add labels: Operator, Bug

**Comment by haojin2** [comment] 2018-08-02 17:05
Related issue: #11156, the root cause for this issue is that topk implementation only supports float32.

**Comment by apeforest** [comment] 2018-09-12 18:28
This is a feature request, not a bug. @anirudh2290 Could you please remove the [Bug] label and add [Feature Request]? Thx

**Comment by apeforest** [comment] 2018-09-18 03:31
@nswamy Could you please remove the [Bug] label and add [Feature Request]? Thanks

**Comment by anirudh2290** [comment] 2018-09-18 18:56
My opinion is that it is still a bug because it doesn't say clearly that float64 is not supported for this op. We cannot expect users to know what 1 or 0 maps to or what the error really means. The #11156 resolution is a good improvement in the error messaging.  I know many ops in MXnet don't do this currently, but a better way is to check for dtypes supported for the op inputs in InferType and error accordingly even before the forward is called.

**Comment by apeforest** [comment] 2018-09-18 19:00
@anirudh2290 As @haojin2 commented #11156 has already updated the error message, so it is now considered a feature request to support float64. Thanks!

**Comment by apeforest** [comment] 2018-09-18 19:45
@anirudh2290 I just tried to run the example in latest master and the issue seems have been resovled. Please verify and close this issue if you can confirm. Thanks.

**Comment by anirudh2290** [comment] 2018-09-18 20:43
@apeforest Thanks for confirming that the issue with respect to error message is fixed. Another issue as raised here , is about error being raised in forward instead of bind call. I know that there may be many operators which have this check in Forward instead of InferType. I have created a new discuss issue for the same and we can close this issue.

**Closed by anirudh2290** 2018-09-18 20:43 UTC
Labels: Bug, Operator
