### ISSUE TITLE
Flaky test: test_operator_gpu.test_sgd

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#10945] opened 2018-05-15 03:28 UTC
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10939/4/pipeline
```
======================================================================

FAIL: test_operator_gpu.test_sgd

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/../unittest/test_optimizer.py", line 233, in test_sgd

    compare_optimizer(opt1(**kwarg), opt2(**kwarg), shape, dtype)

  File "/work/mxnet/tests/python/gpu/../unittest/test_optimizer.py", line 109, in compare_optimizer

    assert_almost_equal(w1.asnumpy(), w2.asnumpy(), rtol=rtol, atol=atol)

  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 2.892578 exceeds tolerance rtol=0.000100, atol=0.000010.  Location of maximum error:(2, 1, 0), a=0.110718, b=0.110657

 a: array([[[0.2059 , 0.262  , 0.873  , 0.1854 , 0.4    ],

        [0.4265 , 0.7393 , 0.1344 , 0.9272 , 0.2896 ],

        [0.5513 , 0.935  , 0.9316 , 0.8315 , 0.638  ],...

 b: array([[[0.2059 , 0.262  , 0.873  , 0.1854 , 0.4    ],

        [0.4265 , 0.7393 , 0.1344 , 0.9272 , 0.2896 ],

        [0.5513 , 0.935  , 0.9316 , 0.8315 , 0.638  ],...

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1308113146 to reproduce.

--------------------- >> end captured logging << ---------------------

```

**Comment by ThomasDelteil** [comment] 2018-05-17 17:46
Happened to me as well here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10959/8/pipeline/703

**Comment by larroy** [comment] 2018-06-05 15:29
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11138/1/pipeline

**Comment by larroy** [comment] 2018-06-14 11:31
I couldn't reproduce these failures locally with ubuntu 16.04 and a Titan V. (I didn't use nvidia docker)

**Comment by szha** [comment] 2018-06-17 23:47
Thanks.

**Comment by larroy** [comment] 2018-06-18 18:13
@szha still we have seen it happening in CI, so I don't think we should close until we are sure it's not happening in CI anymore.

**Comment by haojin2** [comment] 2018-06-18 18:16
@larroy could you provide some links to the failed tests? I'll take a look.

**Comment by szha** [comment] 2018-06-18 18:32
Hi @larroy, I wasn't aware of additional errors so please excuse me. Also, do share the links of additional failures so that @haojin2 can take a look.

**Comment by larroy** [comment] 2018-06-20 00:39
Hi @szha @haojin2 I think this is a misunderstanding. Apologies. I don't have any evidence that the failure is still ocurring. I was actually not aware a fix has been committed, this would explain why I was not able to reproduce. If you have not seen this happening again then we can close.

**Closed by larroy** 2018-06-20 00:39 UTC
Labels: Flaky, Optimizer, Test
