### ISSUE TITLE
Crash on matrix multiplication in windows

### ISSUE THREAD

**Issue by gabgoh** [apache/incubator-mxnet#2565] opened 2016-06-29 03:13 UTC
The following code causes mxnet to crash, any idea why? 

```
>>> x = mx.nd.ones((3, 6))
>>> y = mx.nd.ones((6,3))
>>> mx.nd.dot(x,y)
<mxnet.ndarray.NDArray object at 0x000000000367D8D0>
```

python crashes, at this point.

The wrappers do not appear to be responsible, as it crashes on both julia and python. It works on the GPU, and it works on mac

any idea why?

**Comment by sxjscience** [comment] 2016-06-29 03:22
Try to check the blas install.

**Comment by gabgoh** [comment] 2016-06-29 03:24
how do I do that?

**Comment by sxjscience** [comment] 2016-06-29 04:34
@gabgoh Could you run MNIST classification example correctly on CPU? Since `dot` will be handled by the BLAS engine, it's probably caused by some installation/linking problems of BLAS.

**Comment by sxjscience** [comment] 2017-09-28 04:23
Close it now. Feel free to reopen it.

**Closed by sxjscience** 2017-09-28 04:23 UTC
