### ISSUE TITLE
The net uses MAERegressionOutput loss，why softmax_label is raised in the Error 

### ISSUE THREAD

**Issue by allenlverson** [apache/incubator-mxnet#3615] opened 2016-10-25 14:17 UTC
I build a net as follows:
def get_symbol(num_classes = 1):
    input_data = mx.symbol.Variable(name="data")
    # stage 1
    conv1 = mx.symbol.Convolution(
        data=input_data, kernel=(7, 7), stride=(1, 1), num_filter=50)
    pool1 = mx.symbol.Pooling(
        data=conv1, pool_type="max", kernel=(26, 26), stride=(1,1))
    pool2 = mx.symbol.Pooling(
        data=conv1, pool_type="avg", kernel=(26, 26), stride=(1,1))
    fc1 = mx.symbol.Concat(*[pool1, pool2], dim = 1)
    flatten = mx.symbol.Flatten(data=fc1, name="flatten1")
    fc2 = mx.symbol.FullyConnected(data=flatten, num_hidden=800)
    fc3 = mx.symbol.FullyConnected(data=fc2, num_hidden=800)
    fc4 = mx.symbol.FullyConnected(data=fc3, num_hidden=1)
    MAEr = mx.symbol.MAERegressionOutput(data=fc3)
    return MAEr

I wish to map a patch into a single value ,so the final Fullconneted hidden num =1, The I use the MAER as the loss function.
But the
 model.fit(
        X                  = train,
        eval_data          = val,
        eval_metric        = eval_metrics,
        kvstore            = kv,
        batch_end_callback = batch_end_callback,
        epoch_end_callback = checkpoint)
gives an error :
 raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [22:09:48] src/symbol/symbol.cc:155: Symbol.InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
    [0]data
    [1]convolution0_weight
    [2]convolution0_bias
    [3]fullyconnected0_weight
    [4]fullyconnected0_bias
    [5]fullyconnected1_weight
    [6]fullyconnected1_bias
    [7]maeregressionoutput0_label
Why the error says ,can not find softmax_label? I do not use the SoftmaxLayer!

**Comment by piiswrong** [comment] 2016-10-25 17:07
softmax_label is the default name of data iterator's output. If you are not using that name you need to change your data iter.
That said its easier to just do
`MAEr = mx.symbol.MAERegressionOutput(data=fc3, name='softmax')

**Comment by allenlverson** [comment] 2016-10-26 03:49
@piiswrong Thank your for your reply.I undestand what you said!
But why the softmax_label is the default? If I use LinearRegressionOutput ,LogisticrRegressionPutput，MAERegressionOutput...all of the 'name 'must be set to softmax ?

The I change the name to 'softmax' But another error occur s:
mxnet.base.MXNetError: InferShape Error in softmax's label argument
Corresponding keyword of symbol: softmax_label
Shape inconsistent, Provided =(128,), inferred shape=(128,800)?

**Comment by whaozl** [comment] 2017-02-07 02:43
Because softmax_label is the default name of data iterator's output **Unless you define a data iterator**

**Comment by juilin** [comment] 2017-03-09 09:17
Check how the variable **model** is created. The parameter **label_names** contains 'softmax_label' only by default.

class Module(BaseModule):

    label_names : list of str
        Default is `('softmax_label')` for a typical model used in image
        classification.

**Comment by piyushghai** [comment] 2018-10-09 21:09
@allenlverson I believe your question has been answered. 
To summarize the issue : 
One can specify a custom label name when you define your own data iterator.
Eg : 
```
MAEr = mx.symbol.MAERegressionOutput(data=fc3, name='softmax')
```

@sandeep-krishnamurthy Requesting this issue to be closed. 

@allenlverson Please feel free to re-open the issue if closed in error :)

Thanks!

**Closed** 2018-10-09 22:01 UTC
Labels: Unclear Error/Doc
