### ISSUE TITLE
unit test test_ndarray.test_ndarray_indexing fails

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#9116] opened 2017-12-18 05:08 UTC
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)
I clone the master branch of mxnet from github and compile it with `make -j16 USE_OPENCV=1 USE_BLAS=openblas`. Then I ran the unit test `nosetests -v tests/python/unittest/test_ndarray.py:test_ndarray_indexing` and got the following error. Is this a known problem?

```
$ nosetests -v tests/python/unittest/test_ndarray.py:test_ndarray_indexing
test_ndarray.test_ndarray_indexing ... FAIL

======================================================================
FAIL: test_ndarray.test_ndarray_indexing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/incubator-mxnet/tests/python/unittest/test_ndarray.py", line 928, in test_ndarray_indexing
    test_setitem(np_array, index[0], index[1])
  File "/home/ubuntu/incubator-mxnet/tests/python/unittest/test_ndarray.py", line 864, in test_setitem
    assert_same(np_array, np_index, mx_array, index, np.random.randint(low=-10000, high=0))
  File "/home/ubuntu/incubator-mxnet/tests/python/unittest/test_ndarray.py", line 837, in assert_same
    assert same(np_array, mx_array.asnumpy())
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.263s

FAILED (failures=1)

```

## Environment info (Required)

I test it in the EC2 m4.4xlarge.

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using Python)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) `

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

3b7134a5271d298252bf3d526e1cdfe79a686f37

Build config:
(Paste the content of config.mk, or the build command.)

make -j16 USE_OPENCV=1 USE_BLAS=openblas

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by reminisce** [comment] 2017-12-19 05:41
I was not able to reproduce the error on Ubuntu and MacOS. Will dig deeper.

**Comment by ankkhedia** [comment] 2018-06-22 20:35
Couldn't reproduce the issue for 10000 runs on the setup mentioned in the issue.

**Comment by sandeep-krishnamurthy** [comment] 2018-07-02 03:49
Can you please confirm you tried with same build that was failing before? For example, I had a test that was failing only with cu90-mkl build but not only with cu90.

**Comment by ankkhedia** [comment] 2018-07-02 16:54
@sandeep-krishnamurthy I used the same build instructions as was mentioned in the issue and couldn't reproduce it.

**Comment by marcoabreu** [comment] 2018-07-03 09:18
There are no record of recent failures. Closing

**Closed by marcoabreu** 2018-07-03 09:18 UTC
Labels: Flaky, Test
