### ISSUE TITLE
Install from pre-built binaries failing

### ISSUE THREAD

**Issue by mdtdev** [apache/incubator-mxnet#11822] opened 2018-07-19 15:01 UTC
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Following the instructions at: https://mxnet.apache.org/install/index.html?platform=MacOS&language=R&processor=CPU fail to install mxnet.

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.3
Compiler     : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
Build        : ('default', 'Oct  6 2017 12:04:38')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 10.0.1
Directory    : /Users/XXXXXX/anaconda3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Darwin-17.6.0-x86_64-i386-64bit
system       : Darwin
node         : XXXXXX.local
release      : 17.6.0
version      : Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT2018; root:xnu-4570.61.1~1/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.brand_string: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TMPBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID FPU_CSDS'
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT RDTSCP TSCI'
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0234 sec, LOAD: 0.4682 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0465 sec, LOAD: 0.4947 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0796 sec,LOAD: 0.5364 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0474 sec, LOAD: 0.6981 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0288 sec, LOAD: 0.6707 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0281 sec, LOAD: 0.2254 sec.
```

Package used (Python/R/Scala/Julia):
R. Session info follows...

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] topicmodels_0.2-7 quanteda_1.3.0   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17       lubridate_1.7.4    lattice_0.20-35   
 [4] tidyr_0.8.1        visNetwork_2.0.4   assertthat_0.2.0  
 [7] digest_0.6.15      slam_0.1-43        R6_2.2.2          
[10] plyr_1.8.4         stats4_3.5.1       ggplot2_3.0.0     
[13] pillar_1.3.0       rlang_0.2.1        lazyeval_0.2.1    
[16] rstudioapi_0.7     data.table_1.11.4  Matrix_1.2-14     
[19] DiagrammeR_1.0.0   downloader_0.4     readr_1.1.1       
[22] stringr_1.3.1      htmlwidgets_1.2    igraph_1.2.1      
[25] munsell_0.5.0      compiler_3.5.1     influenceR_0.1.0  
[28] rgexf_0.15.3       spacyr_0.9.9       pkgconfig_2.0.1   
[31] htmltools_0.3.6    tidyselect_0.2.4   tibble_1.4.2      
[34] gridExtra_2.3      XML_3.98-1.12      viridisLite_0.3.0 
[37] crayon_1.3.4       dplyr_0.7.6        grid_3.5.1        
[40] jsonlite_1.5       gtable_0.2.0       magrittr_1.5      
[43] scales_0.5.0       RcppParallel_4.4.0 stringi_1.2.3     
[46] viridis_0.5.1      bindrcpp_0.2.2     NLP_0.1-11        
[49] xml2_1.2.0         stopwords_0.9.0    brew_1.0-6        
[52] fastmatch_1.1-0    RColorBrewer_1.1-2 tools_3.5.1       
[55] stm_1.3.3          glue_1.2.0         purrr_0.2.5       
[58] hms_0.4.2          wordVectors_2.0    Rook_1.1-1        
[61] rsconnect_0.8.8    parallel_3.5.1     yaml_2.1.19       
[64] tm_0.7-4           colorspace_1.3-2   bindr_0.1.1       
[67] modeltools_0.2-21 
```

## Build info (Required if built from source)

Not built from source.

## Error Message:

```
> library("mxnet")
Error: package or namespace load failed for ‘mxnet’:
 .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so, 10): Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/mxnet/libs/libmxnet.so
  Reason: image not found
```

## Minimum reproducible example
Literally the error shows up on running the `library()` function for mxnet:

```
> library("mxnet")
```

## Steps to reproduce
See above.

1. We followed the instructions on the website cited above for install:

```
cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
options(repos = cran)
install.packages("mxnet")
```
2. Then we tried to load the library:
```
library(mxnet)
```
3. Error message as above.

## What have you tried to solve it?

1. Tried to reinstall.
2. Not much else as I am not at all expert in this! Sorry!

**Comment by mdtdev** [comment] 2018-07-19 15:08
Let me add the note that this was discovered in a workshop and problems showed up for both Windows boxes and Macs, however the Windows boxes are loading the libraries and failing to work after that. I cannot provide that info, and most people at this workshop cannot use their command lines much less have github for providing info. Not sure if that is relevant.

**Comment by ankkhedia** [comment] 2018-07-19 17:00
hi @mdtdev Could you please provide me the minimum reproducible code which fails in Windows?

@anirudhacharya Could you please help look into Mac issue?

**Comment by mdtdev** [comment] 2018-07-19 17:33
Unfortunately no, @ankkhedia, I cannot.  I have asked one of the people with a Windows box to do so. Well, actually maybe I can, they got the install to look ok, and the library mounted ok, but it failed to let them try the test code:
```
library(mxnet)
a <- mx.nd.ones(c(2,3), ctx = mx.cpu())
```
The error happened after the `a <-` line, but I do not have access to the error message. Sorry!

**Comment by hetong007** [comment] 2018-07-19 17:41
@mdtdev In your system terminal, please run

```
brew install openblas opencv
```

If it complains, please try to execute with `sudo`, as

```
sudo brew install openblas opencv
```

then try to install the package again.

**Comment by ankkhedia** [comment] 2018-07-19 17:48
@mdtdev The above instructions for Windows works for me and I am not getting error. Might be some additional dependencies required but cannot comment exactly unless we get hold of the exact error message.

**Comment by hetong007** [comment] 2018-07-19 17:49
@ankkhedia The exact error message is there:

```
Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.1.dylib
```

**Comment by mdtdev** [comment] 2018-07-19 17:52
@hetong007 Thank you, that appears to have fixed it. Is that something missing from the installation and setup instructions? Or did I miss something big somewhere?  But for me it seems to have fixed it, so thanks! 

```
library(mxnet)
a <- mx.nd.ones(c(2,3), ctx = mx.cpu())
b <- a * 2 + 1
b
``` 
shows the desired test result.

**Comment by ankkhedia** [comment] 2018-07-19 17:54
@hetong007 I was talking about Windows error which @mdtdev mentioned in the issue description.

**Comment by hetong007** [comment] 2018-07-19 17:57
@mdtdev It'll be a temporary fix. We are working to resolve the dependency issues.

@ankkhedia You are correct, I overlooked that piece. I don't recall similar reports after the update two weeks ago.

**Comment by anirudhacharya** [comment] 2018-07-23 17:43
@mdtdev you said "... this was discovered in a workshop and problems showed ...".

I would like to hear more of your use-case for using this R-package. Could you please leave a note at anirudhkrec [at] gmail.com and i will follow up.

**Comment by nswamy** [comment] 2018-07-27 23:13
closing this issue as it seems to be resolved.

**Closed by nswamy** 2018-07-27 23:13 UTC
Labels: Installation, R
