### ISSUE TITLE
NaiveEngine is not threadsafe and crashes when called from multiple threads.

### ISSUE THREAD

**Issue by piiswrong** [apache/incubator-mxnet#12128] opened 2018-08-10 18:38 UTC
MXNet with NaiveEngine crashes when called from multiple threads. ThreadedEngine works fine.

**Comment by srochel** [comment] 2018-09-02 20:43
@piiswrong - do you have a simple reproducer?

**Comment by piyushghai** [comment] 2018-10-08 21:55
@piiswrong Can you give a minimum reproducible example for this crash that you are facing ?

**Comment by anirudhacharya** [comment] 2019-03-06 19:58
The following code runs fine when run with `MXNET_ENGINE_TYPE=NaiveEngine`

```python
import threading
import mxnet as mx

def worker(module, input1, input2, lock,  outputs):
    o1 = mx.nd.broadcast_add(input1, input2)
    o2 = mx.nd.broadcast_mul(o1, input1)
    o3 = mx.nd.broadcast_mul(input2, o2) 
    outnd = o2 + o3
    outnd.wait_to_read()
    with lock:
        outputs.append(outnd)

threads = []
outputs = []
lock = threading.Lock()
for i in range(3):
    thread = threading.Thread(target=worker, args=(net, mx.random.randn(1, 3, 10), mx.random.randn(1, 3, 10), lock, outputs))
    threads.append(thread)
                                                                                                                                                                
for thread in threads:
    thread.start()
for thread in threads:
    thread.join()

for i in  outputs:
    print(i)
```

I think we can close this issue unless the author still has pending concerns.

**Comment by anirudh2290** [comment] 2019-03-08 03:33
Closing since non-issue. @anirudhacharya can you please also check gluon and open a new issue if required.

**Closed by anirudh2290** 2019-03-08 03:33 UTC
Labels: Bug
