### ISSUE TITLE
class mxnet.gluon.rnn.RNN has a mistake  default activation function in official document.

### ISSUE THREAD

**Issue by xiaotao321** [apache/incubator-mxnet#10257] opened 2018-03-27 02:59 UTC
## Description
class mxnet.gluon.rnn.RNN has a mistake  default activation function in official document.

## Error Message:
[here](https://mxnet.incubator.apache.org/api/python/gluon/rnn.html#mxnet.gluon.rnn.RNN) has a conflict about the default activation function of RNN.

class mxnet.gluon.rnn.RNN(hidden_size, num_layers=1, **activation='relu'**, layout='TNC', dropout=0, bidirectional=False, i2h_weight_initializer=None, h2h_weight_initializer=None, i2h_bias_initializer='zeros', h2h_bias_initializer='zeros', input_size=0, **kwargs)

Parameters:  activation ({'relu' or 'tanh'}, **default 'tanh'**) – The activation function to use.

**Comment by sxjscience** [comment] 2018-03-27 03:02
Duplicate of https://github.com/apache/incubator-mxnet/issues/10152

**Closed by sxjscience** 2018-03-27 03:02 UTC
Labels: Duplicate
