### ISSUE TITLE
mxnet crashes ungracefully if one feeds the output of SwapAxis to SoftmaxOutput as label

### ISSUE THREAD

**Issue by SkidanovAlex** [apache/incubator-mxnet#1069] opened 2015-12-25 21:00 UTC
So I have a model that produces `batch_size x num_outputs x num_classes` outputs, and I have true labels that has shape of `batch_size x num_outputs x num_classes`. Since `SoftmaxOutput` expects `num_classes` to be the second dimension, I swap axis for both of them. Here's an example snippet:

```
import mxnet as mx

x = mx.sym.Variable("x")
y = mx.sym.Variable("y")
w1 = mx.sym.Variable("w1")

model = mx.sym.FullyConnected(data=x, weight=w1, num_hidden=30, name="fc")
model = mx.sym.Reshape(data=model, target_shape=(128, 3, 5, 2), name="reshape")
y = mx.sym.SwapAxis(data=y, dim1=1, dim2=2, name="reshape")
model = mx.sym.SoftmaxOutput(data=model, multi_output=True, label=y, name="output")

arg_names = model.list_arguments()
arg_shape, out_shape, aux_shape = model.infer_shape(x=(128, 10))

print zip(arg_names, arg_shape)
```

It produces the following output:

`[('x', (128L, 10L)), ('w1', (30L, 10L)), ('fc_bias', (30L,)), ('y', ())]`

Note that the inferred shape of `y` is `()`. It is not `None`, which would indicate that it can't be inferred according to the docs (in practice I actually observe that if something cannot be inferred, the entire output of `infer_shape` is `None`, not specific elements of the returned list, which contradicts the docs, but it is a separate issue). If then I proceed with assigning `zeros` to all the parameters, it core dumps, which I assume is because the shape is empty.

Now, I realize what I'm doing wrong (the correct shape of `y` would be `(128, 10)`, in which case swapping first and second axis makes no sense), so the issue here is that `mxnet` doesn't fail gracefully during `infer_shape`, but rather crashes completely at a later stage.

Or, in general, `infer_shape` should fail if any inferred shape is empty, because it seems to cause any consecutive operation on that variable to crash.

**Comment by SkidanovAlex** [comment] 2015-12-26 20:14
If someone can confirm that the case when the inferred shape is `()` is never valid, I can send a PR with one of the two fixes:

1. Make `infer_shape` return `None` if one of the shapes is `()`

2. Make `infer_shape` throw an exception if one of the shapes is `()`

**Comment by piiswrong** [comment] 2015-12-27 20:10
I think this is caused by a missing CHECK on the C++ side. I would look into src/operator/softmax_output-inl.h:infer_shape. You are welcome to contribute a PR. Thanks!

**Comment by sandeep-krishnamurthy** [comment] 2017-05-30 20:11
@piiswrong - I think this is fixed - https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_output-inl.h#L257 
If yes, can you please close this issue?
If not, can you add some more details on the fix?

**Comment by yajiedesign** [comment] 2017-09-28 03:46
look like fix.closed.

**Closed by yajiedesign** 2017-09-28 03:46 UTC
