### ISSUE TITLE
MXNET Scala package build failed

### ISSUE THREAD

**Issue by Aman1994** [apache/incubator-mxnet#11303] opened 2018-06-15 12:38 UTC
I tried these following steps while building:

sudo apt-get update
sudo apt-get install -y build-essential git
sudo apt-get install -y libopencv-dev
git clone --recursive https://github.com/dmlc/mxnet
cd mxnet
make -j 4 USE_OPENCV=1 USE_BLAS=openblas
make scalapkg

While doing the make scalapgk I was facing an error like -

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MXNet Scala Package - Parent ....................... SUCCESS [  1.616 s]
[INFO] MXNet Scala Package - Initializer .................. SUCCESS [  0.395 s]
[INFO] MXNet Scala Package - Initializer Native Parent .... SUCCESS [  0.035 s]
[INFO] MXNet Scala Package - Initializer Native Linux-x86_64 FAILURE [  1.657 s]
[INFO] MXNet Scala Package - Macros ....................... SKIPPED
[INFO] MXNet Scala Package - Core ......................... SKIPPED
[INFO] MXNet Scala Package - Native Parent ................ SKIPPED
[INFO] MXNet Scala Package - Native Linux-x86_64 CPU-only . SKIPPED
[INFO] MXNet Scala Package - Inference .................... SKIPPED
[INFO] MXNet Scala Package - Examples ..................... SKIPPED
[INFO] MXNet Scala Package - Spark ML ..................... SKIPPED
[INFO] MXNet Scala Package - Full Parent .................. SKIPPED
[INFO] MXNet Scala Package - Full Linux-x86_64 CPU-only ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.487 s
[INFO] Finished at: 2018-06-15T18:07:35+05:30
[INFO] Final Memory: 19M/216M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-alpha-7:link (default-link) on project libmxnet-init-scala-linux-x86_64: Error executing command line. Exit code:1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :libmxnet-init-scala-linux-x86_64
Makefile:577: recipe for target 'scalapkg' failed
make: *** [scalapkg] Error 1

**Comment by kalyc** [comment] 2018-06-15 18:46
Thanks for opening this issue @Aman1994 
@nswamy could you add label "Scala" "Build" "Bug" here?
@lanking520

**Comment by lanking520** [comment] 2018-06-15 18:51
@Aman1994 Hi, can you tell me which System image you are running? You need to install opencv and openblas if you haven't got them install on your linux machine

**Comment by Aman1994** [comment] 2018-06-18 05:17
@lanking520 I am running on Ubuntu 18.04 and I have installed both the opencv and openblas. But still the problem persists.

**Comment by nswamy** [comment] 2018-06-18 11:30
@Aman1994 for building from source, could you please edit the Makefile and change `mvn package`.. to `mvn -X package`..... 
`make scalapkg >/tmp/x.txt 2>&1`. Upload the file here, we can take a look

**Comment by nswamy** [comment] 2018-06-18 11:32
what is the issue you are facing when you use the pre-built jar from maven?, could you also please let us know by running with mvn -X

**Comment by Aman1994** [comment] 2018-06-18 11:39
@nswamy here is the file 
[x.txt](https://github.com/apache/incubator-mxnet/files/2111076/x.txt)

**Comment by nswamy** [comment] 2018-06-18 12:35
@Aman1994 did you build the MXNet binaries before you attempted make scalpkg? 
http://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=Python&processor=CPU

**Comment by Aman1994** [comment] 2018-06-18 12:42
@nswamy As pointed earlier I followed these particular steps as pointed out in documentation
sudo apt-get update
sudo apt-get install -y build-essential git
sudo apt-get install -y libopencv-dev
git clone --recursive https://github.com/dmlc/mxnet
cd mxnet
make -j 4 USE_OPENCV=1 USE_BLAS=openblas
make scalapkg

**Comment by gigasquid** [comment] 2018-06-18 17:08
From the file uploaded, looks like it's failing here:

```
/bin/sh -c cd /home/aman/mxnet/scala-package/init-native/linux-x86_64 && g++ -shared -o/home/aman/mxnet/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so target/objs/org_apache_mxnet_init_native_c_api.o -Wl,--whole-archive /home/aman/mxnet/3rdparty/dmlc-core/libdmlc.a /home/aman/mxnet/3rdparty/tvm/nnvm/lib/libnnvm.a /home/aman/mxnet/lib/libmxnet.a -Wl,--no-whole-archive -pthread -lm -lcblas -fopenmp -lrt -lopencv_dnn -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_viz -lopencv_core -fopenmp
/usr/bin/x86_64-linux-gnu-ld: cannot find -lcblas
```
@Aman1994 Maybe you can double check the openblas installation?
` sudo apt-get install -y libopenblas-dev liblapack-dev`

**Comment by lanking520** [comment] 2018-06-18 17:10
Hi @gigasquid I follow the same steps and also stuck in here. I think we need to configure ld path in here to make sure it loads openblas properly

**Comment by lanking520** [comment] 2018-06-18 17:33
In addition, I would like to request for update the installation guide:
```
sudo apt-get install maven
sudo add-apt-repository ppa:openjdk-r/ppa  
sudo apt-get update   
sudo apt-get install openjdk-7-jdk  
```
We need to install maven and open-jdk to get scala package build. @aaronmarkham can you keep track on this thread and let's summarize the installation process once the problem solved

**Comment by lanking520** [comment] 2018-06-18 21:40
@Aman1994 Please try with the follows:
```
sudo apt-get install libatlas-base-dev
ld -lcblas --verbose
```
To test if cblas is installed. It seemed openblas didn't bring cblas together even if it is a required dependency. atlas will install cblas for you.

**Comment by Aman1994** [comment] 2018-06-19 11:20
@lanking520 trying the above helped me resolve that particular issue. But now I am facing a different issue.
[INFO] --- exec-maven-plugin:1.6.0:java (apidoc-generation) @ mxnet-macros_2.11 ---
Java HotSpot(TM) Server VM warning: You have loaded library /home/aman/Documents/incubator-mxnet/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[WARNING] 
java.lang.UnsatisfiedLinkError: /home/aman/Documents/incubator-mxnet/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so: /home/aman/Documents/incubator-mxnet/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
    at java.lang.ClassLoader$NativeLibrary.load (Native Method)
    at java.lang.ClassLoader.loadLibrary0 (ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary (ClassLoader.java:1824)
    at java.lang.Runtime.load0 (Runtime.java:809)
    at java.lang.System.load (System.java:1086)
    at org.apache.mxnet.init.Base$.tryLoadInitLibrary (Base.scala:49)
    at org.apache.mxnet.init.Base$.<init> (Base.scala:21)
    at org.apache.mxnet.init.Base$.<clinit> (Base.scala)
    at org.apache.mxnet.APIDocGenerator$.getSymbolNDArrayMethods (APIDocGenerator.scala:113)
    at org.apache.mxnet.APIDocGenerator$.absClassGen (APIDocGenerator.scala:44)
    at org.apache.mxnet.APIDocGenerator$.main (APIDocGenerator.scala:38)
    at org.apache.mxnet.APIDocGenerator.main (APIDocGenerator.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MXNet Scala Package - Parent ....................... SUCCESS [  9.153 s]
[INFO] MXNet Scala Package - Initializer .................. SUCCESS [ 10.725 s]
[INFO] MXNet Scala Package - Initializer Native Parent .... SUCCESS [  0.090 s]
[INFO] MXNet Scala Package - Initializer Native Linux-x86_64 SUCCESS [  6.921 s]
[INFO] MXNet Scala Package - Macros ....................... FAILURE [ 11.239 s]
[INFO] MXNet Scala Package - Core ......................... SKIPPED
[INFO] MXNet Scala Package - Native Parent ................ SKIPPED
[INFO] MXNet Scala Package - Native Linux-x86_64 CPU-only . SKIPPED
[INFO] MXNet Scala Package - Inference .................... SKIPPED
[INFO] MXNet Scala Package - Examples ..................... SKIPPED
[INFO] MXNet Scala Package - Spark ML ..................... SKIPPED
[INFO] MXNet Scala Package - Full Parent .................. SKIPPED
[INFO] MXNet Scala Package - Full Linux-x86_64 CPU-only ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.015 s
[INFO] Finished at: 2018-06-19T16:47:35+05:30
[INFO] Final Memory: 21M/113M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (apidoc-generation) on project mxnet-macros_2.11: An exception occured while executing the Java class. /home/aman/Documents/incubator-mxnet/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so: /home/aman/Documents/incubator-mxnet/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mxnet-macros_2.11
Makefile:584: recipe for target 'scalapkg' failed
make: *** [scalapkg] Error 1

**Comment by lanking520** [comment] 2018-06-19 15:47
Thanks for your reply, I am really grateful for your ongoing discovery. This issue might related to an Architecture problem, it seemed the package were built in the X86 environment however system try to find 64bit library. I will be keep on finding any possible solutions for your case. 

However, I do encourage you to try to build on AWS Deep Learning AMI which is existed in EC2 preconfiguration. You would have seamless experience as all library are pre-installed there and all you need to do is make the package. Alternatively, there is a v1.2.1 version of Scala package released on Maven yesterday, you can directly imported that on your computer.

**Comment by lanking520** [comment] 2018-06-19 17:41
@Aman1994 as far as I can tell, explained in this [thread](https://groups.google.com/forum/#!topic/comp.lang.java.programmer/s4sxjtM8um4). The problem should be the JVM you are using currently does not match the native library. Use this line of code to check the version:
```
java -version
```
And try to install 64-bit version of Java and build again.

**Comment by aaronmarkham** [comment] 2018-06-19 18:10
You may want to try this pathway for your software installs:
https://github.com/apache/incubator-mxnet/blob/master/ci/docker/install/ubuntu_scala.sh
Then follow up with `make` then `make scalapkg` then `make scalainstall`.
I have some better instructions in a pending PR here: https://github.com/apache/incubator-mxnet/pull/11152

**Comment by Aman1994** [comment] 2018-06-20 04:49
@lanking520 I tried java --version. I guess my java version is of 64 bit.
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by lanking520** [comment] 2018-06-21 04:41
Hi @Aman1994 sorry for the late reply. I cannot reproduce the same issue you have, but let's add @yzhliu involved to see how we can solve this problem.

**Comment by lanking520** [comment] 2018-06-27 20:57
Hi @Aman1994 Sorry for the late response. I opened a clean 16.04 Ubuntu Machine and install all the dependencies all over again and did not see the same issues you have. Please try the followings:

## Step 1 Install Ubuntu Core MXNet dependencies
Copy and run [these commands](https://github.com/apache/incubator-mxnet/blob/master/ci/docker/install/ubuntu_core.sh)
## Step2 Install Scala Specific packages
Copy and tun [these commands](https://github.com/apache/incubator-mxnet/blob/master/ci/docker/install/ubuntu_scala.sh)
## Step3 make the package
```
git clone --recursive https://github.com/dmlc/mxnet
cd mxnet
make -j 4 USE_OPENCV=1 USE_BLAS=openblas
make scalapkg
```

Hope this helps. I will try 18.04 also if time permitted.

**Comment by Aman1994** [comment] 2018-06-28 10:42
@lanking520 Earlier I was trying the build on 18.04 and its continuously failing. Today i tried on 16.04 and its building successfully. So, I guess there is some architecture problem that is currently not compatible with 18.04.

**Comment by lanking520** [comment] 2018-06-28 21:19
@Aman1994 Thanks for trying the solution and MXNet Scala installation page will be updated very soon based on this feedback.

**Comment by nswamy** [comment] 2018-06-28 22:09
@marcoabreu do we have MXNet backend building on 18.04?

**Comment by marcoabreu** [comment] 2018-06-28 22:24
No, only Ubuntu 16.04

Naveen Swamy <notifications@github.com> schrieb am Fr., 29. Juni 2018,
00:09:

**Comment by nswamy** [comment] 2018-07-16 18:57
@Aman1994 I close this issue now, once we have support on the MXNet backend we'll revisit for Scala support as well.

**Closed by nswamy** 2018-07-16 18:57 UTC
Labels: Build, Scala
