### ISSUE TITLE
Error in numpy unit test

### ISSUE THREAD

**Issue by heaseny** [apache/incubator-mxnet#17384] opened 2020-01-20 02:59 UTC
## Description
When I ran the test  nosetests -s -v tests/python/unittest/test_numpy_interoperability.py:test_np_fallback_ops 
, it raised error "TypeError: No loop matching the specified signature and casting
was found for ufunc inv"

### Error Message
nosetests -s -v tests/python/unittest/test_numpy_interoperability.py:test_np_fallback_ops
test_numpy_interoperability.test_np_fallback_ops ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=94434600 to reproduce.
ERROR

======================================================================
ERROR: test_numpy_interoperability.test_np_fallback_ops
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mxnet/workspace/source/intel-mxnet/tests/python/unittest/common.py", line 215, in test_new
    orig_test(*args, **kwargs)
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/mxnet-1.6.0-py3.6.egg/mxnet/util.py", line 321, in _with_np_shape
    return func(*args, **kwargs)
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/mxnet-1.6.0-py3.6.egg/mxnet/util.py", line 505, in _with_np_array
    return func(*args, **kwargs)
  File "/home/mxnet/workspace/source/intel-mxnet/tests/python/unittest/test_numpy_interoperability.py", line 1916, in test_np_fallback_ops
    check_interoperability(op_list)
  File "/home/mxnet/workspace/source/intel-mxnet/tests/python/unittest/test_numpy_interoperability.py", line 1881, in check_interoperability
    _check_interoperability_helper(name, *workload['args'], **workload['kwargs'])
  File "/home/mxnet/workspace/source/intel-mxnet/tests/python/unittest/test_numpy_interoperability.py", line 1851, in _check_interoperability_helper
    out = onp_op(*args, **kwargs)
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1730, in cond
    invx = _umath_linalg.inv(x, signature=signature)
TypeError: No loop matching the specified signature and casting
was found for ufunc inv
-------------------- >> begin captured logging << --------------------
root: INFO: NumPy-shape semantics has been activated in your code. This is required for creating and manipulating scalar and zero-size tensors, which were not supported in MXNet before, as in the official NumPy library. Please DO NOT manually deactivate this semantics while using `mxnet.numpy` and `mxnet.numpy_extension` modules.
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=94434600 to reproduce.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
Dispatch test: heaviside
Dispatch test: spacing
Dispatch test: linalg.cond

### Steps to reproduce
nosetests -s -v tests/python/unittest/test_numpy_interoperability.py:test_np_fallback_ops

**Comment by haojin2** [comment] 2020-01-20 22:56
Hi, I'm not able to reproduce with latest master branch, which branch were you using? and what kind of build are you using?
```
nosetests -s -v tests/python/unittest/test_numpy_interoperability.py:test_np_fallback_ops
test_numpy_interoperability.test_np_fallback_ops ... Dispatch test: heaviside
Dispatch test: spacing
Dispatch test: linalg.cond
ok

----------------------------------------------------------------------
Ran 1 test in 0.007s

OK
```

**Comment by heaseny** [comment] 2020-01-21 01:51
The test can fail with  numpy==1.16.4, so should I upgrade my numpy?

**Comment by haojin2** [comment] 2020-01-21 01:53
I have 1.18.1, I'll try with my numpy downgraded.

**Comment by haojin2** [comment] 2020-01-24 21:55
@heaseny Hi, I just got the chance to try this out, and I was able to hit the same error, I'll be working on a fix for this, thanks for reporting the issue!

**Comment by haojin2** [comment] 2020-01-24 22:59
@heaseny Have you tried with the latest 1.18 version of numpy? I think it should solve the issue, after some investigation I found that the error is caused by numpy 1.17 being not able to handle the same input case.

**Comment by heaseny** [comment] 2020-01-24 23:10
Thank for your solution, I tried and found  the case could be successfull with latest numpy.


------------------
Thanks,
Xuecun

-------- 原始邮件 --------
发件人：Hao Jin <notifications@github.com>
时间：2020年1月25日 05:56
收件人：apache/incubator-mxnet <incubator-mxnet@noreply.github.com>
抄送：heaseny <yangxc_1@aliyun.com>,Mention <mention@noreply.github.com>
主题：Re: [apache/incubator-mxnet] Error in numpy unit test (#17384)

**Comment by TaoLv** [comment] 2020-01-26 13:42
Can we close this issue now or do you think we need another fix? I notice that mxnet requires numpy 1.16.0 - 2.0.0: https://github.com/apache/incubator-mxnet/blob/master/python/setup.py#L33

**Comment by heaseny** [comment] 2020-01-26 21:18
I think the requirement of numpy in setup.py should  be updated due to this issue. Can I get further feedback?

**Comment by haojin2** [comment] 2020-01-31 20:50
Since it's an issue related to numpy itself, we can probably change our test to skip this test for earlier numpy versions without having to change the requirements for just this one test, what do you think?

**Comment by heaseny** [comment] 2020-02-01 08:06
Thanks for your suggestion, this makes sense, I will close this issue.


------------------
Thanks,
Xuecun

-------- 原始邮件 --------
发件人：Hao Jin <notifications@github.com>
时间：2020年2月1日 04:50
收件人：apache/incubator-mxnet <incubator-mxnet@noreply.github.com>
抄送：heaseny <yangxc_1@aliyun.com>,Mention <mention@noreply.github.com>
主题：Re: [apache/incubator-mxnet] Error in numpy unit test (#17384)

**Comment by TaoLv** [comment] 2020-02-01 14:42
> Since it's an issue related to numpy itself, we can probably change our test to skip this test for earlier numpy versions without having to change the requirements for just this one test, what do you think?

I‘m afraid it's a real issue that the users may encounter in their use cases.

**Closed** 2020-04-10 05:18 UTC
Labels: Bug, Numpy
