### ISSUE TITLE
Make error 

### ISSUE THREAD

**Issue by yuyijie1995** [apache/incubator-mxnet#13996] opened 2019-01-26 01:04 UTC
When I want to build cpp package ,this error below just happened.
g++ -std=c++11 -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/users/yijie.yu/yuyijie/mxnet/3rdparty/mshadow/ -I/home/users/yijie.yu/yuyijie/mxnet/3rdparty/dmlc-core/include -fPIC -I/home/users/yijie.yu/yuyijie/mxnet/3rdparty/tvm/nnvm/include -I/home/users/yijie.yu/yuyijie/mxnet/3rdparty/dlpack/include -I/home/users/yijie.yu/yuyijie/mxnet/3rdparty/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -mf16c -I/usr/local/cuda-8.0/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/home/users/yijie.yu/yuyijie/mxnet/3rdparty/mkldnn/build/install/include -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_MKLDNN=1 -DUSE_MKL=1 -I/home/users/yijie.yu/yuyijie/mxnet/src/operator/nn/mkldnn/ -I/home/users/yijie.yu/yuyijie/mxnet/3rdparty/mkldnn/build/install/include -DMXNET_USE_OPENCV=1 -I/usr/include/opencv   -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free  -I/usr/include/openblas/ -I/home/users/yijie.yu/yuyijie/mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -Icpp-package/include -o build/cpp-package/example/lenet_with_mxdataiter cpp-package/example/lenet_with_mxdataiter.cpp -pthread -lm -lcudart -lcublas -lcurand -lcusolver -L/usr/local/cuda-8.0/lib64 -L/usr/local/cuda-8.0/lib -Wl,--as-needed -lmklml_intel -lmklml_gnu -liomp5 -L/home/users/yijie.yu/yuyijie/mxnet/3rdparty/mkldnn/build/install/lib/ -lopenblas -fopenmp -lrt -L/usr/local/hadoop-2.7.2/lib/native -lhdfs -L/usr/lib/jvm/java-1.7.0/jre/lib/amd64/server -ljvm -Wl,-rpath=/usr/lib/jvm/java-1.7.0/jre/lib/amd64/server -L/home/users/yijie.yu/yuyijie/mxnet/3rdparty/mkldnn/build/install/lib -lmkldnn -Wl,-rpath,'${ORIGIN}' -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab -lcudnn /usr/lib64/libtcmalloc.so  -lcufft -lcuda -lnvrtc -L/usr/local/cuda/lib64/stubs -L/home/users/yijie.yu/yuyijie/mxnet/lib -lmxnet
make: *** [build/cpp-package/example/mlp_csv] Error 1
make: *** Waiting for unfinished jobs....
But I still got the MxnetCpp.h file .How can I solve it or I just ignore it ?

**Comment by yuyijie1995** [comment] 2019-01-26 01:35
When I  #include "mxnet-cpp/MxNetCpp.h" ,and this error happened ,fatal error:mxnet/c_api.h:No such file or directory...

**Comment by frankfliu** [comment] 2019-01-28 03:50
@mxnet-label-bot add [question, build, C++]

**Comment by leleamol** [comment] 2019-02-14 18:39
@yuyijie1995 ,

I am not seeing "/home/users/yijie.yu/yuyijie/mxnet/include" directory in the above command line.

Can you please ensure the path ""/home/users/yijie.yu/yuyijie/mxnet/include"" is specified with "-I" option when you are building the example?

I hope this helps.
@mxnet-label-bot add [Pending Requester Info]

**Comment by yuyijie1995** [comment] 2019-02-15 13:29
I already solved it thanks a lot!




| |
俞依杰
|
|
邮箱：13588280094@163.com
|

签名由 网易邮箱大师 定制

On 02/15/2019 02:40, Amol Lele wrote:

@yuyijie1995 ,

I am not seeing "/home/users/yijie.yu/yuyijie/mxnet/include" directory in the above command line.

Can you please ensure the path ""/home/users/yijie.yu/yuyijie/mxnet/include"" is specified with "-I" option when you are building the example?

I hope this helps.
@mxnet-label-bot add [Pending Requester Info]

**Comment by leleamol** [comment] 2019-02-15 19:47
@yuyijie1995 
Thanks for the update.  If the issue is solved, I would recommend closing this issue.

**Comment by lanking520** [comment] 2019-02-19 20:38
@yuyijie1995 Close this issue for now. Please feel free to reopen if problem persist.

**Closed by lanking520** 2019-02-19 20:38 UTC
Labels: Build, C++, Good First Issue, Pending Requester Info, Question
