### ISSUE TITLE
Fused RNN Operators have nonsupport of `add` grad_req with mkl-dnn

### ISSUE THREAD

**Issue by zixuanweeei** [apache/incubator-mxnet#16578] opened 2019-10-22 02:22 UTC
Currently, we have not integrated the `add` grad_req routine in `FusedRNNCell` with mkl-dnn fusion. It will be highly appreciated if anyone could tell us the application scenario using `add` during the training process.

FYI, https://github.com/apache/incubator-mxnet/issues/568 and https://github.com/apache/incubator-mxnet/issues/725. When weights are updated every batch, `add` and `write` will produce the same results.

**Comment by ddavydenko** [comment] 2019-10-28 18:36
@mxnet-label-bot, add [Feature]

**Comment by ddavydenko** [comment] 2019-10-28 18:36
@mxnet-label-bot, add ["Feature request"]

**Comment by ddavydenko** [comment] 2019-10-28 18:41
@mxnet-label-bot add [MKLDNN]

**Comment by ddavydenko** [comment] 2019-10-28 18:42
@TaoLv , I suggest you got this issue verified once you have [Upgrade MKL-DNN dependency to v1.0 #16555] merged.

**Comment by pengzhao-intel** [comment] 2019-11-01 01:28
@zixuanweeei does the issue resolve by MKLDNN upgrade PR?

**Comment by zixuanweeei** [comment] 2019-11-01 01:36
> @zixuanweeei does the issue resolve by MKLDNN upgrade PR?

This issue exists in the upgrade PR. It will give an error message when uses `add`.

**Comment by pengzhao-intel** [comment] 2019-11-01 01:39
OK, is there a workaround for the user and what's the plan for the next step?

**Comment by zixuanweeei** [comment] 2019-11-01 01:51
> OK, is there a workaround for the user and what's the plan for the next step?

It will be appreciated that users could report their usage with `add`. But we couldn't force everyone to do this. So I will put it on the list. I plan to fix it in one week.

**Comment by TaoLv** [comment] 2020-01-02 05:30
Should be fixed via #17075. Feel free to re-open if the problem is still there.  @zixuanweeei

**Closed by TaoLv** 2020-01-02 05:30 UTC
Labels: Feature request, MKLDNN
