### ISSUE TITLE
docker/tool.sh can't fix the "Failed to initialize libdc1394"

### ISSUE THREAD

**Issue by ahriy** [apache/incubator-mxnet#8091] opened 2017-09-29 03:49 UTC
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Ubuntu 16.04

Compiler:

Package used (Python/R/Scala/Julia):
Python

MXNet version: 
0.11

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
python 2.7

## Error Message:
Please paste the full error message, including stack trace.
libdc1394 error: Failed to initialize libdc1394

## Minimum reproducible example
follow the [official guide](https://mxnet.incubator.apache.org/get_started/install.html)

## Steps to reproduce
1. run `./tool.sh build python cpu`
2. docker run -it mxnet/python bash
3. python
4. import mxnet as mx
## What have you tried to solve it?
use ln -s /dev/null /dev/raw1394
however, I must do this manually，the [Dockerfile](https://github.com/apache/incubator-mxnet/blob/198df2fb83ba282999ba1253a986458217d0bef7/docker/tool.sh#L85) try to use `CMD ln -s /dev/null /dev/raw1394`  to solve the problem, but actually it doesn't work. The link file /dev/raw1394 will not in the /dev/ directory when I boot the docker image. 
I'am trying to deploy mxnet in k8s, and this error makes the deployment failed since k8s will check the container's status.

**Comment by eric-haibin-lin** [comment] 2017-09-29 04:04
I see that error message in CI sometimes. Are you sure this is the reason the deployment failed?

**Comment by szha** [comment] 2017-09-29 04:36
1394 error is usually a false issue that's caused by importing an opencv that was built with 1394 I/O, and it doesn't cause real harm.

**Comment by zhreshold** [comment] 2017-09-29 19:04
You can ignore this error, it's a completely nonsense opencv error.

**Comment by vrakesh** [comment] 2018-11-27 00:34
@ahriy Requesting to close the issue, if it is no longer a problem

**Comment by vrakesh** [comment] 2018-11-27 00:34
@mxnet-label-bot add [Pending Requester Info]

**Comment by kalyc** [comment] 2018-12-10 23:50
@lanking520 requesting to close due to lack of activity

**Comment by lanking520** [comment] 2018-12-11 05:07
Close it for now. Please feel free to reopen it if you are still facing the issue.

**Closed by lanking520** 2018-12-11 05:07 UTC
Labels: Installation, Pending Requester Info
