### ISSUE TITLE
data layer grad problem

### ISSUE THREAD

**Issue by songziqin** [apache/incubator-mxnet#14152] opened 2019-02-14 00:58 UTC
the C++ code as follows:
 args_["data"] = NDArray(Shape(params.batch_size, params.dim), ctx);
 network_.InferArgsMap(ctx, &args_, args_);
 exec_.reset(network_.SimpleBind(ctx, args_));

I find the exec_.get()->grad_dict() get the data layer grad is all 0.
and I want to know through the code above, can I  get the actual 
the data layer grad. thanks.

**Comment by lanking520** [comment] 2019-02-14 20:09
Hi @songziqin Thanks for filing this issue. You can join our Slack channel and ask there with a faster response: http://mxnet.incubator.apache.org/versions/master/community/contribute.html#slack

@leleamol

**Comment by leleamol** [comment] 2019-02-15 20:03
@songziqin 

Can you please provide a mimim reproducible example?  It isn't clear what are the expectations.

@mxnet-label-bot add [Pending Requester Info]

**Comment by leleamol** [comment] 2019-06-04 23:54
@songziqin please let us know if you got the answer on forum. It would also help us more in resolving the issue, if there is a reprodicible example

**Comment by lanking520** [comment] 2019-06-05 20:24
@songziqin Close this issue due to inactivity. Please feel free to reopen if you are still facing the same problems.

**Closed by lanking520** 2019-06-05 20:24 UTC
Labels: C++, Pending Requester Info, Question
