### ISSUE TITLE
Unnecessary requirement

### ISSUE THREAD

**Issue by yx3zhang** [apache/incubator-mxnet#13982] opened 2019-01-24 20:16 UTC
https://github.com/apache/incubator-mxnet/blob/4c88f3049695b9c751a6d1a228853f18b2733358/scala-package/core/src/main/scala/org/apache/mxnet/IO.scala#L376

Hi, I believe this line is unnecessary and it is currently messing some of my code from 1.1 up when upgrading to 1.3

**Comment by yx3zhang** [comment] 2019-01-24 20:17
A warning should suffice for this.

**Comment by ChaiBapchya** [comment] 2019-01-24 21:33
Thanks for pointing out. Curious to know why is this unnecessary? What error are you getting in 1.1? The reason why it must be in `require` is If it is needed for some computation (I'm guessing).

**Comment by ChaiBapchya** [comment] 2019-01-24 21:34
@mxnet-label-bot add [Scala]

**Comment by yx3zhang** [comment] 2019-01-24 21:42
I essentially have similar setup as sockeye but in Scala. I train model in Sockeye then migrate to Scala's RNN classes I wrote, but I borrowed some code from Sockeye. 

Specifically this line where layout = "NT" but batchsize * beamsize will be a 1 by N.

https://github.com/awslabs/sockeye/blob/a5fe6d6d672f590b4de517b61eff6f51ca97de76/sockeye/inference.py#L275

**Comment by lanking520** [comment] 2019-01-24 22:05
@yx3zhang Thanks for reporting this issue. This requirement method introduced in 1.2 and improved in 1.3. We plan to make the layout as a requried field for DataDesc. Due to the backward compatibility, we add a `undefined` placeholder here. Please feel free to pass the `UNDEFINED` if you don't want this be in the model. Please let me know if you are facing more issues like that and bring some code here that can reproduce your issue. I will take a look and see how I can help

**Comment by yx3zhang** [comment] 2019-01-24 22:13
The same check is not in the Python io.py I believe even in 1.3, why having it in Scala?

**Comment by lanking520** [comment] 2019-01-28 20:20
> The same check is not in the Python io.py I believe even in 1.3, why having it in Scala?
It is used for the Predictor API and it contains more concrete data possible. Please let me know if you would like to make it better.

**Comment by piyushghai** [comment] 2019-02-08 18:04
@yx3zhang Did the above replies help with your query ? If yes, please feel free to close this issue. 
You can re-open if closed in error.

**Comment by yx3zhang** [comment] 2019-02-08 23:05
I worked around by passing in layout.undefined. I still feel it would be better if consistent but for now it'll work.

**Comment by lanking520** [comment] 2019-02-13 18:13
@yx3zhang Thanks for your reply. Close this issue for now. Please feel free to reopen this if you find a better solution to that or you are blocked by this one more time.

**Closed by lanking520** 2019-02-13 18:13 UTC
Labels: Question, Scala
