### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by rehmanzafar** [apache/incubator-mxnet#11007] opened 2018-05-20 18:09 UTC
Hello,

I have installed the mxnet using the following command "**pip install mxnet==1.1.0**". The package was successfully installed but it is giving an error on import "**ModuleNotFoundError: No module named '_bz2'**" I have tried various solutions but no luck.

`import mxnet as mx` 
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/mxnet/__init__.py", line 77, in <module>
    from . import test_utils
  File "/usr/local/lib/python3.6/site-packages/mxnet/test_utils.py", line 31, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 23, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

Any help would be appreciated !!
Thank you.

**Comment by ankkhedia** [comment] 2018-05-21 05:09
@rehmanzafar Could you please give more details about the environment in which you were using?
@sandeep-krishnamurthy Could you please tag this as Installation and Pending requester info

**Comment by rehmanzafar** [comment] 2018-05-21 08:26
@ankkhedia I am facing this issue in ubuntu 16.04.

**Comment by sandeep-krishnamurthy** [comment] 2018-05-23 17:04
@rehmanzafar I tried on Ubuntu 16.04, I am unable to reproduce your error. Can you please try clean install again? i.e., uninstall and re-install?

```
pip uninstall mxnet
pip install mxnet==1.1.0
```

Here is my output:
```
$ pip install mxnet==1.1.0
Collecting mxnet==1.1.0
  Downloading https://files.pythonhosted.org/packages/9a/4b/8fe47d8f044c78d5adfdfceffb664bdeca13bee2bf8ec7799ebf4d831c23/mxnet-1.1.0-py2.py3-none-manylinux1_x86_64.whl (23.7MB)
    100% |████████████████████████████████| 23.8MB 58kB/s 
Collecting graphviz==0.8.1 (from mxnet==1.1.0)
  Downloading https://files.pythonhosted.org/packages/82/cc/668725769a1b184322019b494bbdfbb82bbef5cecc1dd8be6f778cf1422b/graphviz-0.8.1-py2.py3-none-any.whl
Collecting requests==2.18.4 (from mxnet==1.1.0)
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 11.3MB/s 
Collecting numpy<=1.13.3 (from mxnet==1.1.0)
  Downloading https://files.pythonhosted.org/packages/eb/be/737f3df5806192ac4096e549e48c8c76cfaa2fb880a1c62a7bb085adaa9b/numpy-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl (16.6MB)
    100% |████████████████████████████████| 16.7MB 84kB/s 
Collecting certifi>=2017.4.17 (from requests==2.18.4->mxnet==1.1.0)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 8.3MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->mxnet==1.1.0)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 9.3MB/s 
Collecting idna<2.7,>=2.5 (from requests==2.18.4->mxnet==1.1.0)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 11.4MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->mxnet==1.1.0)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 9.0MB/s 
Installing collected packages: graphviz, certifi, chardet, idna, urllib3, requests, numpy, mxnet
Successfully installed certifi chardet graphviz idna mxnet numpy requests urllib3

$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
>>> exit()

```

**Comment by piyushghai** [comment] 2018-10-09 18:58
@sandeep-krishnamurthy Requesting this issue to be closed as this issue is older than 120 days and also we have not been able to reproduce the issue. 
@rehmanzafar We now have MXNet 1.3.0 as the latest and greatest version of MXNet. Do try it out and let us know if you still face this issue. 
Please feel free to reopen this issue if closed in error. 
Thanks.

**Closed** 2018-10-09 19:32 UTC
Labels: Installation, Pending Requester Info
