### ISSUE TITLE
MxNet allow to use same name

### ISSUE THREAD

**Issue by Caenorst** [apache/incubator-mxnet#9890] opened 2018-02-26 19:35 UTC
## Description
MxNet allow me to reuse a name of a symbol without returning an error, it eventually leads to a cyclic graph in the visualization.

It should prevent the user to be able to reuse the same name unless the user want specifically to reuse the same variable (with an argument), instead of advising them to not reuse the same name (#2036)

## Environment info (Required)
on Intel Core i7-5820K
with `pip install mxnet`

## Error Message:
There is no error message, and that's the problem.

## Minimum reproducible example
```import mxnet as mx
a=mx.sym.Variable('u')
b=mx.sym.relu(a,'v')
c=mx.sym.log(b,'u')
mx.viz.plot_network(c)

in1 = mx.nd.random.uniform(0.001,5,shape=[2,2])
ex = c.bind(ctx=mx.cpu(), args={'u' : in1})
print ex.forward()
print ex.output_dict
print ex.arg_dict
print in1
```
return a cyclic graph (u => v => u) and:
```[
[[-2.28207898  0.61076486]
 [ 1.42630005  1.56565714]]
<NDArray 2x2 @cpu(0)>]
{'u_output': 
[[-2.28207898  0.61076486]
 [ 1.42630005  1.56565714]]
<NDArray 2x2 @cpu(0)>}
{'u': 
[[ 0.10207178  1.84183955]
 [ 4.16326666  4.78581858]]
<NDArray 2x2 @cpu(0)>}

[[ 0.10207178  1.84183955]
 [ 4.16326666  4.78581858]]
<NDArray 2x2 @cpu(0)>
```

Which shows that `u` is BOTH the input variable and the `log` function.

**Comment by roywei** [comment] 2018-04-06 00:19
Hi @Caenorst 
I think this is not a bug, users may want to create two variables with same name and use in different graphs as mentioned in your [reference issue](https://github.com/apache/incubator-mxnet/issues/2036). We should allow to use same name

This your case, the output seems correct, if modify your code to not use the same name:
`c=mx.sym.log(b,'x')`
it will print the same output as your code snippet. 
The only difference is the cycle in graph visualization, which dictates user has used repeated name. I added this [PR](https://github.com/apache/incubator-mxnet/pull/10429) to prevent confusion

**Comment by roywei** [comment] 2018-07-02 21:19
#10429 should fix this.
@sandeep-krishnamurthy  could you help to close this issue?
Thanks

**Closed** 2018-07-02 22:36 UTC
Labels: Bug, Symbol
