### ISSUE TITLE
C++ Convolution layer usage produces "Segmentation fault"

### ISSUE THREAD

**Issue by Ishitori** [apache/incubator-mxnet#9814] opened 2018-02-16 22:32 UTC
## Description
Compiled version 1.1.0 C++ package with `make -j USE_OPENCV=0 USE_CPP_PACKAGE=1` on Mac and trying to run LeNet example. Fails with Segmentation fault exeception

### Package used (Python/R/Scala/Julia):
C++ package

### Compiler
g++
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix

### MXNet commit hash:
Version 1.1.0 - 07a83a0325a3d782513a04f47d711710972cb144

### Build config:
Taken by default from sources of that hash

## Error Message:
No stack trace returned. Here is what I see on terminal:
```
[1]    77873 segmentation fault  ./main 
```

## Minimum reproducible example
```
#include "mxnet-cpp/MxNetCpp.h"
using namespace mxnet::cpp;

int main(int argc, char const *argv[]) {
  Symbol data = Symbol::Variable("data");
  Symbol conv1_w("conv1_w"), conv1_b("conv1_b");
  Symbol conv1 = Convolution("conv1", data, conv1_w, conv1_b, Shape(5, 5), 20);
  return 0;
```
## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Compile with all libraries 
2. Run sample code

## What have you tried to solve it?

1. I looked at [dmlc](https://github.com/dmlc/MXNet.cpp/commit/b54ba371784b48f652930ff3210ff98a9ae12eb6) who were fixing similar problem, but adding `MXNotifyShutdown();` didn't help

**Comment by Mabinogiysk** [comment] 2018-03-07 06:07
Hi, could you tell me where to find the tutorials about building C++ package?

**Comment by ThomasDelteil** [comment] 2018-03-22 21:04
@Mabinogiysk https://mxnet.incubator.apache.org/install/build_from_source#build-the-c-package

I would like to add to this issue, that actually for me, strictly none of the cpp example ran without segfaulting or crashing

**Comment by spidyDev** [comment] 2018-04-23 20:30
I wasnt able to replicate the issue with the minimum reproducible example stated above.

But with ./alexnet I am hitting this error:
Process 92985 launched: './alexnet' (x86_64)
libc++abi.dylib: terminating with uncaught exception of type dmlc::Error: [13:28:39] ../include/mxnet-cpp/ndarray.hpp:54: Check failed: MXNDArrayCreate(shape.data(), shape.size(), context.GetDeviceType(), context.GetDeviceId(), delay_alloc, &handle) == 0 (-1 vs. 0)

**Comment by vishaalkapoor** [comment] 2018-08-30 22:16
@marcoabreu spidyDev's PR has been merged. If this PR addresses all segfaults, can we close this off? Thanks!

**Comment by KellenSunderland** [comment] 2018-09-10 12:45
I'm having the same issues as above with version 1.3.

**Comment by marcoabreu** [comment] 2018-09-10 12:47
As far as we can see, it's still broken on CPU. We should add tests for this before we can close the issue.

**Comment by KellenSunderland** [comment] 2018-09-10 14:04
Sorry it's not well documented but you have to make sure that data is downloaded to the correct folder.  Try changing to the example folder and running the get_data.sh script.

**Comment by leleamol** [comment] 2018-11-01 19:14
@Ishitori @KellenSunderland 

I have recently submitted changes to [ReadMe file in cpp-package](https://github.com/apache/incubator-mxnet/tree/master/cpp-package) and [ReadMe file in cpp-package/example](https://github.com/apache/incubator-mxnet/tree/master/cpp-package/example) that explains how to build cpp-package and run examples.

@Ishitori , since you were trying to run one of the training examples, will you be able to share the use case that you were planning to address using C++ APIs?

**Comment by leleamol** [comment] 2018-11-09 19:05
@mxnet-label-bot add [Pending Requester Info]

**Comment by Ishitori** [comment] 2018-11-09 19:37
@leleamol, I was just reproducing an error from the forum. I am not sure I can find original message anymore though...

**Comment by vrakesh** [comment] 2018-11-27 20:53
@Ishitori Are you still facing this issue? Were you able to follow the documentation above, to have it working consistently? Requesting an update

**Comment by kalyc** [comment] 2018-12-10 23:51
@lanking520 requesting to close due to lack of activity

**Comment by lanking520** [comment] 2018-12-11 04:32
@Ishitori Please feel free to reopen it if you are still facing the problem. Close it for now.

**Closed by lanking520** 2018-12-11 04:32 UTC
Labels: Bug, C++, Example, Pending Requester Info
