### ISSUE TITLE
Issue in exporting gluon model

### ISSUE THREAD

**Issue by BenLag2906** [apache/incubator-mxnet#11944] opened 2018-07-31 09:44 UTC
Hi

I train a CNN with python under mxnet gluon, when i try to use my model exported with command :
"net.export('model', epoch=1) ", mys C++ code crash when i call MXPredsetInput.
My c++ code  works with a SSD model trained on another github.

I am under Windows.

Diag :
----------Python Info----------
('Version      :', '2.7.0')
('Compiler     :', 'MSC v.1500 64 bit (AMD64)')
('Build        :', ('r27:82525', 'Jul  4 2010 07:43:08'))
('Arch         :', ('64bit', 'WindowsPE'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', 'C:\\python27\\lib\\site-packages\\pip')
----------MXNet Info-----------
C:\python27\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
('Version      :', '1.2.0')
('Directory    :', 'C:\\python27\\lib\\site-packages\\mxnet')
Hashtag not found. Not installed from pre-built package.
----------System Info----------
('Platform     :', 'Windows-post2008Server-6.2.9200')
('system       :', 'Windows')
('node         :', 'BEWORK009')
('release      :', 'post2008Server')
('version      :', '6.2.9200')
----------Hardware Info----------
('machine      :', 'AMD64')
('processor    :', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
Name
Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

----------Network Test----------
Setting timeout: 10
Error open MXNet: https://github.com/apache/incubator-mxnet, <urlopen error [Errno 1] _ssl.c:499: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>, DNS finished in 0.101999998093 sec.
Error open PYPI: https://pypi.python.org/pypi/pip, <urlopen error [Errno 1] _ssl.c:499: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>, DNS finished in 0.055999994278 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0690 sec, LOAD: 1.1940 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0590 sec, LOAD: 0.5300 sec.
Error open Gluon Tutorial(en): http://gluon.mxnet.io, <urlopen error [Errno 1] _ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>, DNS finished in 0.0729999542236 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [Errno 1] _ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>, DNS finished in 0.226999998093 sec.

My Compiler is Visual studio:

1. We check size of input data, name of input model ( 1st layer)

I join you the model exported json file.

[export_test.zip](https://github.com/apache/incubator-mxnet/files/2244714/export_test.zip)

Could you please give a piece of advise ?

**Comment by Roshrini** [comment] 2018-07-31 18:48
@sandeep-krishnamurthy Can you take a look and could you please add labels- Gluon, Bug

**Comment by zhreshold** [comment] 2018-08-02 22:42
@BenLag2906 Can you post the C++ crash back trace? So I assume you are having problem running c++ inference, not gluon export right?

**Comment by BenLag2906** [comment] 2018-08-03 07:43
Hi,
Not sure because as I said other model like ssd run with this c++ code.
I give you my trace. Maybe a model gluon exported is not compatible with my mxnet if i refered to the stack trace.

**Comment by BenLag2906** [comment] 2018-08-03 07:44
[esi.av1.engine_1.0.0_mvsrexyh-996274368.zip](https://github.com/apache/incubator-mxnet/files/2256484/esi.av1.engine_1.0.0_mvsrexyh-996274368.zip)
![mxnet](https://user-images.githubusercontent.com/26578899/43630861-cbd9f424-9701-11e8-8e62-767825d22af7.jpg)

**Comment by zhreshold** [comment] 2018-08-03 20:03
The logs are not readable. 
Basically if you are using the same mxnet for gluon and c++ inference, it should be fine.
If you can post the json file exported by gluon, I can have a look.

**Comment by BenLag2906** [comment] 2018-08-04 13:53
Hi,
The json was in my zip file, in first post.
I try two version of mxnet without succes..

**Comment by zhreshold** [comment] 2018-08-06 18:49
@BenLag2906 

Here are the operators I found in your JSON file:

```
  23       "op": "Activation", 
   7       "op": "Concat", 
  35       "op": "Convolution", 
  12       "op": "Flatten", 
   1       "op": "L2Normalization", 
   5       "op": "Pooling", 
  21       "op": "Reshape", 
   2       "op": "SliceChannel", 
   1       "op": "_contrib_box_nms", 
   2       "op": "_div_scalar", 
   1       "op": "_greater_scalar", 
  11       "op": "_mul_scalar", 
   5       "op": "_plus_scalar", 
   2       "op": "broadcast_add", 
   6       "op": "broadcast_mul", 
   2       "op": "elemwise_add", 
   2       "op": "elemwise_sub", 
   2       "op": "exp", 
  79       "op": "null", 
   1       "op": "ones_like", 
   8       "op": "slice_axis", 
   6       "op": "slice_like", 
   1       "op": "softmax", 
  12       "op": "transpose", 
   2       "op": "where", 
   2       "op": "zeros_like", 
```

The latest one is slice_like operator added 4 months ago. So using mxnet 1.3 can ensure all these operators are supported.

**Comment by piyushghai** [comment] 2018-10-09 17:52
@BenLag2906 Did upgrading to MXNet 1.3 help in resolving the issue ?

**Comment by leleamol** [comment] 2018-10-30 22:43
@mxnet-label-bot [pending-requester-info]

**Comment by vdantu** [comment] 2019-01-31 22:19
@BenLag2906 : Just checking in to see if simply upgrading the MXNet version helped solve the issue. 

Also, if you are still seeing this issue, could you share a minimum reproducible code, which we can compile on our end and reproduce this issue?

**Comment by lanking520** [comment] 2019-02-11 19:10
@BenLag2906 Close it for now due to no response, Please feel free to reopen if problem persist.

**Closed by lanking520** 2019-02-11 19:10 UTC
Labels: C++, Pending Requester Info
