### ISSUE TITLE
mkl support problem, please solve it

### ISSUE THREAD

**Issue by vincentJCE** [apache/incubator-mxnet#14381] opened 2019-03-10 03:30 UTC
It seems mxnet has mkl support problem.
nvidia-docker pull mxnet-python: 1.4.0_gpu_cu100_mkl_py3.
It runs with mkldnn problem.
On the other hand, nvidia-docker pull mxnet-python: 1.4.0_gpu_cu100_py3, the verstion without mkl, the image itself is not correctly compiled. It says gpu support is disabled.

**Comment by pengzhao-intel** [comment] 2019-03-10 06:29
@vincentJCE, could you provide the step to reproduce the issue and paste the error log?

@mxnet-label-bot add [build, MKLDNN]

**Comment by pengzhao-intel** [comment] 2019-08-04 04:21
closing since no reproducible case till now.
Feel free to reopen :)

**Closed by pengzhao-intel** 2019-08-04 04:21 UTC
Labels: Build, MKLDNN
