### ISSUE TITLE
Problems of bucking iterator in speech example

### ISSUE THREAD

**Issue by AprilSongRits** [apache/incubator-mxnet#11743] opened 2018-07-13 10:42 UTC
The bucking iterator cannot read all the training data, which will cause the evaluation being significantly different.

**Comment by apeforest** [comment] 2018-07-13 16:12
@AprilSongRits Can you give more details of this problem. Like a reproducible simple example will be great. Thanks!

**Comment by ankkhedia** [comment] 2018-11-01 17:42
@sandeep-krishnamurthy @nswamy @anirudh2290 Could you please close the issue due to lack of activity.

@AprilSongRits Please feel free to re-open the issue in case closed in error.

**Comment by kalyc** [comment] 2018-11-15 22:33
@mxnet-label-bot add [suggest-closed]

**Comment by cjolivier01** [comment] 2018-11-15 22:53
closing until requester reopens

**Closed by cjolivier01** 2018-11-15 22:53 UTC
Labels: Data-loading, Pending Requester Info, suggest-closed
