### ISSUE TITLE
test_module.test_factorization_machine_module has fixed seed that can mask flakiness

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#11704] opened 2018-07-13 05:25 UTC
The unit test in title have been using fixed seed to mask flakiness. Suggested action:
1. Evaluate whether the test is flaky without fixed seed. If not, remove seed. Else move to 2
2. If test is flaky, determine whether it's an actual uncaught edge case. If so, fix the operator. Else move to 3
3. If numerical instability is inevitable, adjust tolerance level appropriately.

**Comment by apeforest** [comment] 2018-07-13 20:48
Thanks for filing this issue. We will investigate this Flaky test

**Comment by apeforest** [comment] 2018-07-31 19:57
I could reproduce the issue using random seed 1306649843.  The issue is accuracy mismatch

**Comment by apeforest** [comment] 2018-08-01 16:01
Assigned JIRA ticket: https://issues.apache.org/jira/browse/MXNET-770

**Comment by apeforest** [comment] 2018-08-03 16:37
Fixed unit test and added training test. PR: https://github.com/apache/incubator-mxnet/pull/12023

**Comment by apeforest** [comment] 2018-08-04 03:25
@szha PR is merged. Please verify and close this issue. Thanks!

**Comment by haojin2** [comment] 2018-08-16 00:29
@sandeep-krishnamurthy Related PR is merged, should be good to close.

**Closed** 2018-08-16 04:25 UTC
Labels: Flaky, Test
