### ISSUE TITLE
when import mxnet using python3.5 the error occurred with the newest version 0.9.5

### ISSUE THREAD

**Issue by Trangle** [apache/incubator-mxnet#5848] opened 2017-04-15 11:48 UTC
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
windows 10 x64

Compiler:
visual c++ 12.0

Package used (Python/R/Scala/Julia):
python3.5

MXNet version:
0.9.5

Or if installed from source:
0.9.5

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
In [1]: import mxnet
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-1-30eb4f951ea5> in <module>()
----> 1 import mxnet

C:\Users\kw_w\Documents\My3rdPartyLib\MxNet\python\mxnet\__init__.py in <module>()
      7 from .base import MXNetError
      8 from . import base
----> 9 from . import contrib
     10 from . import ndarray
     11 from . import name

C:\Users\kw_w\Documents\My3rdPartyLib\MxNet\python\mxnet\contrib\__init__.py in <module>()
      8 from . import ndarray as nd
      9
---> 10 from . import autograd
     11 from . import tensorboard

C:\Users\kw_w\Documents\My3rdPartyLib\MxNet\python\mxnet\contrib\autograd.py in <module>()
      8 from ..base import _LIB, check_call, string_types
      9 from ..base import mx_uint, NDArrayHandle, c_array
---> 10 from ..ndarray import NDArray, zeros_like
     11 from ..symbol import _GRAD_REQ_MAP
     12

C:\Users\kw_w\Documents\My3rdPartyLib\MxNet\python\mxnet\ndarray.py in <module>()
    873         return self.copyto(context)
    874
--> 875 _init_ndarray_module(NDArray, "mxnet")
    876
    877 def onehot_encode(indices, out):

C:\Users\kw_w\Documents\My3rdPartyLib\MxNet\python\mxnet\_ctypes\ndarray.py in _init_ndarray_module(ndarray_class, root_namespace)
    202         hdl = OpHandle()
    203         check_call(_LIB.NNGetOpHandle(c_str(name), ctypes.byref(hdl)))
--> 204         function = _make_ndarray_function(hdl, name)
    205         if function.__name__.startswith('_contrib_'):
    206             function.__name__ = function.__name__[9:]

C:\Users\kw_w\Documents\My3rdPartyLib\MxNet\python\mxnet\_ctypes\ndarray.py in _make_ndarray_function(handle, name)
     67     ret_type = py_str(ret_type.value) if ret_type.value is not None else ''
     68     doc_str = _build_doc(func_name,
---> 69                          py_str(desc.value),
     70                          arg_names,
     71                          arg_types,

C:\Users\kw_w\Documents\My3rdPartyLib\MxNet\python\mxnet\base.py in <lambda>(x)
     22     # this function is needed for python3
     23     # to convert ctypes.char_p .value back to python str
---> 24     py_str = lambda x: x.decode('utf-8')
     25 else:
     26     string_types = basestring,

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 55-56: invalid continuation byte

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by piiswrong** [comment] 2017-04-17 05:44
@yajiedesign 
Looks like unicode problem with windows. Can you reproduce?

**Comment by yajiedesign** [comment] 2017-04-17 06:45
should be some a describe use error encoding,i try to reproduce

**Comment by horsepurve** [comment] 2017-04-20 02:08
same problem installing the newest version

**Comment by horsepurve** [comment] 2017-04-20 04:53
I guess this is the cause:

this commit:
  Fix docs for some NDArray functions (#5808)
  Roshrini committed with mli 5 days ago

in this file:
mxnet\src\operator\tensor\broadcast_reduce_op_index.cc

there are many "LSLSLS" at the ends of lines when viewed on windoes

**Comment by Trangle** [comment] 2017-04-22 16:17
solved by revise the file broadcast_reduce_op_index.cc

**Comment by szha** [comment] 2017-09-29 22:36
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Closed by szha** 2017-09-29 22:36 UTC
