### ISSUE TITLE
Quantization int8 bit performance drop too much

### ISSUE THREAD

**Issue by lxpwj** [apache/incubator-mxnet#15701] opened 2019-07-30 08:37 UTC
I am following the (https://github.com/apache/incubator-mxnet/tree/master/example/quantization )

my Mxnet version is 1.5.0

the action i have done is 
python imagenet_gen_qsym_mkldnn.py --model=imagenet1k-resnet-152 --num-calib-batches=5 --calib-mode=entropy

python imagenet_inference.py --symbol-file=./model/imagenet1k-resnet-152-quantized-5batches-entropy-symbol.json --param-file=./model/imagenet1k-resnet-152-quantized-0000.params --num-skipped-batches=50 --batch-size=64 --num-inference-batches=500 --dataset=./data/val_256_q90.rec --ctx=cpu

however, **my top1 is 0.7256 and top5 is 0.9108**

which is quite different from your official result at (https://cwiki.apache.org/confluence/display/MXNET/MXNet+Graph+Optimization+and+Quantization+based+on+subgraph+and+MKL-DNN)

can you please suggest?

**Comment by vrakesh** [comment] 2019-07-30 20:11
@lxpwj Thans for posting this , issue we will look into this

@mxnet-label-bot  add [Performance]

**Comment by ZhennanQin** [comment] 2019-07-31 00:19
@lxpwj Thanks for reporting this. May I know your CPU type first? Because different generation will provide slight different accuracy due to different instructions used. 

Cwiki results are collected based on proposal which targeting MXNet v1.4 release, and it is not the same situation as v1.5. v1.5 added more quantized operators, which will help to accelerate the quantized model, and on the other hand, the accuracy may slightly drop. To reproduce the accuracy from proposal, you need to exclude all non-fused `relu` and `add` operator.

Also, imagenet1k-resnet-152 isn't a good candidate for quantization because resnet_v2 changed the operator order in base block, causing operator can't be fully fused, and result in frequent type conversion between fp32 and int8. Those conversions will eat up all benefit from quantization, but provide bad accuracy.

Please try `resnet50_v1`, `inceptionv3` or `mobilenetv2_1.0`, they are more friendly and will get good result on both accuracy and speed.

**Comment by lxpwj** [comment] 2019-07-31 01:10
@ZhennanQin Thank you for prompt update
here is my PC info
![image](https://user-images.githubusercontent.com/5241532/62176070-b1138180-b372-11e9-954d-bcb77dc5545a.png)

i will try resnet50_v1, inceptionv3 or mobilenetv2_1.0 at V1.5.0 firstly and update you the results.
Basically, i wan to make sure entropy loss threshold has higher performance than min/max threshold.

**Comment by lxpwj** [comment] 2019-07-31 07:23
some other models on Mx1.5.0

my observation:
1. mobilenetv2 and inceptionv3, the int8 model has desired performance. for inception v3, int8 is even better than floating version.  
1. entropy loss doesnot always perform better than min/max, for example, inceptionv3 and resnet-152.

below are my test scripts and results

python imagenet_gen_qsym_mkldnn.py --model=mobilenetv2_1.0 --num-calib-batches=5 --calib-mode=naïve

python imagenet_inference.py --symbol-file=./model/mobilenetv2_1.0-symbol.json --param-file=./model/mobilenetv2_1.0-0000.params --rgb-mean=123.68,116.779,103.939 --rgb-std=58.393,57.12,57.375 --num-skipped-batches=50 --batch-size=64 --num-inference-batches=500 --dataset=./data/val_256_q90.rec --ctx=cpu

 
![image](https://user-images.githubusercontent.com/5241532/62190742-ae318480-b3a4-11e9-9a23-dd38f4e632ce.png)


python imagenet_inference.py --symbol-file=./model/mobilenetv2_1.0-quantized-5batches-naive-symbol.json --param-file=./model/mobilenetv2_1.0-quantized-0000.params --rgb-mean=123.68,116.779,103.939 --rgb-std=58.393,57.12,57.375 --num-skipped-batches=50 --batch-size=64 --num-inference-batches=500 --dataset=./data/val_256_q90.rec --ctx=cpu

 
![image](https://user-images.githubusercontent.com/5241532/62190778-c1445480-b3a4-11e9-858a-05cf9a84172f.png)


python imagenet_gen_qsym_mkldnn.py --model=mobilenetv2_1.0 --num-calib-batches=5 --calib-mode=entropy

python imagenet_inference.py --symbol-file=./model/mobilenetv2_1.0-quantized-5batches-entropy-symbol.json --param-file=./model/mobilenetv2_1.0-quantized-0000.params --rgb-mean=123.68,116.779,103.939 --rgb-std=58.393,57.12,57.375 --num-skipped-batches=50 --batch-size=64 --num-inference-batches=500 --dataset=./data/val_256_q90.rec --ctx=cpu

 
![image](https://user-images.githubusercontent.com/5241532/62190795-cb665300-b3a4-11e9-8658-1bf704a9b431.png)



python imagenet_gen_qsym_mkldnn.py --model=inceptionv3 --image-shape=3,299,299 --num-calib-batches=5 --calib-mode=naive


python imagenet_inference.py --symbol-file=./model/inceptionv3-symbol.json --param-file=./model/inceptionv3-0000.params --image-shape=3,299,299 --rgb-mean=123.68,116.779,103.939 --rgb-std=58.393,57.12,57.375 --num-skipped-batches=50 --batch-size=64 --num-inference-batches=500 --dataset=./data/val_256_q90.rec --ctx=cpu

 
![image](https://user-images.githubusercontent.com/5241532/62190820-d7521500-b3a4-11e9-98df-106d7985771f.png)


python imagenet_inference.py --symbol-file=./model/inceptionv3-quantized-5batches-naive-symbol.json --param-file=./model/inceptionv3-quantized-0000.params --image-shape=3,299,299 --rgb-mean=123.68,116.779,103.939 --rgb-std=58.393,57.12,57.375 --num-skipped-batches=50 --batch-size=64 --num-inference-batches=500 --dataset=./data/val_256_q90.rec --ctx=cpu

 
![image](https://user-images.githubusercontent.com/5241532/62190830-de792300-b3a4-11e9-97a8-53354a9c1726.png)


python imagenet_gen_qsym_mkldnn.py --model=inceptionv3 --image-shape=3,299,299 --num-calib-batches=5 --calib-mode=entropy

python imagenet_inference.py --symbol-file=./model/inceptionv3-quantized-5batches-entropy-symbol.json --param-file=./model/inceptionv3-quantized-0000.params --image-shape=3,299,299 --rgb-mean=123.68,116.779,103.939 --rgb-std=58.393,57.12,57.375 --num-skipped-batches=50 --batch-size=64 --num-inference-batches=500 --dataset=./data/val_256_q90.rec --ctx=cpu

![image](https://user-images.githubusercontent.com/5241532/62190838-e46f0400-b3a4-11e9-8695-2261ce5ea7d1.png)

**Comment by ZhennanQin** [comment] 2019-07-31 07:41
@lxpwj Thanks for providing the detailed result. I7-4790k only supports AVX2, while not for AVX-512. So the speed up from quantization may not as outstanding as Cascade Lake CPU. 

The accuracy looks good to me. We also observed that entropy isn't always better than naive min/max. It depends on topology and calibration dataset.

**Comment by ZhennanQin** [comment] 2019-07-31 07:47
Worth to mention is, for best accuracy after quantization, it's better to adopt Cascade Lake CPU because newly added VNNI instructions can avoid overflow in int8 convolution, thus the accuracy will be sightly better for most topology, especially for entropy loss, because entropy loss will produce more large data and cause more accumulating overflow for some topologies.

**Comment by lxpwj** [comment] 2019-07-31 07:56
thanks for sharing.

**Comment by pengzhao-intel** [comment] 2019-08-02 15:59
@lxpwj thanks for using quantization flow. you can refer our blog for more info
https://medium.com/apache-mxnet/model-quantization-for-production-level-neural-network-inference-f54462ebba05

**Comment by pengzhao-intel** [comment] 2019-08-03 23:59
Closing this issue and feel free to reopen if there's still an issue.

**Closed by pengzhao-intel** 2019-08-03 23:59 UTC
Labels: MKLDNN, Performance
