### ISSUE TITLE
`mxnet.gpu()` Caused Segmentfault

### ISSUE THREAD

**Issue by NKUCodingCat** [apache/incubator-mxnet#10309] opened 2018-03-29 03:56 UTC
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description

`mxnet.gpu()` Caused Segmentfault

## Environment info (Required)

```
----------Python Info----------
('Version      :', '2.7.5')
('Compiler     :', 'GCC 4.8.5 20150623 (Red Hat 4.8.5-16)')
('Build        :', ('default', 'Aug  4 2017 00:39:18'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '8.1.2')
('Directory    :', '/usr/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
('Version      :', '1.2.0')
('Directory    :', '/usr/lib/python2.7/site-packages/mxnet')
Hashtag not found. Not installed from pre-built package.
----------System Info----------
('Platform     :', 'Linux-3.10.0-327.el7.x86_64-x86_64-with-centos-7.2.1511-Core')
('system       :', 'Linux')
('node         :', 'gpu1')
('release      :', '3.10.0-327.el7.x86_64')
('version      :', '#1 SMP Thu Nov 19 22:10:57 UTC 2015')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               1200.281
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4199.95
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7
NUMA node1 CPU(s):     8-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0017 sec, LOAD: 1.0746 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0490 sec, LOAD: 0.2714 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.7199 sec, LOAD: 2.6862 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0012 sec, LOAD: 0.2026 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.3731 sec, LOAD: 1.2455 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.4029 sec, LOAD: 0.8535 sec.
```

CUDA version: 
```
[root@gpu1 incubator-mxnet]# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

CUDNN version
```
[root@gpu1 incubator-mxnet]# cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 21
```

Package used (Python/R/Scala/Julia):
Python

Compiler (gcc/clang/mingw/visual studio):
`gcc`

MXNet commit hash:
 0ff490b62e33b1d33f5527de3a22d5f54b60fff

Build config:
`make -j 14 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1`

## Error Message:
`Segmentation fault (core dumped)`

## Minimum reproducible example
`python -c "import mxnet as mx; a = mx.nd.ones((2, 3), mx.gpu(1))"`

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Just run the command and wait for crash

## What have you tried to solve it?

1. Since I cannot change cuda version...I have no idea about it

**Comment by eric-haibin-lin** [comment] 2018-03-29 05:14
Related to https://github.com/apache/incubator-mxnet/issues/10305

**Comment by NKUCodingCat** [comment] 2018-04-01 18:22
I tried release 1.1 and failed like latest code....

**Comment by piyushghai** [comment] 2018-10-09 19:59
@NKUCodingCat I tried reproducing the issue on MXNet 1.3 and could not reproduce the issue.

Can you try on the latest release of MXNet ? 

Thanks!

**Comment by kalyc** [comment] 2018-11-14 18:29
Thanks for reporting the issue @NKUCodingCat, it appears to have been fixed. 
Could you close this issue?

**Closed** 2018-11-15 17:48 UTC
Labels: Bug
