### ISSUE TITLE
Expose MaxUnpooling operator

### ISSUE THREAD

**Issue by ehsanmok** [apache/incubator-mxnet#9969] opened 2018-03-02 23:16 UTC
MaxUnpooling operator API is not available despite its implementation [here](https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/pool.h#L388). This was also discussed in [dmlc#640](https://github.com/apache/incubator-mxnet/issues/640) but Bilinear sampling was implemented in [dmlc#746](https://github.com/apache/incubator-mxnet/pull/746) which is *different*.

After that it'd easy to support it in Gluon. Related to [this feature request](https://github.com/apache/incubator-mxnet/issues/9905).

**Comment by sxjscience** [comment] 2018-03-03 00:01
@ehsanmok Thanks for reporting this! Adding Unpooling layer is on our schedule. Please stay tuned. I'll close this because it's a duplicate of the previous issue.

**Closed by sxjscience** 2018-03-03 00:01 UTC
