### ISSUE TITLE
make err on RK3399

### ISSUE THREAD

**Issue by lovehuanhuan** [apache/incubator-mxnet#10883] opened 2018-05-10 07:02 UTC
As I was told by "http://mxnet.incubator.apache.org/install/"

After inputting 
"make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas"
I got these errors:
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/firefly/zzp/incubator-mxnet/3rdparty/mshadow/ -I/home/firefly/zzp/incubator-mxnet/3rdparty/dmlc-core/include -fPIC -I/home/firefly/zzp/incubator-mxnet/3rdparty/nnvm/include -I/home/firefly/zzp/incubator-mxnet/3rdparty/dlpack/include -I/home/firefly/zzp/incubator-mxnet/3rdparty/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -DMSHADOW_USE_SSE=0 -DMSHADOW_USE_F16C=0 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/include/opencv -I/usr/local/include -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMXNET_USE_LAPACK  -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/tensor/broadcast_reduce_op_index.cc -o build/src/operator/tensor/broadcast_reduce_op_index.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:431: recipe for target 'build/src/operator/tensor/matrix_op.o' failed
make: *** [build/src/operator/tensor/matrix_op.o] Error 4
make: *** Waiting for unfinished jobs....

^CMakefile:431: recipe for target 'build/src/operator/tensor/broadcast_reduce_op_index.o' failed
make: *** [build/src/operator/tensor/broadcast_reduce_op_index.o] Interrupt
Makefile:431: recipe for target 'build/src/operator/tensor/elemwise_binary_broadcast_op_basic.o' failed
make: *** [build/src/operator/tensor/elemwise_binary_broadcast_op_basic.o] Interrupt
Makefile:431: recipe for target 'build/src/operator/tensor/elemwise_binary_broadcast_op_extended.o' failed
make: *** [build/src/operator/tensor/elemwise_binary_broadcast_op_extended.o] Interrupt
make: *** wait: No child processes.  Stop.
firefly@firefly:~/zzp/incubator-mxnet$

**Comment by zhyj3038** [comment] 2018-05-10 07:36
I have make from source on 3399 just before.  remember turn off a flag, which ha relationship with  x86 or some thing elsew.

**Comment by kalyc** [comment] 2018-11-14 18:34
Thanks for reporting the issue @lovehuanhuan 
Have you tried a clean install of mxnet by doing `make clean` and then building the library? Is the problem still persisting?

**Comment by piyushghai** [comment] 2019-03-05 23:37
@lovehuanhuan Did @kalyc 's suggestions help you out ? 
If yes, please feel free to close the issue.

**Comment by frankfliu** [comment] 2019-06-18 17:04
@mxnet-label-bot add [Pending Requester Info]

**Comment by vdantu** [comment] 2019-06-28 18:28
@lovehuanhuan This is an old issue but just checking in to see if this is still an issue. I could use the same build command to build MXNet from source without any issues.

**Comment by zachgk** [comment] 2019-06-28 18:43
I am closing this issue because we are unable to reproduce it and can not proceed without additional information. @lovehuanhuan, please reopen if the problem persists.

**Closed by zachgk** 2019-06-28 18:43 UTC
Labels: Bug, Build, Pending Requester Info
