### ISSUE TITLE
PyPi wheel installation failed on Centos 7.5

### ISSUE THREAD

**Issue by wisdomdeng** [apache/incubator-mxnet#8372] opened 2017-10-21 06:35 UTC
System information
```
(mxnet) [ruizhid@cedar5 mxnet]$ lsb_release -a
LSB Version:	n/a
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core
```

Compile version
```
(mxnet) [ruizhid@cedar5 mxnet]$ gcc --version
gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(mxnet) [ruizhid@cedar5 mxnet]$ g++ --version
g++ (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Python version
```
(mxnet) [ruizhid@cedar5 mxnet]$ python
Python 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
(mxnet) [ruizhid@cedar5 mxnet]$ python --version
Python 2.7.14 :: Anaconda, Inc.
(mxnet) [ruizhid@cedar5 mxnet]$ pip --version
pip 9.0.1 from /home/ruizhid/miniconda/envs/mxnet/lib/python2.7/site-packages (python 2.7)
```

Installtion
```
(mxnet) [ruizhid@cedar5 mxnet]$ pip search mxnet
mxnet-to-coreml (0.1.2)          - Tool to convert MXNet models into Apple CoreML model format.
mxnet-cu75 (0.12.0b20171020)     - MXNet is an ultra-scalable deep learning framework. This version uses CUDA-7.5.
mxnet-cu75mkl (0.12.0b20171020)  - MXNet is an ultra-scalable deep learning framework. This version uses CUDA-7.5 and MKL-ML.
mxnet-cu80 (0.12.0b20171020)     - MXNet is an ultra-scalable deep learning framework. This version uses CUDA-8.0.
mxnet-cu80mkl (0.12.0b20171019)  - MXNet is an ultra-scalable deep learning framework. This version uses CUDA-8.0 and MKL-ML.
mxnet-cu90 (0.11.1b20171009)     - MXNet is an ultra-scalable deep learning framework. This version uses .
mxnet-cu90mkl (0.11.1b20171009)  - MXNet is an ultra-scalable deep learning framework. This version uses MKL-ML.
keras-mxnet (1.2.2)              - MXNet backend for Keras 1.2.2
mxnet-mkl (0.12.0b20171020)      - MXNet is an ultra-scalable deep learning framework. This version uses MKL-ML.
mxnet-model-server (0.3.5)       - MXNet Model Server
mxbox (0.0.22)                   - Image and video datasets and models for mxnet deep learning
mxnet (0.12.0b20171020)          - MXNet is an ultra-scalable deep learning framework. This version uses openblas.
(mxnet) [ruizhid@cedar5 mxnet]$ pip install mxnet
Collecting mxnet
  Could not find a version that satisfies the requirement mxnet (from versions: )
No matching distribution found for mxnet
(mxnet) [ruizhid@cedar5 mxnet]$ pip install mxnet-cu80
Collecting mxnet-cu80
  Could not find a version that satisfies the requirement mxnet-cu80 (from versions: )
No matching distribution found for mxnet-cu80
```

**Comment by szha** [comment] 2018-05-18 22:32
closing. ping me if the issue is still not resolved.

**Closed by szha** 2018-05-18 22:32 UTC
Labels: pip
