### ISSUE TITLE
Incomplete UpSamping doc

### ISSUE THREAD

**Issue by ehsanmok** [apache/incubator-mxnet#9970] opened 2018-03-02 23:31 UTC
Despite the doc provided [here](https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/upsampling-inl.h#L78) there's no details provided in its [Python API](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.UpSampling) about an extra parameter needed when `sample_type='bilinear'`.

**Comment by sxjscience** [comment] 2018-03-03 00:09
Thanks for reporting this! @zhanghang1989 has written a new `BilinearResize` operator (See https://github.com/apache/incubator-mxnet/pull/9688). It will be merged in the future and we will revise the doc.

**Comment by sxjscience** [comment] 2018-03-03 00:10
I'll close this first because the issue is the same as in https://github.com/apache/incubator-mxnet/issues/9138.

**Closed by sxjscience** 2018-03-03 00:10 UTC
Labels: Doc, Operator
