### ISSUE TITLE
No "full" pooling convention support with MKL-DNN

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#10092] opened 2018-03-14 00:27 UTC
I'm kind of lacking context here, but I'd like to track this issue. More details are available at https://github.com/apache/incubator-mxnet/pull/10021

@ashokei would you mind summarizing the problem?

**Comment by ashokei** [comment] 2018-03-14 00:42
@marcoabreu The issue is with a specific SSD-VGG16-reduced model, in which pooling convention of full (only with maxpool) causes failure. 

The solution in #10021 is to fall-back to CPU maxpool/full-pooling convention.  This fallback approach is used anytime we have a config/option not supported by mkl-dnn integration yet. So this is not a "bug" per se. It would be feature that may be enabled / implemented in future. I would remove "bug" as it is misleading for this ticket. With the fix in @10021 this issue will be resolved.

**Comment by marcoabreu** [comment] 2018-03-14 01:01
Thanks a lot for the explanation. 

Does it fail because it has not been implemented by MKLDNN or because the implementation itself fails?

**Comment by ashokei** [comment] 2018-03-14 01:59
not been implemented by mkldnn for this specific case, hence with fix in #10021 we fallback to CPU just like any other feature/configure that is not currently implemented/supported-by-mkldnn-integration.

**Comment by pengzhao-intel** [comment] 2018-03-14 05:45
I think the current change is fine and the path can be back when MKL-DNN supports 'full' pooling convention. 
@ashokei could you also share the implementation plan of MKL-DNN to the community?

**Comment by TaoLv** [comment] 2019-01-30 13:55
Closed via https://github.com/apache/incubator-mxnet/pull/11047

**Closed by TaoLv** 2019-01-30 13:55 UTC
Labels: Feature request, MKL, Operator
