### ISSUE TITLE
Feature Request: randint

### ISSUE THREAD

**Issue by safrooze** [apache/incubator-mxnet#12478] opened 2018-09-07 17:06 UTC
## Description
MXNet has no `randint` implementation and integer sampling can be both limiting and confusing to developers:
* If using random_uniform with 'float32', the range is limited to 16.6M, beyond with there is no one to one mapping between float and int values.
* My tests show that random_uniform with 'float64' seem to address the issue, but this is not obvious to most developers and it may be extra unnecessary precision to achieve the necessary accuracy.
* It isn't very well known how to do proper random integer sampling using an underlying float sampling, i.e.:
```
randint = cast(clip(random.uniform(low, high, shape), low, high-1), 'int32')
```  

A `randint` operator implementation will solve all above issues.

**Comment by safrooze** [comment] 2018-09-07 17:07
@mxnet-label-bot [Feature request]

**Comment by eric-haibin-lin** [comment] 2018-09-07 21:18
https://github.com/apache/incubator-mxnet/issues/11218 
@mseth10  did you make any progress on this?

**Comment by szha** [comment] 2018-09-07 22:32
Duplicate of #11218

**Closed by szha** 2018-09-07 22:32 UTC
Labels: Feature request
