### ISSUE TITLE
gluon.nn.Conv2DTranspose() may have a problem working with MKLDNN data ?

### ISSUE THREAD

**Issue by TriLoo** [apache/incubator-mxnet#15635] opened 2019-07-23 05:25 UTC
`mxnet version`: 1.5.0
`OS`: Centos 7.2
`Python`: 3.6
`CPU`: Xeon E5-2650 v4

Following code can reproduce this bug on my server: 
```python
import mxnet as mx
from mxnet import gluon
class VerifyConcatMKL(gluon.HybridBlock):
    def __init__(self, **kwargs):
        super(VerifyConcatMKL, self).__init__(**kwargs)
        self.conv = gluon.nn.Conv2D(10, 3, 1, 1)
        self.conv1 = gluon.nn.Conv2D(channels=128, kernel_size=3, strides=1, padding=1)
        self.deconv1 = gluon.nn.Conv2DTranspose(64, 4, 2, 1)

    def hybrid_forward(self, F, x, *args, **kwargs):
        feat = self.conv(x)
        output = self.conv1(feat)
        output = self.deconv1(output)
        return output

net = VerifyConcatMKL()
net.initialize()
data = mx.nd.ones((1, 3, 10, 10))
pred = net(data)
print(pred) .        # raise an error
```

The error info is:
```
mxnet.base.MXNetError: [13:19:25] src/ndarray/ndarray.cc:752: Check failed: !IsMKLDNNData(): We can't generate TBlob for MKLDNN data. Please use Reorder2Default() to generate a new NDArray first
```

**What I found:**
1.  if the `Conv2DTranspose()` after another `Conv2D()`, one output channel of these two operators must less than 24, for example
```Python
    self.conv1 = gluon.nn.Conv2D(channels=23, kernel_size=3, strides=1, padding=1)
    self.deconv1 = gluon.nn.Conv2DTranspose(64, 4, 2, 1)
```
works fine.

**Comment by pengzhao-intel** [comment] 2019-07-28 04:51
@TaoLv take a look for this?

**Comment by TaoLv** [comment] 2019-07-28 15:16
I cannot reproduce this issue with the recent 1.5.0 release but with the 1.4.0 release I can get the exact same error. A similar issue was fixed in https://github.com/apache/incubator-mxnet/pull/15088 and the fix is already merged and released in 1.5.0.

@TriLoo Can you double check for the MXNet version you used?

**Comment by TriLoo** [comment] 2019-07-29 12:40
@TaoLv 
Sure, my mxnet version  is exactly mxnet 1.15.0. But I found that my source code's commit hash is : `5fc4fc53df74f276aafa51208142e657e9cfe42d`. I downloaded the latest code and compiling it now.

**Comment by TaoLv** [comment] 2019-07-29 15:40
The version on master branch was changed to 1.5.0 right after the 1.4.0 was released. But the formal 1.5.0 was just released last week.

**Comment by TriLoo** [comment] 2019-07-29 16:03
@TaoLv 
Ok, I'll use the latest commit. Thanks for your reply ~

**Closed** 2019-07-29 16:10 UTC
Labels: Backend, Bug, MKLDNN
