### ISSUE TITLE
any.h:286: Check failed: type_ != nullptr The any container is empty requested=N5mxnet10Imperative6AGInfoE

### ISSUE THREAD

**Issue by hdmjdp** [apache/incubator-mxnet#17925] opened 2020-03-27 14:31 UTC
loss.backward()
  File "/home/hdm/miniconda3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 2200, in backward
    ctypes.c_void_p(0)))
  File "/home/hdm/miniconda3/lib/python3.6/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:51:51] /home/travis/build/dmlc/mxnet-distro/mxnet-build/3rdparty/dmlc-core/include/dmlc/./any.h:286: Check failed: type_ != nullptr The any container is empty requested=N5mxnet10Imperative6AGInfoE

please help me

**Comment by leezu** [comment] 2020-03-27 19:41
Please provide a minimal example to reproduce the error

**Comment by leezu** [comment] 2021-12-10 14:41
Closing as a duplicate of https://github.com/apache/incubator-mxnet/issues/9712
Please use `autograd.backward(losses)`
instead of

```
for loss in losses:
    loss.backward()
```

Another option is to use `loss.backward(retain_graph=True)`

**Closed by leezu** 2021-12-10 14:41 UTC
Labels: Bug
