### ISSUE TITLE
cannot import name 'registry'

### ISSUE THREAD

**Issue by bitdata** [apache/incubator-mxnet#9871] opened 2018-02-23 09:52 UTC
## Description
error while import mxnet.contrib.text

## Environment info 
mxnet-cu90                1.1.0b20180213            <pip>
---------Python Info----------
Version      : 3.6.2
Compiler     : MSC v.1900 64 bit (AMD64)
Build        : ('default', 'Jul 20 2017 12:30:02')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 9.0.1
Directory    : C:\ProgramData\Anaconda3\envs\gluon\lib\site-packages\pip
----------System Info----------
Platform     : Windows-7-6.1.7601-SP1
system       : Windows
node         : USER-5777KMOEDE
release      : 7
version      : 6.1.7601
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
Name
Intel(R) Xeon(R) CPU E31230 @ 3.20GHz

## Error Message:
\>\>\> from mxnet.contrib import text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\gluon\lib\site-packages\mxnet\contrib\text
\__init__.py", line 23, in <module>
    from . import embedding
  File "C:\ProgramData\Anaconda3\envs\gluon\lib\site-packages\mxnet\contrib\text
\embedding.py", line 36, in <module>
    from ... import registry
ImportError: cannot import name 'registry'

**Comment by szha** [comment] 2018-02-23 19:48
I can't reproduce this on mac using `mxnet==1.1.0b20180213` and don't have a windows machine to reproduce. I tested the same for master branch and didn't find a problem. @yajiedesign would you help check whether it's working?

**Comment by bitdata** [comment] 2018-02-24 03:08
Finding that a lot of files are lost in site-packages\mxnet, I uninstall and reinstall mxnet. Then error message goes away.
Thanks a lot, and sorry to disturb everyone.

**Comment by szha** [comment] 2018-02-24 04:12
No problem, don't worry. Let us know what else we may help with. Closing the issue now.

**Closed by szha** 2018-02-24 04:12 UTC
