### ISSUE TITLE
Flaky test_deconvolution

### ISSUE THREAD

**Issue by asitstands** [apache/incubator-mxnet#10973] opened 2018-05-16 12:50 UTC
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10970/1/pipeline/724

```
======================================================================
FAIL: test_operator_gpu.test_deconvolution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 157, in test_new
    orig_test(*args, **kwargs)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_operator.py", line 1169, in test_deconvolution
    pad                 = (1,1)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_operator.py", line 1061, in check_deconvolution_forward_backward
    assert_almost_equal(out + args_grad_addto_npy[0], args_grad_addto[0].asnumpy(), rtol=1e-4, atol=1e-3)
  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu\python\mxnet\test_utils.py", line 493, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 1.029078 exceeds tolerance rtol=0.000100, atol=0.001000.  Location of maximum error:(1, 2, 19, 15), a=0.083483, b=0.082445
 a: array([[[[  -1.03032662,   84.66370263,  -15.19734333, ...,   75.15862218,
           -93.83804658,  -63.14129641],
         [  54.54269176,    7.71739136,   23.10548904, ...,   81.15015121,...
 b: array([[[[  -1.03033042,   84.6636734 ,  -15.19732857, ...,   75.15862274,
           -93.83802795,  -63.14128113],
         [  54.54269409,    7.71736002,   23.10546684, ...,   81.15015411,...
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1270064081 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by larroy** [comment] 2018-05-17 13:43
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/883/pipeline

**Comment by haojin2** [comment] 2018-05-22 22:57
Also encountered at: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11021/5/pipeline

**Comment by larroy** [comment] 2018-06-11 08:32
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11220/1/pipeline/

Sign flip in this case

**Comment by szha** [comment] 2018-06-12 22:57
Got a couple of this too http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11041/82/pipeline/724

**Comment by szha** [comment] 2018-06-14 01:10
Seems like this is the exact option that causes problems `nn.Conv2DTranspose(16, (3, 4), padding=4, in_channels=4)`

**Comment by anirudh2290** [comment] 2018-06-23 15:16
all failures seem specific to windows. unable to reproduce this on a linux env.

**Comment by szha** [comment] 2018-06-23 22:14
Tests that are already disabled should be re-enabled: https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_gluon.py#L428-L434
https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_gluon.py#L443
https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_gluon.py#L450-L465

**Comment by marcoabreu** [comment] 2018-06-27 23:01
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1058/pipeline/

**Comment by anirudh2290** [comment] 2018-06-28 20:44
I was struggling  to build MXNet on windows with DEBUG flag on without success. I realized that windows was testing a different code path compared to linux. Windows was testing the MXNet convolution and deconvolution ops while linux was testing the conv and deconv ops of cudnn. This is probably because windows probably has an older cudnn version. This code path should also be tested on linux so I have added it in this PR : https://github.com/apache/incubator-mxnet/pull/11470 

Finally I can reproduce on mxnet built on linux with USE_CUDA=1 USE_CUDNN=0, with the code changes from #11470 .

```
MXNET_TEST_SEED=1002773977 nosetests -v --logging-level=DEBUG tests/python/gpu/test_operator_gpu.py:test_deconvolution
```

Investigating the failure now.

**Comment by marcoabreu** [comment] 2018-06-28 20:46
Yes, on Windows we only test CUDA8

**Comment by lupesko** [comment] 2018-07-18 05:16
@anirudh2290 does https://github.com/apache/incubator-mxnet/pull/11470 fix the issue? if so - please close.

**Comment by anirudh2290** [comment] 2018-07-25 05:55
@lupesko I am waiting for Nvidia folks to comment on the related PR: #11630

**Comment by anirudh2290** [comment] 2018-08-01 18:13
has been fixed as part of #11630

**Comment by apeforest** [comment] 2019-01-30 23:53
We should re-enable the test if this is fixed. Working on it: def test_deconvolution():

**Comment by perdasilva** [comment] 2019-02-13 17:42
I'm seeing this again on an unrelated PR:

```
======================================================================

FAIL: test_operator_gpu.test_deconvolution

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 173, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_operator.py", line 1413, in test_deconvolution

    pad                 = (1,1)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_operator.py", line 1305, in check_deconvolution_forward_backward

    assert_almost_equal(out + args_grad_addto_npy[0], args_grad_addto[0].asnumpy(), rtol=1e-3, atol=1e-3)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 495, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 1.290297 exceeds tolerance rtol=0.001000, atol=0.001000.  Location of maximum error:(31, 2, 7, 11), a=0.181059, b=0.182585

 a: array([[[[  71.53303956,   27.22900263,  -81.94053338, ...,  131.83555384,

             0.14714987, -125.67693774],

         [  71.65034077, -127.16477248,   97.06501721, ...,  224.75550074,...

 b: array([[[[  71.53299713,   27.22902107,  -81.94055176, ...,  131.83551025,

             0.14712699, -125.6769104 ],

         [  71.65033722, -127.1647644 ,   97.06500244, ...,  224.75546265,...

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1614629591 to reproduce.

--------------------- >> end captured logging << ---------------------
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-14144/6/pipeline

**Comment by apeforest** [comment] 2019-02-18 17:00
Please reproduce this in master before marking it as flaky test.

**Closed by apeforest** 2019-02-18 17:00 UTC
Labels: Disabled test, Flaky, Test
