### ISSUE TITLE
flaky test test_gluon_model_zoo_gpu.test_inference 

### ISSUE THREAD

**Issue by spidyDev** [apache/incubator-mxnet#10750] opened 2018-04-30 20:03 UTC
build.py: 2018-04-30 19:20:49,927 Running ['/work/runtime_functions.sh', 'unittest_ubuntu_python2_gpu'] in container mxnet/build.ubuntu_gpu

build.py: 2018-04-30 19:20:49,927 Executing: nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-python2-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-gpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu

+ set +x

+ export PYTHONPATH=./python/

+ PYTHONPATH=./python/

+ export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0

+ MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0

+ nosetests-2.7 --verbose tests/python/gpu

[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=2027890742 to reproduce.

test_forward.test_consistency ... [19:21:00] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...

[19:21:00] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!

[INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=851076501 to reproduce.

ERROR

[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=1530227848 to reproduce.

test_gluon_model_zoo_gpu.test_inference ... testing inference on resnet50_v1

**[19:21:11] src/io/iter_image_recordio_2.cc:170: ImageRecordIOParser2: data/val-5k-256.rec, use 1 threads for decoding..

/work/runtime_functions.sh: line 391:     7 Segmentation fault      (core dumped) nosetests-2.7 --verbose tests/python/gpu**

build.py: 2018-04-30 19:21:12,195 Running of command in container failed (139): nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-python2-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-gpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu

build.py: 2018-04-30 19:21:12,195 You can try to get into the container by using the following command: nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-python2-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-gpu/build:/work/build -u 1001:1001 -ti --entrypoint /bin/bash mxnet/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu

into container: False

Traceback (most recent call last):

  File "ci/build.py", line 263, in <module>

    sys.exit(main())

  File "ci/build.py", line 204, in main

    container_run(platform, docker_binary, shared_memory_size, command)

  File "ci/build.py", line 126, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-python2-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-gpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu' returned non-zero exit status 139

script returned exit code 1

**Comment by marcoabreu** [comment] 2018-05-01 01:39
Hi @spidyDev, please also put a link to the job in the description

**Comment by sandeep-krishnamurthy** [comment] 2018-06-29 17:51
Could not reproduce with 1000 runs. Issue is fixed by Da in this PR - https://github.com/apache/incubator-mxnet/pull/9862 resolving MKLDNN memory layout race condition. Verified that recent 50 failures in CI doesn't have this issue.

Please reopen if issue still persists.

**Closed by sandeep-krishnamurthy** 2018-06-29 17:51 UTC
Labels: Flaky, Test
