### ISSUE TITLE
Add thumbs up/down for API/Example/Tutorial documentation

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#12610] opened 2018-09-20 07:48 UTC
Time and again we have heard users complain that the documentation on Apache MXNet could need improvement, but we don't know which parts need improvement and also we cannot just do one overhaul of all the documentation, so we need to capture user feedback. 

One suggestion @mli has made in the past is to have thumbs up/down reaction on each of the API/Example/tutorial documentation that exists, so we could capture and focus on the specific doc that users say is unclear or needs improvement.

@aaronmarkham here is the issue for you track and plan.

**Comment by aaronmarkham** [comment] 2018-09-26 20:35
@nswamy I'd label this a Website and not Doc.

**Comment by ys2843** [comment] 2020-06-18 23:16
This feature will be implemented in `Merge beta.mxnet.io to Official website` project.
Mark it as duplicate of #18548

**Comment by szha** [comment] 2020-06-20 22:59
Tracked in the linked issue above where there are more details

**Closed by szha** 2020-06-20 22:59 UTC
Labels: Feature request, Website
