### ISSUE TITLE
Flaky test on Python2 Windows

### ISSUE THREAD

**Issue by lanking520** [apache/incubator-mxnet#11394] opened 2018-06-25 20:07 UTC
## Description
CI Flaky on Python and Windows
@haojin2 @marcoabreu 

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11377/6/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11377/5/pipeline

**Comment by frankfliu** [comment] 2018-06-25 20:28
Thanks for the question.
@sandeep-krishnamurthy requesting this be labeled under Flaky and Test.

**Comment by marcoabreu** [comment] 2018-06-25 20:48
Duplicate of https://github.com/apache/incubator-mxnet/issues/11353

**Closed by marcoabreu** 2018-06-25 20:48 UTC

**Comment by lanking520** [comment] 2018-06-25 20:52
@marcoabreu this one is not dupes: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11377/5/pipeline

**Comment by marcoabreu** [comment] 2018-06-25 20:59
Oh sorry, that run is a duplicate of https://github.com/apache/incubator-mxnet/issues/11064 

I have reopened the issue for you. Please document your findings there.

P.S. In future, please paste the log into the ticket to prevent people from having to access our website.

**Comment by marcoabreu** [comment] 2018-06-25 21:02
Ah, sorry. I have documented it at https://github.com/apache/incubator-mxnet/issues/11395. 

I already engaged with Nvidia about that one but forgot to create GitHub issue.
