### ISSUE TITLE
inference results unstable in mxnet_mkl-1.2.0b20180416 

### ISSUE THREAD

**Issue by dwSun** [apache/incubator-mxnet#10580] opened 2018-04-17 09:27 UTC
## sysinfo
Python 3.6.5
debian sid

## desc
I am using mx.mod.Module to build my inference program.
When run a same inference several time without restart my program the results are unstable, only the first one is correct, others are differ from each other.
Then I change back to mxnet-mkl 1.1.0, the results become same again.

**Comment by TaoLv** [comment] 2018-04-17 09:48
Is it possible for you to give a repeatable model for this issue? Thanks.

**Comment by dwSun** [comment] 2018-04-17 10:31
try this.
[issue_10580.gz](https://github.com/apache/incubator-mxnet/files/1919272/issue_10580.gz)

**Comment by pengzhao-intel** [comment] 2018-04-17 11:27
did you try new mkldnn backbend?

**Comment by zheng-da** [comment] 2018-04-17 16:31
could you provide us a minimum script to reproduce the error? Thanks

**Comment by TaoLv** [comment] 2018-04-17 16:50
@dwSun Thanks for the scripts. Here is my update:
This issue can be reproduced on master branch with mkldnn enabled. I have tried several old commits, it seems this issue was introduced in since #9918 , which is just for updating mkldnn version. So I doubt there are some bugs in mkldnn. Need more investigation.
@xinyu-intel @pengzhao-intel

**Comment by zheng-da** [comment] 2018-04-17 16:56
Does it mean the bug is in the MKLDNN library?

**Comment by TaoLv** [comment] 2018-04-17 17:05
I guess yes, but not sure. I opened MXNET_MKLDNN_DEBUG but no complaints. Still need minimum case to reproduce it.

**Comment by TaoLv** [comment] 2018-04-18 02:58
On latest master, this issue for @dwSun 's script can be resolved by removing below line from mkldnn_convolution.cc
https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/mkldnn/mkldnn_convolution.cc#L286
```
weight.MKLDNNDataReorderAsync(fwd.fwd_pd.weights_primitive_desc());
```
However this change only works for inference. We still need more comprehensive solution for it.
I feel that we can't push async operation to execution engine from an operator body. It may cause dead lock or data race. @zheng-da @pengzhao-intel please take a look.

**Comment by zheng-da** [comment] 2018-04-18 04:46
The reason we push async here is to change the layout of weight arrays during inference so that we don't need to change the layout every time.
Originally, the code changed the data layout inside the array directly, and it caused a race condition. 

How is @dwSun code different from here https://github.com/apache/incubator-mxnet/blob/master/tests/python/gpu/test_gluon_model_zoo_gpu.py#L41
The code works here.

**Comment by TaoLv** [comment] 2018-04-19 15:32
update:
@dwSun could you help to try this branch to see if this issue still there?
https://github.com/TaoLv/incubator-mxnet/tree/fix-SetMKLMem

Thanks.

**Comment by dwSun** [comment] 2018-04-20 07:10
@TaoLv can you provide a pre-compiled pip package? 
Thanks

**Comment by TaoLv** [comment] 2018-04-20 07:27
Please ignore that. @zheng-da has submitted the final fix in #10624 . You can try the nightly build after that PR is merged. Thanks.

**Comment by zheng-da** [comment] 2018-04-27 06:03
@dwSun the bug should have been fixed. the code has been merged to the master branch. Could you please try and see if the fix has solved your problem? Thanks.

**Comment by dwSun** [comment] 2018-04-28 06:04
> https://github.com/apache/incubator-mxnet/files/1919272/issue_10580.gz
it is the code to reproduce this bug.

**Comment by dwSun** [comment] 2018-04-28 06:32
@zheng-da try this command:
```sh
tar -vxf issue_10580.gz
```

**Comment by zheng-da** [comment] 2018-04-29 01:56
I tried your script on my own machine with PR https://github.com/apache/incubator-mxnet/pull/10731.
it works fine. Could you please try again after the PR is merged?

**Comment by dwSun** [comment] 2018-05-01 02:00
waiting for PR #10731 to be merged

**Comment by dwSun** [comment] 2018-05-08 14:26
just tested with mxnet-mkl-1.2.0b20180508, it works well.

**Closed** 2018-05-08 23:47 UTC
