### ISSUE TITLE
Out of memory test on Ubuntu Python3 GPU : test_kvstore_gpu.test_rsp_push_pull

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#10325] opened 2018-03-29 22:59 UTC
## Description
Flaky test on ubuntu_gpu for the test - test_kvstore_gpu.test_rsp_push_pull while running on Python3. The failure is completely unrelated to my PR.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
Python3

Link to the CI run log:
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-10140/runs/7/nodes/586/log/?start=0

## Error Message:

> ======================================================================
> ERROR: test_kvstore_gpu.test_rsp_push_pull
> ----------------------------------------------------------------------
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
>     self.test(*self.arg)
>   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
>     orig_test(*args, **kwargs)
>   File "/work/mxnet/tests/python/gpu/test_kvstore_gpu.py", line 91, in test_rsp_push_pull
>     check_rsp_push_pull('device')
>   File "/work/mxnet/tests/python/gpu/test_kvstore_gpu.py", line 82, in check_rsp_push_pull
>     check_rsp_pull(kv, 4, [mx.gpu(i//2) for i in range(4)])
>   File "/work/mxnet/tests/python/gpu/test_kvstore_gpu.py", line 73, in check_rsp_pull
>     retained = val.asnumpy()
>   File "/work/mxnet/python/mxnet/ndarray/sparse.py", line 180, in asnumpy
>     return self.tostype('default').asnumpy()
>   File "/work/mxnet/python/mxnet/ndarray/ndarray.py", line 1826, in asnumpy
>     ctypes.c_size_t(data.size)))
>   File "/work/mxnet/python/mxnet/base.py", line 149, in check_call
>     raise MXNetError(py_str(_LIB.MXGetLastError()))
> 
> mxnet.base.MXNetError: [21:38:37] src/operator/tensor/./../mxnet_op.h:576: Check failed: err == cudaSuccess (2 vs. 0) Name: mxnet_generic_kernel ErrStr:out of memory

**Comment by anirudhacharya** [comment] 2018-03-30 21:55
Possibly a duplicate issue of . - https://github.com/apache/incubator-mxnet/issues/10322

**Comment by marcoabreu** [comment] 2018-03-31 00:09
Closed due to duplicate of #10322

**Closed by marcoabreu** 2018-03-31 00:09 UTC
Labels: Flaky, KVStore, Test
