### ISSUE TITLE
mxnet cpu broadcasting >5x slower than numpy

### ISSUE THREAD

**Issue by maxkohlbrenner** [apache/incubator-mxnet#8937] opened 2017-12-04 15:51 UTC
## Description
When running on cpu only, broadcasting a  larger array is a lot more time consuming on mxnet than on numpy. Is there a way to speed this up?

## Environment info (Required)
Running mxnet using python 2.7 on ubuntu 16.04 in cpu mode on Intel® Xeon(R) CPU E5-2687W v3 @ 3.10GHz × 20
Config entries for matrix computation libraries are:
USE_CUDA = 1
USE_CUDNN = 1
USE_NVRTC = 0
USE_OPENCV = 1
USE_OPENMP = 1
MKLML_ROOT=/usr/local
USE_MKL2017 = 1
USE_MKL2017_EXPERIMENTAL = 1
USE_NNPACK = 0
USE_BLAS = atlas
USE_LAPACK = 1
USE_INTEL_PATH = NONE

MXNet commit hash:
a5edbf94094581ee27157eae4f2113115a3994e7

A simple test script outputs the following: 

```
import mxnet as mx
from   mxnet import nd
import time
import numpy as np

num_trials = 100
shape_a = (1000, 10000)
shape_b = (1000,     1)

strt = time.time()

for i in range(num_trials):
    nd.waitall()

    a = nd.empty(shape_a)
    b = nd.empty(shape_b)
    c = a + b
    
    c = c.asnumpy() # implicitely waits for results to be finished
stp = time.time()

print c.shape
print 'avg time over {} trials: {}s'.format(num_trials, (stp - strt) / float(num_trials))

strt = time.time()
for i in range(num_trials):
    a = np.empty(shape_a)
    b = np.empty(shape_b)
    c = a + b

stp = time.time()

print c.shape
print 'avg time over {} trials: {}s'.format(num_trials, (stp - strt) / float(num_trials))
```

(1000, 10000)
avg time over 100 trials: 0.0974750995636s
(1000, 10000)
avg time over 100 trials: 0.0150070381165s

When broadcasting larger arrays, a performance difference is clearly noticeable, is there anything I can do to speed it up?

**Comment by piiswrong** [comment] 2017-12-05 22:59
@cjolivier01

**Comment by cjolivier01** [comment] 2017-12-06 01:52
What version was this done on?  0.11, 0.12, 1.0, this week's master?

**Comment by cjolivier01** [comment] 2017-12-06 01:56
Ok, I see this was done with version MXNet 0.11.0

**Comment by cjolivier01** [comment] 2017-12-06 02:10
Resolution:

In 0.11, when mxnet was built with CUDA enabled, OMP was not used for most operations in mxnet, even on CPU-only operations.  This changed in 0.12.

In 1.0, two additional things happened:
  1) @piiswrong refactored broadcast operators from using the deprecated mshadow framework to his Kernel/Launch framework
  2) Auto-tuning for selecting the most optimal OMP or non-OMP modes based upon thread count, number of data items and operator calculation "weight", thus using OMP for larger datasets and single-thread for smaller datasets (which is often faster).

Post 1.0, IntelOMP is built and used by default for cmake builds.

These things together make mxnet faster than numpy for most broadcast ops (so far as I have seen so far).  Times I get for the above script:

PASS 1...
(1000, 10000)
avg time over 100 trials: 0.0125194501877s
(1000, 10000)
avg time over 100 trials: 0.0115594983101s
PASS 2...
(1000, 10000)
avg time over 100 trials: 0.0119210195541s
(1000, 10000)
avg time over 100 trials: 0.0114824414253s

So, I think that the issue is resolved in current builds.  To get similar performance in your 0.11, you'd probably need to build without CUDA enabled.  

Please reopen the issue if necessary.

**Closed by cjolivier01** 2017-12-06 02:10 UTC
