### ISSUE TITLE
Flaky test test_operator_gpu.test_batchnorm_with_type

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#10942] opened 2018-05-14 23:11 UTC
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10939/2/pipeline
```
======================================================================

FAIL: test_operator_gpu.test_batchnorm_with_type

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 321, in test_batchnorm_with_type

    check_consistency(sym, ctx_list_v2_2D)

  File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency

    raise e

AssertionError: 

Items are not equal:

Error 1.120281 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(1,), a=0.580048, b=0.779297

 a: array([-809.1597   ,    0.5800476], dtype=float32)

 b: array([-809.    ,    0.7793], dtype=float16)

-------------------- >> begin captured stdout << ---------------------

Train Err: ctx 1 vs ctx 2 at norm_beta



--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=42792676 to reproduce.

--------------------- >> end captured logging << ---------------------

```

**Comment by ThomasDelteil** [comment] 2018-05-17 17:48
Happened to me too hre: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10959/6/pipeline/

**Comment by marcoabreu** [comment] 2018-06-07 11:58
Duplicate of https://github.com/apache/incubator-mxnet/issues/10087

**Closed by marcoabreu** 2018-06-07 11:58 UTC
Labels: Flaky, Operator, Test
