### ISSUE TITLE
[Jenkins CI] Broken R Unit test during build

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#7675] opened 2017-08-31 00:11 UTC
@thirdwing 

R GPU unit tests are failing more frequently on the master branch. Can you please take a look at this?
Example failed CI build - https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/master/272/pipeline/

**Comment by sandeep-krishnamurthy** [comment] 2017-08-31 16:37
@thirdwing Can we work on the fix to this soon? This issue is causing more frequent build failures.

**Comment by sandeep-krishnamurthy** [comment] 2017-09-01 00:28
This is causing a new issue. All master builds are failing. Can we relook at it? @thirdwing

**Comment by cjolivier01** [comment] 2017-09-05 21:08
I think I know what's causing this...

**Comment by thirdwing** [comment] 2017-09-06 19:03
The problem is the command executed by Jenkins server is not the same with commands in Jenkinsfile.

For example, the command executed in https://builds.apache.org/blue/organizations/jenkins/incubator-mxnet/detail/master/287/pipeline/280 
```
tests/ci_build/ci_build.sh cpu R CMD INSTALL --library=/workspace/ut-r-cpu/site-library mxnet_current_r.tar.gz
```

However, in our Jenkinsfile (https://github.com/apache/incubator-mxnet/blob/master/Jenkinsfile#L382):

```
sh "${docker_run} cpu R CMD INSTALL --library=/workspace/ut-r-cpu/site-library R-package"
```

Sorry that I don't know why they are different.

**Comment by cjolivier01** [comment] 2017-09-06 19:50
Which ones is known to work?

**Comment by cjolivier01** [comment] 2017-09-06 22:19
Fixed

**Comment by cjolivier01** [comment] 2017-09-06 22:23
Issue is thought to be resolved with this change

**Closed by cjolivier01** 2017-09-06 22:23 UTC
