### ISSUE TITLE
ndarray reshape function has docs errors

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12937] opened 2018-10-23 22:55 UTC
## Description
Sphinx throws errors on the `ndarray.reshape()` function.

## Error
```
/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/ndarray.py:docstring of mxnet.ndarray.NDArray.reshape:57: ERROR: Unexpected indentation.
/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/ndarray.py:docstring of mxnet.ndarray.NDArray.reshape:58: WARNING: Block quote ends without a blank line; unexpected unindent.
```

**Comment by andrewfayres** [comment] 2018-10-24 17:45
@mxnet-label-bot add [NDArray,doc]

**Comment by vandanavk** [comment] 2018-11-13 22:59
Duplicate of https://github.com/apache/incubator-mxnet/issues/13020

**Closed** 2018-11-15 20:58 UTC
Labels: Doc, NDArray
