### ISSUE TITLE
There is something wrong in Installation from source on OS X (Mac) page

### ISSUE THREAD

**Issue by fengsky401** [apache/incubator-mxnet#13776] opened 2019-01-05 11:46 UTC
In the page, https://mxnet.incubator.apache.org/install/osx_setup.html,
this part:
"To build with MKLDNN

echo "CC=$(brew --prefix llvm)/bin/clang++" >> ./config.mk
echo "CXX=$(brew --prefix llvm)/bin/clang++" >> ./config.mk
echo "USE_OPENCV=1" >> ./config.mk
echo "USE_OPENMP=1" >> ./config.mk
echo "USE_MKLDNN=1" >> ./config.mk
echo "USE_BLAS=apple" >> ./config.mk
echo "USE_PROFILER=1" >> ./config.mk
LIBRARY_PATH=$(brew --prefix llvm)/lib/ make -j $(sysctl -n hw.ncpu)
"
echo "CC=$(brew --prefix llvm)/bin/clang++"  should be modified to echo "CC=$(brew --prefix llvm)/bin/clang", I tried the origin one it report error, until I modified.

**Comment by pengzhao-intel** [comment] 2019-01-05 13:09
Thanks @fengsky401 to report the issue. We will fix it @xinyu-intel 

BTW, there's a page for MKLDNN installation.
https://github.com/apache/incubator-mxnet/blob/master/MKLDNN_README.md

**Comment by pengzhao-intel** [comment] 2019-01-05 13:10
@mxnet-label-bot add [MKLDNN, Installation]

**Comment by TaoLv** [comment] 2019-01-16 15:02
Closed via #13778 . Feel free to reopen if the issue is still there. @fengsky401

**Closed by TaoLv** 2019-01-16 15:02 UTC
Labels: Installation, MKLDNN
