### ISSUE TITLE
Gluon Conv1DTranspose causes "kernel died" 

### ISSUE THREAD

**Issue by relaxli00** [apache/incubator-mxnet#9508] opened 2018-01-20 14:02 UTC
Using pip-installed mxnet-cu90-1.0.1b20171229. Similar codes, Conv2DTranspose works fine and Conv1DTranspose causes kernel death, in Spyder 3.2.6.  Windows 10 / Anaconda 3 / Python 3.6

The working code with Conv2DTranspose:
==== 2D code ====
import mxnet as mx
from mxnet import gluon as g
import numpy as np

ctx = mx.cpu()
img = np.zeros((1, 3, 7))
img = img.reshape(img.shape[0], 3, 7, 1)
dataLoader = g.data.DataLoader(img, batch_size=1)

net = g.nn.Sequential()
with net.name_scope():
    net.add(g.nn.Conv2DTranspose(channels=3, kernel_size=(3,1), activation='relu'))

net.collect_params().initialize(mx.init.Normal(sigma=0.05))

for data in dataLoader:
    img = data.astype('float32')
    img = img.as_in_context(ctx)
    output = net(img)
==== 2D code end ====

Changed to 1D case, kernel dies every time:
==== 1D code ====
import mxnet as mx
from mxnet import gluon as g
import numpy as np

ctx = mx.cpu()

img = np.zeros((1, 3, 7))
dataLoader = g.data.DataLoader(img, batch_size=1)

net = g.nn.Sequential()
with net.name_scope():
    net.add(g.nn.Conv1DTranspose(channels=3, kernel_size=3, activation='relu'))

net.collect_params().initialize(mx.init.Normal(sigma=0.05))

for data in dataLoader:
    img = data.astype('float32')
    img = img.as_in_context(ctx)
    output = net(img)
==== 1D code end ====

Is there any trick for the Conv1DTranspose usage?

Thanks.

**Comment by haojin2** [comment] 2018-04-05 06:54
Hello, I tried to re-produce this issue earlier today with Spyder 3.2.6 on Windows 10/ CUDA 9.0/ Python 3.6.4 but with a newer build: mxnet-cu90-1.2.0b20180403 and was not able to reproduce the same bug. Please try the same code again with a newer build on your machine, and see if this bug still pops up, thanks for reporting the bug!

**Comment by anirudh2290** [comment] 2018-04-14 06:54
@relaxli00 can we close this ?

**Comment by relaxli00** [comment] 2018-04-14 08:01
Please go ahead to close it. I’m away currently and will turn back after a month or so. Will let you know if any problem is found at that time. Thanks.

**Closed** 2018-04-14 08:02 UTC
Labels: Bug
