### ISSUE TITLE
CUDA: unspecified launch failure on CI Windows

### ISSUE THREAD

**Issue by szhengac** [apache/incubator-mxnet#17616] opened 2020-02-17 23:06 UTC
## Description
CI on windows keeps giving `CUDA: unspecified launch failure`. It has been retriggered many times.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-17400/20/pipeline/

**Comment by ptrendx** [comment] 2020-02-19 17:15
@haojin2 The first failing test is `test_operator_gpu.test_np_nan_to_num`.

**Comment by haojin2** [comment] 2020-02-19 18:14
Please first disable then investigate.

**Comment by haojin2** [comment] 2020-02-20 06:07
#17630 still fails on windows-gpu with `test_np_nan_to_num` disabled, the error starts to occur on the test immediately after `test_np_nan_to_num`, meanwhile there were other PRs passing the windows-gpu build, as a result, I suspect the problem is not with the `test_np_nan_to_num` itself.

**Comment by ChaiBapchya** [comment] 2020-02-28 18:54
Another one for unrelated PR #17487  - http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-17487/24/pipeline

**Comment by leezu** [comment] 2020-04-24 06:36
This issue appears fixed by the toolchain updgrade https://github.com/apache/incubator-mxnet/pull/17962

**Closed by leezu** 2020-04-24 06:36 UTC
Labels: CI, Flaky
