### ISSUE TITLE
MKLDNN header missing in mxnet-cu102==1.7.0 pip package 

### ISSUE THREAD

**Issue by vycezhong** [apache/incubator-mxnet#19575] opened 2020-11-22 10:37 UTC
I encountered an compilation error showing that <mkldnn.h> is not found when I tried to compile BytePS with mxnet-cu102==1.7.0. I checked the mxnet package and indeed there is no MKLDNN header.

However, interestingly I found that it supports MKLDNN. And later I found MKLDNN is enabled by default in 1.7.0. https://github.com/apache/incubator-mxnet/pull/16899

![image](https://user-images.githubusercontent.com/25879526/99901319-ed4dbc80-2cf0-11eb-9c23-1e52384290f8.png)

So I suggest including the headers in the pip package.

**Comment by bartekkuncer** [comment] 2020-11-23 12:35
Hi @vycezhong,
I saw that there was simillar issue in the past: https://github.com/apache/incubator-mxnet/issues/18120, which has been fixed here: https://github.com/apache/incubator-mxnet/pull/18355. I will check why this issue is occurring again.
Thanks for reporting.

**Comment by bartekkuncer** [comment] 2020-11-23 14:26
I have checked that the fix has been applied to branch v1.7.x but not to the tag 1.7.0 which apparently is used to build the pip package.

**Comment by bartekkuncer** [comment] 2020-11-23 16:17
Please try using: https://repo.mxnet.io/dist/python/cu102/mxnet_cu102-1.7.0b20200813-py2.py3-none-manylinux2014_x86_64.whl. I believe it has all necessary headers.

**Comment by vycezhong** [comment] 2020-11-23 17:27
> Please try using: https://repo.mxnet.io/dist/python/cu102/mxnet_cu102-1.7.0b20200813-py2.py3-none-manylinux2014_x86_64.whl. I believe it has all necessary headers.

Thanks for your help.

**Comment by bartekkuncer** [comment] 2020-11-25 10:29
> > Please try using: https://repo.mxnet.io/dist/python/cu102/mxnet_cu102-1.7.0b20200813-py2.py3-none-manylinux2014_x86_64.whl. I believe it has all necessary headers.
> 
> Thanks for your help.

@vycezhong I understand that the package I proposed works for you? :)

@szha @leezu Should we release patch v1.7.1 which will fix the lacking headers or just wait for official minor v1.8.0 release?

**Comment by vycezhong** [comment] 2020-11-25 11:19
Yes it works for me. Thanks.

**Comment by szha** [comment] 2020-11-25 15:33
@bartekkuncer I think we should.

**Comment by bartekkuncer** [comment] 2020-11-26 10:53
> @bartekkuncer I think we should. At least it should be fixed with a post-release

@szha Ok, I will look into it.

**Comment by szha** [comment] 2020-11-26 17:12
@bartekkuncer it's just about repackaging and releasing on PyPI as another version. Since there is some ongoing license issue that needs to be sorted out first, we are putting changes to PyPI changes on hold. Will revisit once the issue is resolved.

**Comment by EnricoMi** [comment] 2021-01-26 10:34
Is there an ETA on releasing v1.7.1 or v1.7.0.post0 for cu101 and cu102?

**Comment by bartekkuncer** [comment] 2021-01-26 10:36
> Is there an ETA on releasing v1.7.1 or v1.7.0.post1 for cu101 and cu102?

@szha

**Comment by szha** [comment] 2021-01-26 14:53
Thanks for the ping. We resolved the license issue and I can get to it this week.

**Comment by EnricoMi** [comment] 2021-01-26 16:52
Awesome, thanks for picking it up!

**Comment by szha** [comment] 2021-02-01 21:58
Patched wheels are now available:
https://pypi.org/project/mxnet-cu101/#files
https://pypi.org/project/mxnet-cu102/#files

**Comment by EnricoMi** [comment] 2021-02-02 11:07
@szha thanks for the cu101 and cu102 releases, is a release with MKLDNN headers planned for [mxnet](https://pypi.org/project/mxnet/#history) as well? Version [mxnet-1.7.0.post1](https://buildkite.com/horovod/horovod/builds/4830#2c48d5bf-2ea7-4d03-988c-683777dab40c/6-4313) does not include headers.

**Comment by EnricoMi** [comment] 2021-02-02 11:17
With `mxnet-cu101==1.7.0.post0`, I get the following error:

```
    In file included from /usr/local/lib/python3.8/dist-packages/mxnet/include/mkldnn/mkldnn.hpp:24:0,
                     from /usr/local/lib/python3.8/dist-packages/mxnet/include/mxnet/ndarray.h:41,
                     from /tmp/pip-req-build-n16mfgkd/horovod/mxnet/mpi_ops.h:24,
                     from /tmp/pip-req-build-n16mfgkd/horovod/mxnet/mpi_ops.cc:21:
    /usr/local/lib/python3.8/dist-packages/mxnet/include/mkldnn/dnnl.hpp:23:10: fatal error: dnnl_config.h: No such file or directory
```

With `mxnet-cu101==1.7.0b20200813`, everything worked fine. Are there any changes between those two versions that I have to incorporate?

**Comment by leezu** [comment] 2021-02-02 14:58
It's a bug in the post0. I'm reopening the issue

**Comment by szha** [comment] 2021-02-05 22:23
Sorry, the two dnnl_* files were missed in post0. I posted 1.7.0.post1 to cu101/cu102 wheels which should include the necessary mkldnn headers (thanks @leezu for verifying). Let me look into including the headers for the CPU versions.

**Comment by EnricoMi** [comment] 2021-02-06 11:39
I can confirm 1.7.0.post1 for cu101 works for Horovod. Is a release of 1.7.0.post1 for cu110 also planned for the near future?

**Comment by szha** [comment] 2021-02-07 21:02
@EnricoMi our 1.8.0 release is in the pipeline so I think it's more likely to have cu110 release for that.

**Comment by szha** [comment] 2021-02-07 21:22
I uploaded the post2 versions of the CPU wheels to include mkldnn headers.

**Closed by szha** 2021-02-07 21:22 UTC
Labels: Bug, pip

**Comment by EnricoMi** [comment] 2021-02-10 10:32
@szha that post2 version for CPU works for Horovod, thanks!
