### ISSUE TITLE
[MXNet-Scala] Update DataBatch, DataIter/MXNDIterator, NDArrayIterator to take DataDesc of data and labels.

### ISSUE THREAD

**Issue by nswamy** [apache/incubator-mxnet#11878] opened 2018-07-25 00:15 UTC
Current Iterators do not take the layout and Shape information of both data and labels, this is essential to support Networks which take input with different layouts such as 'NTC' or 'TNC'.

**Comment by nswamy** [comment] 2018-07-25 00:17
#11775

**Comment by lupesko** [comment] 2018-08-07 02:35
@nswamy this does not seem like a bug, rather like a feature request. Can you please update the labels to remove "Bug"? Thanks!

**Comment by lanking520** [comment] 2018-09-24 23:29
@nswamy I think we can close this issue now since we add the support for DataDesc

**Comment by piyushghai** [comment] 2018-10-09 17:55
@nswamy Can you close this issue  as the related PRs have been merged ?

**Comment by lanking520** [comment] 2019-01-12 01:14
@nswamy Close this since the problem is fixed. Feel free to reopen the issue if the problem persist.

**Closed by lanking520** 2019-01-12 01:14 UTC
Labels: Feature request, Scala
