### ISSUE TITLE
Exit race condition on library handle usage

### ISSUE THREAD

**Issue by landersson** [apache/incubator-mxnet#8388] opened 2017-10-23 00:21 UTC
There seems to be some sort of race condition on the _LIB handle (in base.py) when calling exit() from python.

Code:
```
import mxnet as mx
data = mx.sym.Variable('data')
# del data
exit(0)
```
The code above occasionally trigger the following exception:
```
Exception ignored in: <bound method SymbolBase.__del__ of <Symbol data>>
Traceback (most recent call last):
  File "/OSM/CBR/D61_RCV/work/and502/build/mxnet/python/mxnet/_ctypes/symbol.py", line 46, in __del__
AttributeError: 'NoneType' object has no attribute 'NNSymbolFree'
```

**NOTE:** the error is only triggered "sometimes", and the particular missing attribute may be other than 'NNSymbolFree'. 

I guess the issue is that the _LIB handle gets deleted and set to None before all the objects using it have been deleted. If uncommenting the "del data" line, the problem seems to go away, or is at least a lot harder to trigger.

This happens in master as of today using python 3 under Ubuntu 16.04.

**Comment by szha** [comment] 2017-10-23 00:27
What's the version of mxnet? @cjolivier01 had a fix on exit race condition a while back.

**Comment by landersson** [comment] 2017-10-23 00:34
I'm using master as of today, commit c82c555a4633e5a3b0bfae7a4419357b1eec667c.

**Comment by cjolivier01** [comment] 2017-10-24 05:13
This sort of error doesn’t look familiar. What’s the difference in behavior of just letting the script finish rather than calling exit(0)? 
I’m not a python expert — does exit(0) cause a more immediate exit than reaching th end of the script? Is python shutdown procedure different?

**Comment by landersson** [comment] 2017-10-24 05:35
I guess calling exit(0) before reaching the end changes the order in which objects are deleted. I can't reproduce the error without the exit statement, so leaving it out probably causes the "data" object to be  deterministically deleted before the _LIB handle, while when using exit(), the _LIB handle sometimes gets deleted before the "data" object, causing the errors seen.

**Comment by cjolivier01** [comment] 2017-11-21 17:40
yes, I tried reproducing this but could not.  However, I think your assessment is correct -- _LIB gets destroyed before data, since 'data' doesn't take the normal 'going out of scope' destruction path and gets destroyed during general cleanup, which appears to not be deterministic in order.

It does not appear to be related to the engine shutdown, which was the focus of my previous shutdown fix.
I do not know if there is a way to avoid this except to use an exception to exit or something like that (which could be caught near a benign entry point), which will allow scope-destruction to occur in an organized manner.

Do you think we can close this issue?

**Comment by cjolivier01** [comment] 2017-12-07 05:30
Please reopen if necessary

**Closed by cjolivier01** 2017-12-07 05:30 UTC
