### ISSUE TITLE
CI failure: Python 3: MKLDNN-GPU Win: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException 

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#11667] opened 2018-07-12 15:21 UTC
Looks like a flaky test. The [PR ](http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11528/4/pipeline)has nothing to do with MKLDNN-GPU.

## Error Message:

[Pipeline] [Python 3: MKLDNN-GPU Win] }

[Pipeline] // parallel

[Pipeline] }

[Pipeline] // stage

[Pipeline] node

Running on mxnetlinux-cpu_nf5jdr2k1i in /home/jenkins_slave/workspace/incubator-mxnet_PR-11528-QQHFI25MND262P2N4BY27ZEYVMSNOVB4CJPCX3TL545RF6JDY22Q

[Pipeline] {

[Pipeline] sh

[incubator-mxnet_PR-11528-QQHFI25MND262P2N4BY27ZEYVMSNOVB4CJPCX3TL545RF6JDY22Q] Running shell script

+ echo caught hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException

caught hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException

[Pipeline] }

[Pipeline] // node

[Pipeline] node

Running on mxnetlinux-cpu_nf5jdr2k1i in /home/jenkins_slave/workspace/incubator-mxnet_PR-11528-QQHFI25MND262P2N4BY27ZEYVMSNOVB4CJPCX3TL545RF6JDY22Q

[Pipeline] {

[Pipeline] }

[Pipeline] // node

[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

java.nio.channels.ClosedChannelException

Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-172-31-9-166.us-west-2.compute.internal/172.31.9.166:59498

		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)

		at hudson.remoting.Request.call(Request.java:202)

		at hudson.remoting.Channel.call(Channel.java:954)

		at hudson.EnvVars.getRemote(EnvVars.java:408)

		at hudson.model.Computer.getEnvironment(Computer.java:1187)

		at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:662)

		at hudson.model.ResourceController.execute(ResourceController.java:97)

		at hudson.model.Executor.run(Executor.java:429)

Also:   <cycle to java.nio.channels.ClosedChannelException>

	Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-172-31-9-166.us-west-2.compute.internal/172.31.9.166:59498

			at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)

			at hudson.remoting.Request.call(Request.java:202)

			at hudson.remoting.Channel.call(Channel.java:954)

			at hudson.EnvVars.getRemote(EnvVars.java:408)

			at hudson.model.Computer.getEnvironment(Computer.java:1187)

			at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:662)

			at hudson.model.ResourceController.execute(ResourceController.java:97)

			at hudson.model.Executor.run(Executor.java:429)

	Caused: hudson.remoting.RequestAbortedException

Also:   java.nio.channels.ClosedChannelException

	Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-172-31-11-68.us-west-2.compute.internal/172.31.11.68:49922

			at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)

			at hudson.remoting.Request.call(Request.java:202)

			at hudson.remoting.Channel.call(Channel.java:954)

			at hudson.EnvVars.getRemote(EnvVars.java:408)

			at hudson.model.Computer.getEnvironment(Computer.java:1187)

			at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:662)

			at hudson.model.ResourceController.execute(ResourceController.java:97)

			at hudson.model.Executor.run(Executor.java:429)

	Caused: hudson.remoting.RequestAbortedException

Also:   hudson.AbortException: script returned exit code 1

		at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:335)

		at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:288)

		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

		at java.util.concurrent.FutureTask.run(FutureTask.java:266)

		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

Caused: hudson.remoting.RequestAbortedException

	at hudson.remoting.Request.abort(Request.java:340)

	at hudson.remoting.Channel.terminate(Channel.java:1038)

	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)

	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)

	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)

	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)

	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)

	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)

	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)

	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)

	at hudson.remoting.Channel.close(Channel.java:1450)

	at hudson.remoting.Channel.close(Channel.java:1403)

	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:746)

	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:99)

	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:664)

	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Finished: FAILURE

**Comment by apeforest** [comment] 2018-07-12 16:49
@sandeep-krishnamurthy Please label this _Flaky test_

**Comment by marcoabreu** [comment] 2018-07-12 17:20
Duplicate of https://github.com/apache/incubator-mxnet/issues/11644

**Closed by marcoabreu** 2018-07-12 17:20 UTC
