### ISSUE TITLE
Conv3DTranspose not work in Ubuntu.

### ISSUE THREAD

**Issue by PistonY** [apache/incubator-mxnet#14712] opened 2019-04-16 10:21 UTC
This is my code
```python
import mxnet
from mxnet import nd
from mxnet.gluon import nn

ab = nd.random.normal(shape=(1, 64, 4, 4, 4),ctx=mx.gpu())
fra = nn.Conv3DTranspose(channels=32, kernel_size=3, padding=1)

fra.initialize(ctx=mx.gpu())
print(fra(ab))
```
But report a cudnn bug, I also tried nvidia-docker (official) also not work too.
```
[18:24:26] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "/home/piston/PycharmProjects/iqiyi-cvic/match/test.py", line 11, in <module>
    print(fra(ab))
  File "/home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 193, in __repr__
    return '\n%s\n<%s %s @%s>' % (str(self.asnumpy()),
  File "/home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 1992, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:24:26] src/operator/nn/./cudnn/cudnn_deconvolution-inl.h:867: Failed to find any forward deconvolution algorithm with workspace size of 536870912 bytes, please consider reducing batch/model size or increasing the workspace size

Stack trace returned 10 entries:
[bt] (0) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x4271f2) [0x7fc48762f1f2]
[bt] (1) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x4277d8) [0x7fc48762f7d8]
[bt] (2) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x3f79c82) [0x7fc48b181c82]
[bt] (3) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x3f7e0b1) [0x7fc48b1860b1]
[bt] (4) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x3f6f2e2) [0x7fc48b1772e2]
[bt] (5) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x3f6f707) [0x7fc48b177707]
[bt] (6) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x3f7079d) [0x7fc48b17879d]
[bt] (7) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x3f716d3) [0x7fc48b1796d3]
[bt] (8) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x3f772ae) [0x7fc48b17f2ae]
[bt] (9) /home/piston/.conda/envs/mxnet/lib/python3.7/site-packages/mxnet/libmxnet.so(mxnet::imperative::PushFCompute(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const+0x36d) [0x7fc48a44db9d]

```

**Comment by PistonY** [comment] 2019-04-16 10:28
Also, I tried to reduce/model size is not work too.

**Comment by frankfliu** [comment] 2019-04-16 15:52
@mxnet-label-bot add [gluon, bug, cuda]

**Comment by PistonY** [comment] 2019-04-16 16:20
windows could run the same code but Ubuntu can’t.

**Comment by haojin2** [comment] 2019-05-01 05:50
@PistonY What GPU do you have? Can you share the nvidia-smi outputs?

**Comment by PistonY** [comment] 2019-05-05 03:15
I use GTX 1070 with CUDA10.
```
NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   49C    P8    10W / 180W |    787MiB /  8116MiB |      0%      Default |

```

**Comment by wkcn** [comment] 2019-05-05 13:32
What is the version of CUDNN?

**Comment by Arelax-zhu** [comment] 2019-05-06 03:04
@wkcn   
CUDNN 7.0.5, CUDA 9.0, Ubuntu 16.04  
```
error:
mxnet.base.MXNetError: [10:55:33] src/operator/nn/./cudnn/cudnn_deconvolution-inl.h:849: Failed to find any forward deconvolution algorithm with workspace size of 536870912 bytes, please consider reducing batch/model size or increasing the workspace size
```

**Comment by suyz526** [comment] 2019-05-09 10:04
works on Ubuntu 16.04, CUDA 10.1, CUDNN 7, mxnet 1.3.1

**Comment by mseth10** [comment] 2019-05-17 03:05
minimum cuDNN version required to support CUDA 10 is 7.3.1
@PistonY can you please check your cuDNN version?

**Comment by abhinavs95** [comment] 2019-06-04 20:19
Possibly related to #13135

**Comment by sandeep-krishnamurthy** [comment] 2019-06-05 21:19
Closing it in favor of #13135 Please reopen if you see the issue is different.

**Closed by sandeep-krishnamurthy** 2019-06-05 21:19 UTC
Labels: Bug, CUDA, Gluon
