### ISSUE TITLE
im2rec documentation is lacking / buggy

### ISSUE THREAD

**Issue by kjchalup** [apache/incubator-mxnet#11884] opened 2018-07-25 16:50 UTC
[im2rec.py](https://github.com/apache/incubator-mxnet/blob/master/tools/im2rec.py) doesn't have docstrings. The online doc that describes the RecordIO format ([here](https://mxnet.incubator.apache.org/architecture/note_data_loading.html)) doesn't describe how to use the script. [Another page](https://mxnet.incubator.apache.org/faq/recordio.html) does, but it could really use a full-fledged real-world example, and should either be unified with or at least linked to from the other doc page.

In addition, the im2rec.py script encodes class labels as floating point numbers:
```
def write_list(path_out, image_list):
    with open(path_out, 'w') as fout:
        for i, item in enumerate(image_list):
            line = '%d\t' % item[0]
            for j in item[2:]:
                line += '%f\t' % j ### <---- THIS IS THE FLOATING POINT LABEL
            line += '%s\n' % item[1]
            fout.write(line)
```
But the [doc page](https://mxnet.incubator.apache.org/faq/recordio.html) has integer labels in the example. When trying to make my own test .lst file by hand I used integer labels which in fact didn't work with mx.io.ImageRecordIter. It'd be great to get a clarification on the exact required .lst file format.

**Comment by stu1130** [comment] 2018-09-19 00:10
Thanks for submitting the issue @kjchalup 
The reason why it uses floating point is that the label value could be generated by the regression, e.g. 68.6 kg for a human body weight.
There is a [page](https://mxnet.incubator.apache.org/tutorials/basic/data.html) that uses im2rec with real data.
I did some experiments to change the code to %d and it works with ImageRecordIter.
Could you provide some reproducible code for me?
I would update the documentation as well.

**Comment by stu1130** [comment] 2018-09-19 17:36
After I traced the code from [im2rec.py](https://github.com/apache/incubator-mxnet/blob/master/tools/im2rec.py). The correct format is `float`. But if you use integer for label data, it should work fine since float(label value) return a float anyway

**Comment by lupesko** [comment] 2018-09-21 23:58
Fix merged - thanks @stu1130 - this can be resolved.
@kjchalup - kindly resolve, or add more details if there is still an issue. Thanks!

**Closed** 2018-09-22 03:47 UTC
Labels: Data-loading, Doc, Unclear Error/Doc
