### ISSUE TITLE
Fail to install mxnet on Macos using docker (./tools.sh)

### ISSUE THREAD

**Issue by danielgoncalvesti** [apache/incubator-mxnet#16629] opened 2019-10-25 19:27 UTC
## Description
I'm trying to run the script incubator-mxnet/docker/tools.sh but I'm getting a message of error when the script is executed. 

### Error Message
cp /mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn.so.0 /mxnet/lib
cp: cannot stat '/mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn.so.0': No such file or directory
make: *** [/mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn.so.0] Error 1

**Comment by ChaiBapchya** [comment] 2019-10-25 23:25
Hey @danielgoncalvesti Thanks for posting this issue
But we need more code for reproducing this issue.
For starters - Which commit+device+language?

**Comment by danielgoncalvesti** [comment] 2019-10-29 01:54
I'm using the latest commit from the master branch. 
My configuration is: 
-MacOS Catalina 10.15
-Docker 2.1.0.4 (stable)
-Python 3.7.4

I short, I enter the docker folder, and then run this command:
`./tool.sh build python cpu`

**Comment by ChaiBapchya** [comment] 2019-10-31 20:29
My config
MacOS High Sierra 10.13.6
Docker 2.1.0.4
Python 3.7.5

`./tool.sh build python cpu`
Was able to reproduce this error. Working on fixing it

**Comment by ChaiBapchya** [comment] 2019-10-31 20:30
@mxnet-label-bot remove [Pending Requester Info]

**Comment by ChaiBapchya** [comment] 2019-10-31 21:34
It's not just for Mac (as i tried it for unix too) and error was reproduced.
@mxnet-label-bot add [MKLDNN, Build, Docker]

**Comment by ChaiBapchya** [comment] 2019-10-31 21:36
For reference, error
```
[100%] Built target mkldnn
make[2]: Leaving directory `/mxnet/3rdparty/mkldnn/build'
Install the project...
-- Install configuration: "Release"
-- Installing: /mxnet/3rdparty/mkldnn/build/install/share/doc/mkldnn/LICENSE
-- Installing: /mxnet/3rdparty/mkldnn/build/install/lib/x86_64-linux-gnu/libmkldnn.so.1.0
-- Installing: /mxnet/3rdparty/mkldnn/build/install/lib/x86_64-linux-gnu/libmkldnn.so.1
-- Installing: /mxnet/3rdparty/mkldnn/build/install/lib/x86_64-linux-gnu/libmkldnn.so
-- Installing: /mxnet/3rdparty/mkldnn/build/install/include/mkldnn_config.h
-- Installing: /mxnet/3rdparty/mkldnn/build/install/include/mkldnn_version.h
-- Installing: /mxnet/3rdparty/mkldnn/build/install/include/mkldnn.h
-- Installing: /mxnet/3rdparty/mkldnn/build/install/include/mkldnn_debug.h
-- Installing: /mxnet/3rdparty/mkldnn/build/install/include/mkldnn_types.h
-- Installing: /mxnet/3rdparty/mkldnn/build/install/include/mkldnn.hpp
-- Installing: /mxnet/3rdparty/mkldnn/build/install/lib/x86_64-linux-gnu/cmake/mkldnn/mkldnn-config.cmake
-- Installing: /mxnet/3rdparty/mkldnn/build/install/lib/x86_64-linux-gnu/cmake/mkldnn/mkldnn-config-version.cmake
-- Installing: /mxnet/3rdparty/mkldnn/build/install/lib/x86_64-linux-gnu/cmake/mkldnn/mkldnn-targets.cmake
-- Installing: /mxnet/3rdparty/mkldnn/build/install/lib/x86_64-linux-gnu/cmake/mkldnn/mkldnn-targets-release.cmake
make[1]: Leaving directory `/mxnet/3rdparty/mkldnn/build'
mkdir -p /mxnet/lib
if [ -f "/mxnet/3rdparty/mkldnn/build/install/lib64/libmkldnn.so.1" ]; then \
                cp /mxnet/3rdparty/mkldnn/build/install/lib64/libmkldnn* /mxnet/lib; \
                cp /mxnet/3rdparty/mkldnn/build/install/lib64/libmkldnn* /mxnet/3rdparty/mkldnn/build/install/lib/; \
        else \
                cp /mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn* /mxnet/lib; \
        fi
cp: cannot stat '/mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn*': No such file or directory
make: *** [/mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn.so.1] Error 1
The command '/bin/sh -c git clone --recursive https://github.com/dmlc/mxnet && cd mxnet &&     make -j$(nproc) &&     rm -r build' returned a non-zero code: 2
```

**Comment by pengzhao-intel** [comment] 2019-10-31 22:30
@xinyu-intel could you help take a look for the MKLDNN library link?

**Comment by TaoLv** [comment] 2019-11-01 02:17
Just to clarify, the issue is not caused by the MKL-DNN 1.0 upgrading. It was reported against the master branch before #16555 was merged. It relates to the cmake installation behavior on different OS distributions. Anyway we will fix it on the latest master branch.

**Closed** 2019-11-01 06:36 UTC
Labels: Bug, Build, Docker, MKLDNN
