### ISSUE TITLE
Enable the test_CSVIter which fails intermittently on windows

### ISSUE THREAD

**Issue by gautamkmr** [apache/incubator-mxnet#7826] opened 2017-09-09 22:27 UTC
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows

Compiler:

Package used (Python/R/Scala/Julia): Python

MXNet version: master

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. nosetests tests/python/unittest/test_io.py
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by gautamkmr** [comment] 2017-09-11 22:43
Running the test on windwos environment fails with following 
- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2017-09-11T22:20:04.170823700Z 
 
   EventRecordID 4672 
 
   Channel Application 
 
   Computer EC2AMAZ-SQL8POR 
 
   Security 
 

- EventData 

   python.exe 
   3.6.1150.1013 
   58d320d0 
   libmxnet.dll 
   0.0.0.0 
   59b6bc76 
   c0000005 
   0000000000dd7f28 
   5d8 
   01d32b4c1b20cf09 
   C:\Anaconda3\envs\py3\python.exe 
   c:\Users\jenkins\Downloads\workspace\ut-python-cpu\pkg_vc14_cpu\build\libmxnet.dll 
   04ddb8ec-73c8-4452-ab18-cf25f7ce2ddc 
    
    


- EventData 

   python.exe 
   3.6.1150.1013 
   58d320d0 
   libmxnet.dll 
   0.0.0.0 
   59b6bc76 
   c0000005 
   0000000000dd7f28 
   5d8 
   01d32b4c1b20cf09 
   C:\Anaconda3\envs\py3\python.exe 
   c:\Users\jenkins\Downloads\workspace\ut-python-cpu\pkg_vc14_cpu\build\libmxnet.dll 
   04ddb8ec-73c8-4452-ab18-cf25f7ce2ddc 
    
    

   3.6.1150.1013 
   58d320d0 
   libmxnet.dll 
   0.0.0.0 
   59b6bc76 
   c0000005 
   0000000000dd7f28 
   5d8 
   01d32b4c1b20cf09 
   C:\Anaconda3\envs\py3\python.exe 
   c:\Users\jenkins\Downloads\workspace\ut-python-cpu\pkg_vc14_cpu\build\libmxnet.dll 
   04ddb8ec-73c8-4452-ab18-cf25f7ce2ddc

**Comment by gautamkmr** [comment] 2017-09-12 00:19
Step to reproduce the issue. just run this test on g2.2x or g2.8x ec2 windows instance.

**Comment by szha** [comment] 2017-12-30 00:26
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by haojin2** [comment] 2018-06-22 05:08
@szha this is already fixed in #10533.

**Comment by haojin2** [comment] 2018-06-22 05:11
The fundamental cause was in dmlc-core, and fixed in https://github.com/dmlc/dmlc-core/pull/381

**Comment by apeforest** [comment] 2018-06-22 22:33
I have run this test on Windows built from the latest MXNet source and could not reproduce the error.

**Comment by szha** [comment] 2018-06-22 22:50
thanks @haojin2 for the fix, @apeforest for confirming the fix.

**Closed by szha** 2018-06-22 22:50 UTC
Labels: Bug, Flaky, Windows
