### ISSUE TITLE
[MXNET-84] Segfault test_autograd.test_unary_func @ Python3: MKLDNN-CPU

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#10086] opened 2018-03-13 15:12 UTC
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/474/pipeline/485/

```
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=56561434 to reproduce.

test_autograd.test_unary_func ... /work/runtime_functions.sh: line 312:     6 Segmentation fault      (core dumped) nosetests-3.4 --verbose tests/python/unittest

build.py: 2018-03-11 11:21:48,801 Running of command in container failed: docker run --rm -v /home/jenkins_slave/workspace/ut-python3-mkldnn-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python3-mkldnn-cpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_python3_cpu

build.py: 2018-03-11 11:21:48,801 You can try to get into the container by using the following command: docker run --rm -v /home/jenkins_slave/workspace/ut-python3-mkldnn-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python3-mkldnn-cpu/build:/work/build -u 1001:1001 -ti --entrypoint bash mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_python3_cpu

Traceback (most recent call last):

  File "ci/build.py", line 179, in <module>

    sys.exit(main())

  File "ci/build.py", line 159, in main

    container_run(platform, docker_binary, command)

  File "ci/build.py", line 110, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'docker run --rm -v /home/jenkins_slave/workspace/ut-python3-mkldnn-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python3-mkldnn-cpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_python3_cpu' returned non-zero exit status 139

script returned exit code 1
```

Tracked at https://issues.apache.org/jira/browse/MXNET-84

**Comment by pengzhao-intel** [comment] 2018-03-19 07:20
@marcoabreu we are trying to reproduce this issue but can't. Could you reproduce it?

Actually, the MKL-DNN OP is not used in this test.  So we need to double check this issue. 

```
(apache)[zhiyuanh@mlt-bdw024 incubator-mxnet]$ git branch
* (detached from 94f68fc)
  master
```
```
(apache)[zhiyuanh@mlt-bdw024 incubator-mxnet]$ python -V
Python 3.6.1 :: Anaconda custom (64-bit)
(apache)[zhiyuanh@mlt-bdw024 incubator-mxnet]$ nosetests --verbose tests/python/unittest/test_autograd.py:test_unary_func
/home/zhiyuanh/anaconda3/lib/python3.6/site-packages/nose/util.py:453: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  inspect.getargspec(func)
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=1685770351 to reproduce.
test_autograd.test_unary_func ... ok

----------------------------------------------------------------------
Ran 1 test in 0.025s

OK

```

**Comment by marcoabreu** [comment] 2018-03-19 07:23
Hi Patric, could you try using the seed 56561434?

**Comment by pengzhao-intel** [comment] 2018-03-19 07:38
No crash with specified seed @marcoabreu 

```
(apache)[zhiyuanh@mlt-skx060 incubator-mxnet]$ nosetests tests/python/unittest/test_autograd.py:test_unary_func
/home/zhiyuanh/anaconda3/lib/python3.6/site-packages/nose/util.py:453: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  inspect.getargspec(func)
/home/zhiyuanh/0319/incubator-mxnet/tests/python/unittest/common.py:221: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('*** module-level seed is set: all tests running deterministically ***')
[WARNING] *** module-level seed is set: all tests running deterministically ***
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=56561434 to reproduce.
.
----------------------------------------------------------------------
Ran 1 test in 0.034s

OK
```

**Comment by marcoabreu** [comment] 2018-03-19 09:47
Seems like we'll have to dig a bit deeper to find the segfault. Since it's not using an MKL operator, I'll remove that label. Thanks for investigating!

**Comment by anirudh2290** [comment] 2018-06-27 23:48
assigned to myself, @azai91 is working on this.

**Comment by azai91** [comment] 2018-06-28 00:00
build with MKLDNN and ran 10000 times. was not able to reproduce.
```
[DEBUG] 9999 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=2051518549 to reproduce.
this test seed 1227028138
[DEBUG] 10000 of 10000: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1227028138 to reproduce.
ok

----------------------------------------------------------------------
Ran 1 test in 89.334s

OK
ubuntu@ip-172-31-11-93:~/incubator-mxnet-original$ MXNET_TEST_COUNT=10000 nosetests --logging-level=DEBUG --verbose -s tests/python/unittest/test_autograd.py:test_unary_func
```
will try building with cuda as well.

**Comment by anirudh2290** [comment] 2018-07-13 23:20
closing, please reopen if still able to reproduce.

**Closed by anirudh2290** 2018-07-13 23:20 UTC
Labels: Flaky, Test
