### ISSUE TITLE
[Website] Java, Scala, C++, R, Clojure, and Julia API References redirect to 404

### ISSUE THREAD

**Issue by connorgoggins** [apache/incubator-mxnet#18604] opened 2020-06-22 17:01 UTC
## Description
Java issue: trying to access the MXNet Java API reference from [this page](https://mxnet.apache.org/api/java.html) leads to a 404. This issue also extends to all of the other language docs mentioned in the title.

### Error Message
[404 page](https://mxnet.apache.org/api/java/docs/api/#org.apache.mxnet.infer.javaapi.package)

## To Reproduce
Navigate to the [MXNet Java homepage](https://mxnet.apache.org/api/java.html) or [Docs & Tutorials](https://mxnet.apache.org/api) on the MXNet website and try to access the MXNet Java API reference.

**Comment by connorgoggins** [comment] 2020-06-22 17:02
@mxnet-label-bot add [Website]

**Comment by leezu** [comment] 2020-06-22 18:02
Should this have been caught by the automatic link checker?

**Comment by connorgoggins** [comment] 2020-06-22 18:58
@leezu I'm not personally familiar with the automatic link checker, but I would assume so.

**Comment by ys2843** [comment] 2020-06-22 19:17
This is happening on the latest build, probably these 2 PR import the bug #18598 #18578

**Comment by connorgoggins** [comment] 2020-06-22 19:50
Thanks @ys2843. Found what I believe to be the root cause in #18598 - merge for this PR should be reverted ASAP.

**Comment by connorgoggins** [comment] 2020-06-22 20:01
Updated issue as it is worse than initial assessment - docs for Java, Scala, C++, R, Clojure, and Julia are not being built and are no longer available on the website.

**Comment by eric-haibin-lin** [comment] 2020-06-22 20:05
That's correct, the PR removes the language bindings that use the old graph executor APIs. For now we need to remove them from the master version of the website until they are available in mxnet 2.0. Users can access these language binding docs in mxnet 1.6 website version. Let's work together to remove them, instead of reverting the PR.

**Comment by connorgoggins** [comment] 2020-06-22 20:06
Was there community consensus on this change? @eric-haibin-lin

**Comment by leezu** [comment] 2020-06-22 21:50
I think this issue is duplicate of https://github.com/apache/incubator-mxnet/issues/18429 and can be closed?

**Comment by ys2843** [comment] 2020-06-22 22:59
@sandeep-krishnamurthy The project for merging beta website need to be rediscussed due to this change.

**Comment by ys2843** [comment] 2020-07-31 21:03
This issue can be closed, all language bindings are removed from master website.

**Closed** 2020-07-31 21:05 UTC
Labels: Bug, Website
