### ISSUE TITLE
Failure in unittest test_operator.py:test_reduce for some seeds

### ISSUE THREAD

**Issue by ptrendx** [apache/incubator-mxnet#8780] opened 2017-11-23 00:01 UTC
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Setting both MXNet and Numpy seeds to 2098177962 at the beginning of `test_reduce`  in `tests/python/unittest/test_operator.py` results in failure - the difference between tensors expected to be the same is over 0.5, so it is not an issue with test tolerance.

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
89d2a71

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
```
test_repro.test_reduce ... FAIL

======================================================================
FAIL: test_repro.test_reduce
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/mxnet/tests/python/unittest/test_operator.py", line 1578, in test_reduce
    mx.symbol.max)
  File "/opt/mxnet/tests/python/unittest/test_operator.py", line 1553, in test_reduce_inner
    assert equal_backward
AssertionError: 
```

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce

1. put 
```
mx.random.seed(2098177962)
np.random.seed(2098177962)
```
at the beginning of `test_reduce` function in `tests/python/unittest/test_operator.py`
2. `nosetests --verbose test_operator.py:test_reduce`

## What have you tried to solve it?

1. Tried different seeds, could not get it to fail for ~100 tries.

**Comment by bhavinthaker** [comment] 2018-03-10 00:38
Proposed labels: "Flaky", "Test", "Python"

**Comment by Roshrini** [comment] 2018-06-22 20:10
@marcoabreu @KellenSunderland I ran this test for 10000 times but couldn't reproduce the issue. 
Did this test fail recently as well?

**Comment by marcoabreu** [comment] 2018-07-13 09:14
Not as far as I can tell. Closing

**Closed by marcoabreu** 2018-07-13 09:14 UTC
Labels: Flaky, Python, Test
