### ISSUE TITLE
Mac build from source script validation fails

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#9949] opened 2018-03-01 22:06 UTC
## Description
The installation instructions for Mac, refer you to this script:
https://raw.githubusercontent.com/dmlc/mxnet/master/setup-utils/install-mxnet-osx-python.sh

If "fails" at the end during a test.

## Environment info (Required)

macOS 10.12.6 (Sierra)

MXNet commit hash:
I chose to use the v1.1.0 tag for the install, so this is:
07a83a0325a3d782513a04f47d711710972cb144

## Error Message:
```
Finished processing dependencies for mxnet==1.1.0
END: Install MXNet package for Python
########################################################################
 
BEGIN: Test MXNet
1,2c1,2
< [[2. 2. 2.]
<  [2. 2. 2.]]
---
> [[ 2.  2.  2.]
>  [ 2.  2.  2.]]
 
ERROR: Following files differ: mxnet_test.log mxnet_test.expected
ERROR: MXNet test failed
END: Test MXNet
 
:-(
```
Also, some errors when running Python:
```
8c8590217d260a:mxnet markhama$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
dyld: warning, LC_RPATH ${ORIGIN} in /Users/markhama/Library/Python/2.7/lib/python/site-packages/mxnet/libmxnet.so being ignored in restricted program because it is a relative path
>>> quit()
```

## Steps to reproduce

1. Set env var: `export MXNET_TAG=1.1.0`
2. Run script: `https://raw.githubusercontent.com/dmlc/mxnet/master/setup-utils/install-mxnet-osx-python.sh`

## Comments

I reran this script using environments and a Python3 setup. It passed the test, and I don't get weird errors when doing `import mxnet`. Note that doing a vanilla Mac install, it tries to bind to Mac's default 2.7.10 Python... and apparently fails.

**Comment by gautamkmr** [comment] 2018-04-04 00:24
I am not able to reproduce this issue 
I do have python 2.7.10.

/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/msvc.py:309: DeprecationWarning: invalid escape sequence \c
/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py:331: UserWarning: Normalizing '2018.01.18' to '2018.1.18'
creating /anaconda/lib/python3.6/site-packages/certifi-2018.1.18-py3.6.egg
Extracting certifi-2018.1.18-py3.6.egg to /anaconda/lib/python3.6/site-packages
Adding certifi 2018.1.18 to easy-install.pth file

Installed /anaconda/lib/python3.6/site-packages/certifi-2018.1.18-py3.6.egg
Searching for numpy==1.12.1
Best match: numpy 1.12.1
Adding numpy 1.12.1 to easy-install.pth file

Using /anaconda/lib/python3.6/site-packages
Searching for urllib3==1.21.1
Best match: urllib3 1.21.1
Adding urllib3 1.21.1 to easy-install.pth file

Using /anaconda/lib/python3.6/site-packages
Searching for idna==2.5
Best match: idna 2.5
Adding idna 2.5 to easy-install.pth file

Using /anaconda/lib/python3.6/site-packages
Searching for chardet==3.0.3
Best match: chardet 3.0.3
Adding chardet 3.0.3 to easy-install.pth file
Installing chardetect script to /anaconda/bin

Using /anaconda/lib/python3.6/site-packages
Finished processing dependencies for mxnet==1.1.0
END: Install MXNet package for Python
########################################################################
 
BEGIN: Test MXNet
 
SUCCESS: MXNet test passed
SUCCESS: MXNet is successfully installed and works fine!
SUCCESS: MXNet Version is: 1.1.0
END: Test MXNet
:-)
 
FYI : You can fine-tune MXNet run-time behavior using environment variables described at:
      http://mxnet.io/faq/env_var.html
 
NEXT: Try the tutorials at: http://mxnet.io/tutorials
 
########################################################################
 

f45c89a20de7:tmp gauta$ python 
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by gautamkmr** [comment] 2018-04-04 07:33
I tried using the install-mxnet-osx-python.sh script, it did work well with python3.6 however with python-2.7.10 I guess I have not reached upto your step but failed due to some missing dependency. 

I will give a shot with the osx_setup.md 

with Python2.7.10 it failed during installation of Numpy.

Searching for numpy>=1.8.2,<=1.13.3
Reading https://pypi.python.org/simple/numpy/
Best match: numpy 1.13.3
Downloading https://pypi.python.org/packages/bf/2d/005e45738ab07a26e621c9c12dc97381f372e06678adf7dc3356a69b5960/numpy-1.13.3.zip#md5=300a6f0528122128ac07c6deb5c95917
Processing numpy-1.13.3.zip
Writing /tmp/easy_install-R1dTVi/numpy-1.13.3/setup.cfg
Running numpy-1.13.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-R1dTVi/numpy-1.13.3/egg-dist-tmp-He2mV1
/tmp/easy_install-R1dTVi/numpy-1.13.3/setup.py:367: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
Warning: distutils distribution has been initialized, it may be too late to add a subpackage compatTraceback (most recent call last):
  File "setup.py", line 109, in <module>
    **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 374, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 590, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 641, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 687, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 568, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 806, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 818, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 609, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 639, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 825, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1031, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1016, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 120, in run
    return func()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 392, in <module>
    
  File "setup.py", line 384, in setup_package
    
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 166, in configuration
    
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 10, in configuration
    #
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 847, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "/private/tmp/easy_install-R1dTVi/numpy-1.13.3/numpy/core/setup.py", line 13, in <module>
    # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
ImportError: No module named _build_utils.apple_accelerate
 
ERROR: Return value non-zero for: sudo python setup.py install

**Comment by gautamkmr** [comment] 2018-04-05 03:57
Looks like 1.0.0. was fine 

PR which tried to add the numpy version but looks like python-2.7.10 is too old for numpy version 1.8.2. 

https://github.com/apache/incubator-mxnet/commit/17427d1dc949cb921a190151bc8de74ed50504ef#diff-8cf6167d58ce775a08acafcfe6f40966R31

**Comment by gautamkmr** [comment] 2018-04-05 20:43
1. Verified that it works fine on 2.7.14 but not 2.7.10

**Comment by gautamkmr** [comment] 2018-04-05 20:53
By default all the mac os comes with either python2.7.14 or python3+. 

Probably we can change the release doc with a statement saying, we need python 2.7.14+

**Comment by gautamkmr** [comment] 2018-04-05 23:01
So MAC OS system python-2.7.10 comes with default numpy version 1.8.0.rc1 
We have to change the numpy lower bound version something smaller than 1.8.0.rc1

**Comment by gautamkmr** [comment] 2018-05-14 19:03
Dev decided to have user upgrade the python rather than using the old version. 
Please see the discussion here https://github.com/apache/incubator-mxnet/pull/10445
Feel free to close this issue.

**Comment by bhavinthaker** [comment] 2018-05-14 21:02
@sandeep-krishnamurthy @eric-haibin-lin  Could one of you please close this issue?

**Closed** 2018-05-14 21:36 UTC
Labels: Installation, Test
