### ISSUE TITLE
Flaky test(scala): test_arange

### ISSUE THREAD

**Issue by anirudh2290** [apache/incubator-mxnet#10387] opened 2018-04-03 18:53 UTC
```
*** 1 TEST FAILED ***

[INFO] ------------------------------------------------------------------------

[INFO] Reactor Summary:

[INFO] 

[INFO] MXNet Scala Package - Parent ....................... SUCCESS [  2.834 s]

[INFO] MXNet Scala Package - Initializer .................. SUCCESS [  0.947 s]

[INFO] MXNet Scala Package - Initializer Native Parent .... SUCCESS [  0.497 s]

[INFO] MXNet Scala Package - Initializer Native Linux-x86_64 SUCCESS [ 11.852 s]

[INFO] MXNet Scala Package - Macros ....................... SUCCESS [  0.728 s]

[INFO] MXNet Scala Package - Core ......................... FAILURE [ 48.518 s]

[INFO] MXNet Scala Package - Native Parent ................ SKIPPED

[INFO] MXNet Scala Package - Native Linux-x86_64 CPU-only . SKIPPED

[INFO] MXNet Scala Package - Inference .................... SKIPPED

[INFO] MXNet Scala Package - Examples ..................... SKIPPED

[INFO] MXNet Scala Package - Spark ML ..................... SKIPPED

[INFO] MXNet Scala Package - Full Parent .................. SKIPPED

[INFO] MXNet Scala Package - Full Linux-x86_64 CPU-only ... SKIPPED

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 01:05 min

[INFO] Finished at: 2018-04-02T22:07:11+00:00

[INFO] Final Memory: 54M/2143M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project mxnet-core_2.11: There are test failures -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR] 

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

[ERROR] 

[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :mxnet-core_2.11

Makefile:543: recipe for target 'scalatest' failed

make: *** [scalatest] Error 1

build.py: 2018-04-02 22:07:12,537 Running of command in container failed: docker run --rm -v /home/jenkins_slave/workspace/ut-scala-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-scala-cpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_cpu_scala

build.py: 2018-04-02 22:07:12,537 You can try to get into the container by using the following command: docker run --rm -v /home/jenkins_slave/workspace/ut-scala-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-scala-cpu/build:/work/build -u 1001:1001 -ti --entrypoint bash mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_cpu_scala

Traceback (most recent call last):

  File "ci/build.py", line 179, in <module>

    sys.exit(main())

  File "ci/build.py", line 159, in main

    container_run(platform, docker_binary, command)

  File "ci/build.py", line 110, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'docker run --rm -v /home/jenkins_slave/workspace/ut-scala-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-scala-cpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_cpu_scala' returned non-zero exit status 2

script returned exit code 1
```

Please see: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10374/1/pipeline/

**Comment by ThomasDelteil** [comment] 2018-04-11 01:45
Happened to me too:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10495/1/pipeline/597

**Comment by marcoabreu** [comment] 2018-06-27 23:09
Not scala, but still: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1053/pipeline/

**Comment by haojin2** [comment] 2018-07-13 04:38
@marcoabreu Have we observed more occurrence of this?

**Comment by haojin2** [comment] 2018-07-13 05:28
Plus, seems like a duplicate issue for #8834

**Comment by marcoabreu** [comment] 2018-07-13 09:12
I don't know. Let's come back when we see it again.

Duplicate of https://github.com/apache/incubator-mxnet/issues/8834

**Closed by marcoabreu** 2018-07-13 09:12 UTC
Labels: Flaky, Scala, Test

**Comment by haojin2** [comment] 2019-03-11 21:04
Seems to happen again on my PR: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14359/7/pipeline. @marcoabreu @lanking520

**Comment by lanking520** [comment] 2019-03-11 21:20
This is something different, with strange value came from the op
