### ISSUE TITLE
How to maximize one loss function and minimize another one?

### ISSUE THREAD

**Issue by lilhope** [apache/incubator-mxnet#8037] opened 2017-09-26 05:58 UTC
I want to maximize a dice coefficient and minimize the smooth_l1_loss at the same time,  I tried multiple `-1.` to the dice coefficient but seems it doesn't work.

**Comment by kevinthesun** [comment] 2017-09-27 07:11
Provide a simple example? Are you combining this two losses into a single one? Or these two losses are bind with different models and you want something similar to adversarial network?

**Comment by szha** [comment] 2017-12-27 12:26
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by b0noI** [comment] 2018-03-20 21:34
Suggested tags: "Question", "HowTo"

**Comment by ThomasDelteil** [comment] 2018-07-04 22:34
@lilhope If the issue is still current, could you provide an example code and post a follow-up post to https://discuss.mxnet.io referencing this issue? Thanks!

@sandeep-krishnamurthy can you please close the issue? Thanks!

**Closed** 2018-07-05 07:07 UTC
Labels: HowTo, Question
