### ISSUE TITLE
A couple of issues in benchmark_score.py

### ISSUE THREAD

**Issue by juliensimon** [apache/incubator-mxnet#8969] opened 2017-12-06 18:16 UTC
Here are a couple of issues in incubator-mxnet/example/image-classification/benchmark_score.py.

Both prevent the script from running.

--> Issue #1
def get_symbol(network, batch_size):
    image_shape = (3,299,299) if network == 'inception-v3' else (3,224,224)
    num_layers = 0

get_symbol() for vgg16 doesn't accept a zero value for the number of layers.
Quick fix: insert this after "num_layers = 0"
if network=='vgg':
    num_layers=16
Or use the same solution as for resnet (split and extract number of layers)

--> Issue #2
devs = [mx.gpu(0)] if len(get_gpus()) > 0 else []

get_gpus() relies on nvidia-smi which is not installed on machines that don't have GPUs (say, c4 instances on AWS).

**Comment by gautamkmr** [comment] 2018-03-10 00:06
Please add labels: "Example", "Need Triage"

**Comment by mbaijal** [comment] 2018-03-20 21:33
Please remove the label 'Need Triage'

**Comment by szha** [comment] 2018-03-24 19:55
@gautamkmr @sandeep-krishnamurthy please refrain from manually adding "Need Triage" label while triaging. Thanks.

**Comment by thomelane** [comment] 2018-08-15 23:40
@juliensimon just tested this out and I don't hit either of these issues.

With regards to Issue 1, there is logic to extract the number of layers from the network string for VGG (as with ResNet).

```
if 'vgg' in network:
    num_layers = int(network.split('-')[1])
```

And for Issue 2, I tried `get_gpus()` on a CPU machine and due to the `except OSError` exception handling the function just returns an empty list which is expected behaviour of this function. In `benchmark_score.py` the cpu context is added.

So I think something must have been fixed since you filed this issue. But please do reopen if you're still hitting these issues.

**Comment by thomelane** [comment] 2018-08-15 23:40
@indhub @yzhliu would appreciate if you could close this issue, many thanks!

**Closed** 2018-08-16 02:08 UTC
Labels: Example
