### ISSUE TITLE
nnvm any.h check_type failed

### ISSUE THREAD

**Issue by feiyulv** [apache/incubator-mxnet#4116] opened 2016-12-06 08:09 UTC
nnvm branch failed when training seq2seq task, following is the error info
```
any.h:261: Check failed: type_  != nullptr The any container is empty  requested=N5mxnet2op15ReduceAxesParamE
```
The strange thing is when i setting engine type to naive, nnvm will be ok.

**Comment by piiswrong** [comment] 2016-12-06 08:10
@tqchen

**Comment by sxjscience** [comment] 2016-12-06 08:44
I think I've met similar errors when trying to run the FasterRCNN (NaiveEngine will trigger no error but the default engine will). It will appear after training the network for several steps. Previously I thought that might be related to some problems in CustomOP. However, the cyclic dependency problem should have been solved, so the problem may be related to something else.

**Comment by feiyulv** [comment] 2016-12-06 09:34
@piiswrong sorry,  it is a little difficult  to access the code since it is in intranet. I have debugged the program, it  is caused by the broadcast operator in backward 
https://github.com/dmlc/mxnet/blob/nnvm/src/operator/tensor/broadcast_reduce_op.h#382
```
  const ReduceAxesParam& param = nnvm::get<ReduceAxesParam>(attrs.parsed);
```
But I don't understand why engine type should affect it

**Comment by piiswrong** [comment] 2016-12-06 18:12
@feiyulv Could you make a minimal reproducing example? What layers did you use?

**Comment by piiswrong** [comment] 2016-12-06 18:38
I can't reproduce this bug with FasterRCNN.

**Comment by tqchen** [comment] 2016-12-06 23:23
seems was due to the attr parser did not get invoked (and the attr.parsed) remains empty somehow.

**Comment by tqchen** [comment] 2016-12-06 23:35
here is the related code https://github.com/dmlc/mxnet/blob/nnvm/src/operator/operator_common.h#L149

In theory, when MakeGradNode is called, the attribute parser will get called and set the parsed to be the result.

**Comment by feiyulv** [comment] 2016-12-07 09:25
It seems all the operator which calls nnvm::get() will fail in this case. Currently I  avoid this problem by replacing the broadcast_reduce_op and elemwise_binary_scalar_op with the master version.

**Comment by piiswrong** [comment] 2016-12-07 20:01
@tqchen Is any thread safe? Possible race conditions?

**Comment by piiswrong** [comment] 2016-12-08 07:35
@feiyulv Could you at least post your symbol? There is too little information to debug

**Comment by tqchen** [comment] 2016-12-08 07:49
@feiyulv How frequent can you reproduce this problem? Does it happens indeterministically or at every time when the backward get hitted?

**Comment by feiyulv** [comment] 2016-12-08 09:31
@piiswrong @tqchen 
The problem reproduce after several batches as @sxjscience described.
It seems  it is caused by my modification of executor_manager.py I construct a new executor for each batch, and the old one will be deconstructed, as follows:
https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor_manager.py#L399. 
```
        if self.sym_gen is not None:
            key = data_batch.bucket_key
            # create new bucket entry
            symbol = self.sym_gen(key)
            execgrp = DataParallelExecutorGroup(symbol, self.arg_names,
                                                self.param_names, self.ctx,
                                                self.slices, data_batch,
                                                shared_group=self.execgrp)
            # delay the deconstruct 
            # self.prev_execgrp = self.curr_execgrp
            self.curr_execgrp = execgrp_bucket
```
However when I remove the comment of ` self.prev_execgrp = self.curr_execgrp`, it will be ok.

**Comment by piiswrong** [comment] 2016-12-09 19:33
@tqchen I think this is the same problem as before. Executor can get destructed before ops pushed by the executor is finished

**Comment by tqchen** [comment] 2016-12-09 19:48
@piiswrong I think you are right on this. This can be fixed by changing https://github.com/dmlc/mxnet/blob/nnvm/src/executor/attach_op_execs_pass.cc#L156 to not use reference, or keep reference to the shared_ptr of the corresponding node

**Comment by piiswrong** [comment] 2016-12-09 20:05
is it possible to fix it once and for all by making executor destruction async and depend on the operators it pushed?

**Comment by tqchen** [comment] 2016-12-09 20:18
there is no dependency for operations, but instead only on the variables. It will need a destruction depends on all the variables in the executor, and make the data structure internal.

Making the pushed operator self-conatained and store things by value is a finer grained approach to solve this problem

**Comment by piiswrong** [comment] 2016-12-12 20:20
@feiyulv Could you confirm if this https://github.com/dmlc/mxnet/pull/4208 fixes your problem?

**Comment by yajiedesign** [comment] 2017-09-28 07:15
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Closed by yajiedesign** 2017-09-28 07:15 UTC
