### ISSUE TITLE
train faster-rcnn use two gpus, error occured like this

### ISSUE THREAD

**Issue by Trangle** [apache/incubator-mxnet#3836] opened 2016-11-15 15:36 UTC
C:\WinPython\python-2.7.10.amd64\python.exe D:/MyCoding/DeepLearning/test_example/mxnet/example/rcnn/train_end2end.py --root_path H:\data\faster_rcnn --devkit_path H:\data\faster_rcnn\VOCdevkit --frequent 50 --kv_store local --prefix H:\data\faster_rcnn\model\faster-rcnn --pretrained H:\data\faster_rcnn\model\vgg16 --load-epoch 1
INFO:root:Namespace(devkit_path='H:\\data\\faster_rcnn\\VOCdevkit', factor_step=50000, frequent=50, gpu_ids='1,0', image_set='trainval', kv_store='local', load_epoch=1, lr=0.001, mom=0.9, monitor=False, no_flip=False, num_classes=21, num_epoch=10, prefix='H:\\data\\faster_rcnn\\model\\faster-rcnn', pretrained='H:\\data\\faster_rcnn\\model\\vgg16', resume=False, root_path='H:\\data\\faster_rcnn', test_image_set='test', wd=0.0005, work_load_list=None, year='2007')
INFO:root:########## TRAIN FASTER-RCNN WITH APPROXIMATE JOINT END2END #############
('providing maximum shape', [('data', (2, 3, 1000, 1000))], [('label', (1L, 34596L)), ('bbox_target', (1L, 36L, 62L, 62L)), ('bbox_inside_weight', (1L, 36L, 62L, 62L)), ('bbox_outside_weight', (1L, 36L, 62L, 62L)), ('gt_boxes', (2, 500))])
voc_2007_trainval gt roidb loaded from H:\data\faster_rcnn\cache\voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
Traceback (most recent call last):
  File "D:/MyCoding/DeepLearning/test_example/mxnet/example/rcnn/train_end2end.py", line 178, in <module>
    args.work_load_list, args.resume, not args.no_flip, args.factor_step)
  File "D:/MyCoding/DeepLearning/test_example/mxnet/example/rcnn/train_end2end.py", line 125, in end2end_train
    arg_params=args, aux_params=auxs, begin_epoch=begin_epoch, num_epoch=num_epoch)
  File "C:\WinPython\python-2.7.10.amd64\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\module\base_module.py", line 338, in fit
    for_training=True, force_rebind=force_rebind)
  File "D:\MyCoding\DeepLearning\test_example\mxnet\example\rcnn\rcnn\module.py", line 137, in bind
    force_rebind=False, shared_module=None)
  File "C:\WinPython\python-2.7.10.amd64\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\module\module.py", line 282, in bind
    grad_req=grad_req, input_types=input_types)
  File "C:\WinPython\python-2.7.10.amd64\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\module\executor_group.py", line 170, in __init__
    self.label_layouts = self.decide_slices(label_shapes)
  File "C:\WinPython\python-2.7.10.amd64\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\module\executor_group.py", line 196, in decide_slices
    + ("%s has shape %s" % (name, shape)))
AssertionError: all data must have the same batch size: batch_size = 2, but label has shape (1L, 34596L)

Process finished with exit code 1

training_end2end

**Comment by piiswrong** [comment] 2016-11-15 18:32
@precedenceguo

**Comment by precedenceguo** [comment] 2016-11-16 06:04
Yes, the e2e code in the example does not support multiple gpu training yet. We are working on that but you are welcome to contribute.

**Comment by tornadomeet** [comment] 2016-11-16 06:44
but i 'm always using multi-gpus for  e2e training.  @Trangle do you change the training symbol?

**Comment by Trangle** [comment] 2016-11-16 08:44
@tornadomeet symbol was original version, and i changed the max_label_shape list，it works in multi-gpu，but really slower than just one device

**Comment by hanshumin001** [comment] 2016-11-16 10:17
@tornadomeet , I  encountered the same problem and had no change for the source code.  I want to kown how you run the program using mutil-GPUs.

**Comment by precedenceguo** [comment] 2016-11-17 03:04
@hanshumin001 Maybe issues appear in some commits. I checked out the latest master and 2-gpu training works.

**Comment by KeyKy** [comment] 2016-11-22 08:18
@precedenceguo do you mean e2e version?

**Comment by KeyKy** [comment] 2016-11-22 09:15
@precedenceguo I try the latest master, but e2e 2-gpu training can't work, AssertionError: all data must have the same batch size: batch_size = 2, but label has shape (1, 34596)

**Comment by precedenceguo** [comment] 2016-11-22 10:27
tried again, still works. are we talking about the same https://github.com/dmlc/mxnet/tree/master/example/rcnn/train_end2end.py?

**Comment by KeyKy** [comment] 2016-11-22 13:30
@precedenceguo I copy your https://github.com/dmlc/mxnet/tree/master/example/rcnn/train_end2end.py, but still have the problem, i use the latest mxnet and i clone it today.

**Comment by precedenceguo** [comment] 2016-11-23 06:37
@tornadomeet Hi, I remember I once saw "AssertionError: all data must have the same batch size: batch_size = 2, but label has shape (1L, 34596L)" but now I cannot reproduce this error as @Trangle or @KeyKy found in current mxnet. Now Trangle seems to have fixed it using "max_label_shape" but did not give details. Can you verify again?

**Comment by KeyKy** [comment] 2016-11-24 00:58
@precedenceguo i also fix by set the batch size of "max_label_shape" to 2. I see the code max_label_shape is used to decide slice.

**Comment by precedenceguo** [comment] 2016-11-24 03:05
OK I know how to reproduce the problem. Module API has changed since tornadomeet's pr several months ago. The fix is indeed to change the batch size of max_label_shape.

**Comment by yajiedesign** [comment] 2017-09-28 07:11
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Closed by yajiedesign** 2017-09-28 07:11 UTC
