### ISSUE TITLE
[website] Training with Data from S3 article broken link

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#16444] opened 2019-10-11 17:26 UTC
## Description
Broken link on:
https://mxnet.apache.org/api/python/docs/tutorials/deploy/run-on-aws/index.html
This page tries to link to:
https://mxnet.apache.org/versions/master/faq/s3_integration.html

**Comment by ys2843** [comment] 2020-05-28 22:22
It should be fixed. Can't reproduce any more.

**Closed** 2020-06-24 23:13 UTC
Labels: Website
