### ISSUE TITLE
[BUG] MNIST LeNet forward fails on 65061dc

### ISSUE THREAD

**Issue by zhanghang1989** [apache/incubator-mxnet#10976] opened 2018-05-16 17:48 UTC
MNIST LeNet forward fails on master branch. @eric-haibin-lin mentioned that it may be related to this PR https://github.com/apache/incubator-mxnet/pull/10911
```python
import mxnet as mx
from mxnet.gluon import nn, Block
net = nn.HybridSequential()
with net.name_scope():
        net.add(nn.Conv2D(in_channels=1, channels=20, kernel_size=5))
        net.add(nn.Activation('relu'))
        net.add(nn.MaxPool2D(pool_size=2, strides=2))
        net.add(nn.Conv2D(in_channels=20, channels=50, kernel_size=5))
        net.add(nn.Activation('relu'))
        net.add(nn.MaxPool2D(pool_size=2, strides=2))
        # The Flatten layer collapses all axis, except the first one, into one axis.
        net.add(nn.Flatten())
        net.add(nn.Dense(512,in_units=800))
        net.add(nn.Activation('relu'))
        net.add(nn.Dense(10, in_units=512))
net.collect_params().initialize()
x = mx.random.uniform(shape=(8, 1, 28, 28))
net(x)
```
Got this error
```bash
Segmentation fault (core dumped)
```

**Comment by zhanghang1989** [comment] 2018-05-16 18:18
Failed on commit 65061dc93710afce92edfe548aa3352473da3cdb,
but seems fixed on master now.

**Comment by srochel** [comment] 2018-09-02 21:11
@mxnet-label-bot: ["Good First Issue"]

**Comment by vandanavk** [comment] 2018-09-25 04:58
@sandeep-krishnamurthy Please change the label to Good First Issue. 

Looks like the issue is not reproducible on a more recent codebase.

**Comment by vrakesh** [comment] 2018-10-08 18:05
@vandanavk if the issue is not reproducible can this be closed

**Comment by sandeep-krishnamurthy** [comment] 2018-10-09 04:42
resolving, issue is not reproducible

**Closed by sandeep-krishnamurthy** 2018-10-09 04:42 UTC
Labels: Good First Issue
