### ISSUE TITLE
rcnn example throws CUDNN_STATUS_BAD_PARAM when running under cudnn 6.0

### ISSUE THREAD

**Issue by xioryu** [apache/incubator-mxnet#11240] opened 2018-06-12 03:24 UTC
After I update the mxnet version from 1.1.0 to 1.2.0 and build the repository with CUDA 8.0.61 and cudnn 6.0, the rcnn training throws the following error when evaluating the rpn accuracy.

check failed: e == cuDNN: CUDNN_STATUS_SUCCESS(3 vs. 0) cuDNN: CUDNN_STATUS_BAD_PARAM

The error occurred when executing the following code in example/rcnn/rcnn/core/metric.py:
`pred_label = mx.ndarray.argmax_channel(pred).asnumpy().astype('int32')`
Any ideas to address this without disabling cudnn or rolling to a former version?

**Comment by kalyc** [comment] 2018-06-12 18:17
Thanks for submitting this issue @xioryu You could post this on discuss.mxnet.io for further details on usage of mxnet.

**Comment by kalyc** [comment] 2018-06-15 18:57
@nswamy could you add label "Question", "CUDA" to this?

**Comment by vrakesh** [comment] 2018-06-18 23:16
@nswamy  requesting a label for "Question", or CUDA to this issue

**Comment by ijkguo** [comment] 2018-07-13 01:08
It was probably related to old SoftmaxActivation layer. Now changed to `mx.sym.softmax` in https://github.com/apache/incubator-mxnet/pull/11373.

**Comment by thomelane** [comment] 2018-08-17 21:01
@xioryu are you able to provide some sample code that reproduces this issue? many thanks!

It's not possible to diagnose from just knowing the error occurred on line `pred_label = mx.ndarray.argmax_channel(pred).asnumpy().astype('int32')`. I'd expect any fatal error in the network to appear when this line is run, just because `.asnumpy()` blocks and waits for all the async operations to complete (i.e. waits for the network computation to complete).

**Comment by xioryu** [comment] 2018-08-20 14:34
@thomelane The new simplified repo is OK.

**Comment by ijkguo** [comment] 2018-08-20 18:16
The cause of this issue is operator SoftmaxActivation, used in the old complex rcnn example. Two fixes were made and either fixed this issue:
- https://github.com/apache/incubator-mxnet/pull/10918 fixed SoftmaxActivation cudnn bug.
- https://github.com/apache/incubator-mxnet/pull/11373 removed any usage of SoftmaxActivation.

**Comment by thomelane** [comment] 2018-08-20 21:12
@xioryu @ijkguo great, and thanks for confirming!

@sandeep-krishnamurthy good to close this ticket now, cheers.

**Closed** 2018-08-20 21:44 UTC
Labels: CUDA, Example, Question
