### ISSUE TITLE
Question about Custom Iterator?

### ISSUE THREAD

**Issue by danache** [apache/incubator-mxnet#8221] opened 2017-10-11 08:30 UTC
I try to create my own Custom data Iterator.
My input is image and my label is 14 heat map(a [14,64,64] matrix).
And in my iter class,I use mx.io.ImageRecordIter to generate iter, and change the label as I want.
So,with the batchsize is 2, when I print the provide_data and  provide_label it looks like this:
```
[DataDesc[data,(2, 3, 256, 256),<class 'numpy.float32'>,NCHW]]
[('label', (2, 14, 64, 64))]
```
but when I 
try to bind the value, I got this error
```
mod.bind(data_shapes=train_iter.provide_data, label_shapes=train_iter.provide_label)

```
```
Error in operator conv1: [16:28:21] src/operator/./convolution-inl.h:446: Check failed: dshp.ndim() == 3U (4 vs. 3) Input data should be 3D in batch-num_filter-x
```
I have no idea where I have mistakes in my iter class, Thank you !

**Comment by chinakook** [comment] 2017-10-12 01:05
Maybe your network definition has something wrong.

**Comment by szha** [comment] 2018-01-11 12:26
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by lanking520** [comment] 2018-06-11 00:34
Hi @danache , are you still facing the same issue now?

**Comment by anirudhacharya** [comment] 2018-06-25 06:20
@danache can you please provide a reproducible example.

@eric-haibin-lin please label this - "Question", "Pending Requester Info"

**Comment by yzhliu** [comment] 2018-07-30 23:41
Since we don't receive response from the requester for a long time, I close it for now. @danache Feel free to reopen if you're still facing the problem.

**Closed by yzhliu** 2018-07-30 23:41 UTC
Labels: Pending Requester Info, Question
