### ISSUE TITLE
flaky test: test_operator.test_depthwise_convolution

### ISSUE THREAD

**Issue by mseth10** [apache/incubator-mxnet#14052] opened 2019-02-02 00:19 UTC
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14016/4/pipeline/

ERROR: test_operator.test_depthwise_convolution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/mxnet/tests/python/unittest/common.py", line 173, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/unittest/test_operator.py", line 1676, in test_depthwise_convolution
    np.testing.assert_allclose(arr1.asnumpy(), arr2.asnumpy(), rtol=1e-3, atol=1e-3)
  File "/work/mxnet/python/mxnet/ndarray/ndarray.py", line 1995, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/work/mxnet/python/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
MXNetError: [01:40:38] src/operator/nn/mkldnn/mkldnn_base.cc:576: Check failed: similar 

NOTE: The test fails on CPU when MKLDNN is enabled and passes when MKL-DNN is disabled. So, the issue is mostly due to MKL-DNN.

**Comment by ZhennanQin** [comment] 2019-02-03 02:12
@mseth10, Thanks for reporting this. Confirmed it's caused by mkldnn bug. The fix is already in mkldnn master, but not available in its latest release. We will upgrade mkldnn when its next release comes out.

**Comment by mseth10** [comment] 2019-02-25 18:52
@ZhennanQin Thanks for confirming it's an MKLDNN bug. Good to know that it's fixed. Can you also give an ETA on when the next release containing the fix be rolled out?

**Comment by pengzhao-intel** [comment] 2019-08-04 04:30
Resolved so closing.

**Closed** 2019-08-04 04:30 UTC
Labels: Flaky, MKLDNN, Test
