### ISSUE TITLE
test_sparse_ndarray.test_sparse_nd_save_load has fixed seed that can mask flakiness

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#11741] opened 2018-07-13 05:37 UTC
The unit test in title have been using fixed seed to mask flakiness. Suggested action:
1. Evaluate whether the test is flaky without fixed seed. If not, remove seed. Else move to 2
2. If test is flaky, determine whether it's an actual uncaught edge case. If so, fix the operator. Else move to 3
3. If numerical instability is inevitable, adjust tolerance level appropriately.

**Comment by apeforest** [comment] 2018-07-13 16:24
@szha Thanks for filing this issue. We will investigate these Flaky tests.

**Comment by kalyc** [comment] 2018-07-27 22:46
Unable to reproduce issue with 10000 runs, opened PR - https://github.com/apache/incubator-mxnet/pull/11920

**Comment by kalyc** [comment] 2018-07-27 23:09
For reference, initially seed was set to 0

**Comment by kalyc** [comment] 2018-07-30 16:42
PR has been merged. @szha could you please close the issue?

**Closed** 2018-07-30 16:49 UTC
Labels: Flaky, Test
