### ISSUE TITLE
asnumpy() of NDArray @cpu  halted

### ISSUE THREAD

**Issue by nopattern** [apache/incubator-mxnet#3724] opened 2016-11-04 08:12 UTC
I am running example/rcnn/demo.py . It succedded on gpu. Then I try to run whole program on cpu. But the program halted at line:
        `scores = executor.output_dict['cls_prob_reshape_output'].asnumpy()[0]`
        in file rcnn/detector.py.
    then I modified the line to :
       
         ```
scores_raw = executor.output_dict['cls_prob_reshape_output']
         scores = scores_raw.asnumpy()[0]
```
it still halted at  scores_raw.asnumpy().
     I have made sample  code as following:
     
      ```
mx_x = mx.nd.ones((1,300,21))
      np_x = mx_x.asnumpy()[0] 
```

But it succeed. so what happens? does asnumpy()  has some bug?

**Comment by nopattern** [comment] 2016-11-04 09:28
By Debuging  into the code , I found the code halted at 
       check_call(_LIB.MXNDArraySyncCopyToCPU(
            self.handle,
            data.ctypes.data_as(ctypes.c_void_p),
            ctypes.c_size_t(data.size)))
     in file ndarray.py.

**Comment by zihaolucky** [comment] 2016-11-04 12:19
I have same issues on https://github.com/dmlc/mxnet/issues/3684 also at `_LIB.MXNDArraySyncCopyToCPU `

**Comment by piiswrong** [comment] 2016-11-04 17:15
rcnn is a big model. You need to wait for 100x the GPU execution time

**Comment by nopattern** [comment] 2016-11-04 23:33
The copy size is about 300*21*4=24k, I waited more than half an hour...

**Comment by piiswrong** [comment] 2016-11-05 00:01
@precedenceguo

**Comment by precedenceguo** [comment] 2016-11-06 03:22
asnumpy awaits engine for the actual computation.
Is you machine conducting heavy calculation while stuck at this line? If so, please use mxnet-notebook/predict_with_pretrained_model to test an image and see how long that takes?

**Comment by nopattern** [comment] 2016-11-06 07:24
Thank you .I checked the cpu status and it utilize almost 0 . I will try predict_with_pretrained_model 。

**Comment by zihaolucky** [comment] 2016-11-07 02:00
@javelinjs I guess the `toArray` method in Scala is same as `asnumpy` in python.

**Comment by nopattern** [comment] 2016-11-07 03:16
I moved from mx.cpu(0) to mx.cpu(1) and the problem solved . It seems the bug is about thread synchronization.

**Comment by zihaolucky** [comment] 2016-11-07 05:56
@nopattern Have you tried to call predict in multi-thread?

**Comment by nopattern** [comment] 2016-11-07 07:19
How to ?

**Comment by zihaolucky** [comment] 2016-11-07 12:37
@nopattern Python multi-thread, call `model.predict` and `asnumpy`. Or you could also use `waitToRead` after `asnumpy` in single thread.

**Comment by cloudhan** [comment] 2017-04-17 16:14
I also met this problem.
I tried to bind two executors **with partially shared parameters**. If I use `exe1.outputs[0].asnumpy()` in the training iteration (to inspect whether there is any problem with the training setup), the training process freeze. If I comment out all `asnumpy()` lines, training goes smoothly. If I bind without any parameter shared, then there is no problem with `asnumpy()` call

**Comment by precedenceguo** [comment] 2017-04-20 03:20
I though this issue is fixed in collection #4713 and pr #4528.

**Comment by maxenceliu** [comment] 2017-08-17 02:36
@zihaolucky Hi, How do you resolve this problem? I met the same occasion. Each time I call NDArray.toArray in scala, it will block at least 10 seconds when I run this on a cpu-Server with Centos. however, in my Macbook cpu only, its time cost can be noticed!

**Comment by zihaolucky** [comment] 2017-08-17 02:55
@maxenceliu Unfortunately, I haven't resolve this.

**Comment by maxenceliu** [comment] 2017-08-17 02:58
@zihaolucky So, you give up to deploy mxnet  on Server at last and use another platform?

**Comment by maxenceliu** [comment] 2017-08-17 03:28
@zihaolucky Now I use version 1.10, problem appear again?!! What do you mean by naive engine?

**Comment by cloudhan** [comment] 2017-08-17 03:54
@zihaolucky actually pre 0.9 version works okey. Seems there have been deadlock since NVVM refactor

**Comment by maxenceliu** [comment] 2017-08-17 04:22
@cloudhan Have you tried 0.10.1 version? Still will block for several seconds. It will call `WaitToRead()` when copy data to Cpu. I don't understand if all the dependency need to be wait for this copy.

**Comment by maxenceliu** [comment] 2017-08-17 04:34
@zihaolucky naive engine has not been implemented?

**Comment by cloudhan** [comment] 2017-08-17 06:29
@maxenceliu nah, I lost the script and forgot how to reproduce...

**Comment by maxenceliu** [comment] 2017-08-21 03:40
I found I use the docker env in the server. I'm not sure if docker could lead to this problem?

**Comment by maxenceliu** [comment] 2017-08-21 08:02
I think I have resolved this problem but still don't know why. #7417

**Comment by javelinjs** [comment] 2017-08-21 08:05
@maxenceliu 
Could you list the system env, including the mx version you're using (you mentioned 1.10 and 0.10.1 but neither is a valid version) or the git commit version?
Also please provide the shortest snippets that can reproduce the problem. I'll look into it.

**Closed** 2017-10-19 04:51 UTC

**Comment by mangojiez** [comment] 2017-12-05 08:19
I have meet the same problem . 
in asnumpy (self=<NDArray at remote 0x7fad1a284f90>, data=<numpy.ndarray at remote 0x7facfc6e97b0>)
    ctypes.c_size_t(data.size)))

**Comment by pilhoon** [comment] 2019-01-08 04:18
How about to use `as_in_context(mx.cpu())` like this:
`executor.output_dict['cls_prob_reshape_output'].as_in._context(mx.cpu()).asnumpy()`
