### ISSUE TITLE
Large batch size does not improve predict speed

### ISSUE THREAD

**Issue by gaosanyuan** [apache/incubator-mxnet#9764] opened 2018-02-11 10:09 UTC
I test the predict speed in mxnet using different batch size, and I found that predicting a large batch size data at the same time doesn't eventually improve the predict speed, compared to predicting the data one by one (exclude the time of loading data).
My environment is P40, which has enough GPU memory for my task. Why is it ?

**Comment by anirudh2290** [comment] 2018-02-13 18:30
Can you provide some more information: Do you have a minimum reproducible example ? Do you have any benchmark numbers ? What MXNet version are you using ?

**Comment by gaosanyuan** [comment] 2018-02-14 03:26
I use mxnet 0.12.0 to do image semantic segmentation, and the input data size is (Batch, C, H, W). When I set Batch is 1, the total predict time is about 1 second；When I set Batch is 2, the predict speed is about 2 seconds; When I set Batch is 4, the predict speed is about 4 seconds, etc.

**Comment by gaosanyuan** [comment] 2018-02-14 03:27
I use mxnet 0.12.0 to do image semantic segmentation, and the input data size is (Batch, C, H, W). When I set Batch is 1, the total predict time is about 1 second；When I set Batch is 2, the predict time is about 2 seconds; When I set Batch is 4, the predict time is about 4 seconds, etc.

**Comment by gaosanyuan** [comment] 2018-02-14 06:45
@anirudh2290

**Comment by sandeep-krishnamurthy** [comment] 2018-02-14 23:59
Hi @gaosanyuan - I think this question can get answer faster on discuss - https://discuss.mxnet.io/latest
Some related discussion:
https://discuss.mxnet.io/t/best-practices-for-prediction-on-a-machine-with-multiple-gpus/192/2
https://discuss.mxnet.io/t/forward-pass-performance-for-one-image-is-quite-slow-concerns-mxnet-0-11-0/229

Closing the issue here. Please reopen if the performance degradation is due to a bug.

**Closed by sandeep-krishnamurthy** 2018-02-14 23:59 UTC
