### ISSUE TITLE
Inconsistent behaviour nd.argmax against np.argmax when there are 'nans' in data

### ISSUE THREAD

**Issue by access2rohit** [apache/incubator-mxnet#16216] opened 2019-09-19 21:36 UTC
below is a reproducable example to display inconsistencies in argmax in mxnet and numpy
 ```python
>>> import mxnet as mx
>>> import mxnet.ndarray as nd
>>> x = np.array([[1,5,3],[float('nan'), 2,6]])
>>> x
array([[ 1.,  5.,  3.],
       [nan,  2.,  6.]])
>>> y = nd.array(x)
shape=(2, 3)
[14:05:53] src/c_api/c_api.cc:190: MXNDArrayCreateExInt64 shape=2
>>> nd.argmax(y, axis=0)
[0. 0. 1.]
<NDArray 3 @cpu(0)>
>>> nd.argmax(y, axis=1)
[1. 2.]
<NDArray 2 @cpu(0)>
>>> import numpy as np
>>> np.argmax(x, axis=0)
array([1, 0, 1])
>>> np.argmax(x, axis=1)
array([1, 0])
```

**Comment by access2rohit** [comment] 2019-09-19 21:40
@mxnet-label-bot add [numpy]

**Comment by access2rohit** [comment] 2019-09-19 21:40
@reminisce @szha

**Comment by haojin2** [comment] 2019-12-30 07:52
@access2rohit Seems like this issue has been addressed in the latest nightly build (mxnet-mkl==1.6.0b20191229):
```
>>> import mxnet as mx
>>> import mxnet.ndarray as nd
>>> import numpy as np
>>> x = np.array([[1,5,3],[float('nan'), 2,6]])
>>> y = nd.array(x)
>>> nd.argmax(y, axis=0)

[1. 0. 1.]
<NDArray 3 @cpu(0)>
>>> nd.argmax(y, axis=1)

[1. 0.]
<NDArray 2 @cpu(0)>
```
Closing this issue now, if you found the problem is not solved please feel free to re-open this issue.

**Closed by haojin2** 2019-12-30 07:52 UTC
Labels: Numpy
