### ISSUE TITLE
Distributed Training: looks like async from the log although setting the kv-store=dist_device_sync

### ISSUE THREAD

**Issue by zdaxie** [apache/incubator-mxnet#11777] opened 2018-07-17 07:01 UTC
## Description
Train the distributed image classification code from mxnet master branch, but it seems like async from the log although setting the kv-store=dist_device_sync

## Environment info (Required)
Python 2.7
Mxnet 1.2 from pip

## Partial log:
First several epoches seems like normal, however when the training process near the end, the sequence is totally disordered. Also, when there are several machines, only one of them (I guess it was the machine with rank 0) will do the final validation and cut off the training process. So is it normal?

INFO:root:Epoch[4] Batch [100]	Speed: 130.80 samples/sec	accuracy=0.058594
INFO:root:Epoch[4] Batch [100]	Speed: 124.33 samples/sec	accuracy=0.054883
INFO:root:Epoch[4] Batch [100]	Speed: 124.36 samples/sec	accuracy=0.059375
INFO:root:Epoch[4] Batch [100]	Speed: 124.71 samples/sec	accuracy=0.060352
INFO:root:Epoch[4] Batch [100]	Speed: 124.52 samples/sec	accuracy=0.049805
INFO:root:Epoch[4] Batch [100]	Speed: 124.22 samples/sec	accuracy=0.061719
INFO:root:Epoch[4] Batch [100]	Speed: 123.96 samples/sec	accuracy=0.060156
INFO:root:Epoch[4] Batch [100]	Speed: 125.70 samples/sec	accuracy=0.057813
INFO:root:Epoch[4] Batch [120]	Speed: 124.19 samples/sec	accuracy=0.061328
INFO:root:Epoch[4] Batch [120]	Speed: 132.98 samples/sec	accuracy=0.057813
INFO:root:Epoch[4] Batch [120]	Speed: 132.90 samples/sec	accuracy=0.058789
INFO:root:Epoch[4] Batch [120]	Speed: 129.81 samples/sec	accuracy=0.055664
INFO:root:Epoch[4] Batch [120]	Speed: 130.18 samples/sec	accuracy=0.051758
INFO:root:Epoch[4] Batch [120]	Speed: 130.86 samples/sec	accuracy=0.056836
INFO:root:Epoch[4] Batch [120]	Speed: 131.26 samples/sec	accuracy=0.059375
INFO:root:Epoch[4] Batch [120]	Speed: 131.27 samples/sec	accuracy=0.063086

INFO:root:Epoch[74] Batch [460]	Speed: 129.31 samples/sec	accuracy=0.505664
INFO:root:Epoch[74] Batch [360]	Speed: 129.30 samples/sec	accuracy=0.498828
INFO:root:Epoch[74] Batch [600]	Speed: 132.93 samples/sec	accuracy=0.504687
INFO:root:Epoch[74] Batch [400]	Speed: 130.13 samples/sec	accuracy=0.493555
INFO:root:Epoch[74] Batch [480]	Speed: 130.71 samples/sec	accuracy=0.510547
INFO:root:Epoch[74] Batch [340]	Speed: 131.04 samples/sec	accuracy=0.518555
INFO:root:Epoch[74] Batch [320]	Speed: 130.99 samples/sec	accuracy=0.517188
INFO:root:Epoch[74] Batch [300]	Speed: 132.39 samples/sec	accuracy=0.506055
INFO:root:Epoch[74] Batch [380]	Speed: 135.49 samples/sec	accuracy=0.490625
INFO:root:Epoch[74] Batch [480]	Speed: 135.43 samples/sec	accuracy=0.509766
INFO:root:Epoch[74] Batch [620]	Speed: 131.17 samples/sec	accuracy=0.504687
INFO:root:Epoch[74] Train-accuracy=0.535156
INFO:root:Epoch[74] Time cost=1237.146
INFO:root:Epoch[74] Batch [420]	Speed: 130.73 samples/sec	accuracy=0.500977
INFO:root:Epoch[74] Validation-accuracy=0.637695
INFO:root:Epoch[74] Batch [500]	Speed: 122.72 samples/sec	accuracy=0.498047
INFO:root:Epoch[74] Batch [360]	Speed: 122.85 samples/sec	accuracy=0.504883
INFO:root:Epoch[74] Batch [340]	Speed: 122.91 samples/sec	accuracy=0.500195

(it's the only validation of epoch 119)
INFO:root:Epoch[119] Batch [240]	Speed: 133.12 samples/sec	accuracy=0.542188
INFO:root:Epoch[119] Batch [620]	Speed: 131.63 samples/sec	accuracy=0.529102
INFO:root:Epoch[119] Batch [420]	Speed: 134.22 samples/sec	accuracy=0.537305
INFO:root:Epoch[119] Train-accuracy=0.599609
INFO:root:Epoch[119] Time cost=1233.944
INFO:root:Epoch[119] Batch [120]	Speed: 134.16 samples/sec	accuracy=0.534766
INFO:root:Epoch[119] Batch [160]	Speed: 134.36 samples/sec	accuracy=0.517969
INFO:root:Epoch[119] Validation-accuracy=0.669596

**Comment by rahul003** [comment] 2018-07-17 23:31
That order doesn't look normal in my experience. What network are you training? 

Also regarding the last validation part, do you see that the training hangs at that point on the last epoch? That could explain why some processes go ahead and finish valiation while others are stuck because they have more batches than other worker machines. If so, can you ensure you have the changes from this commit in your code. https://github.com/apache/incubator-mxnet/pull/10435/

**Comment by zdaxie** [comment] 2018-07-18 01:20
@nswamy @rahul003 The code i ran is incubator-mxnet/example/image-classification/train_imagenet.py, cloning from the master branch. The extra params is
--benchmark 0
--network resnet-v1
--gpus 0,1,2,3
--kv-store dist_device_sync
--num-layers 50
--batch-size 256
--dtype float32
--data-train /path/to/train.rec 
--data-val /path/to/val.rec
--num-epochs 120
--lr-step-epochs 30,60,90
--lr-factor 0.1
--image-shape 3,224,224
--lr 0.8
BTW, I used 8 machines with 32 cards.

About the last validation part, I think it's more like the main process just quit once it finished validating, so the results from other machines cannot be received. Usually there are 8 validation results after one complete epoch.

**Comment by zdaxie** [comment] 2018-07-26 03:42
Is there any solutions for this issue so far?  The former version of mxnet works fine in synchronization and accuracy, only the last epoch part still got stuck.

**Comment by ankkhedia** [comment] 2018-11-01 17:46
@zdaxie Is the issue persisting? Did you trying using particular commit as mentioned by @rahul003

**Comment by nswamy** [comment] 2018-11-09 05:46
@zdaxie thanks for letting us know, Closing Issue as unable to reproduce

**Closed by nswamy** 2018-11-09 05:46 UTC
Labels: Distributed, KVStore, Pending Requester Info
