### ISSUE TITLE
flaky test: test_spatial_transformer_with_type

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#11839] opened 2018-07-20 18:59 UTC
Flaky test introduced in master:

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1246/pipeline/

https://github.com/apache/incubator-mxnet/issues/7645

**Comment by szha** [comment] 2018-07-20 19:38
@ddavydenko

**Comment by ddavydenko** [comment] 2018-07-21 03:06
I just finished re-runing this test on P2.x8large with 1,000,000 iterations and have not seen single failure (`MXNET_TEST_COUNT=1000000 nosetests --logging-level=DEBUG tests/python/gpu/test_operator_gpu.py:test_spatial_transformer_with_type`).

I wonder whether this could be something related to the CI environment that causes flakyness as I am yet to see this failing, despite running 1M times.

**Comment by szha** [comment] 2018-07-21 05:43
Possibly. Here's a doc that @marcoabreu put together: https://cwiki.apache.org/confluence/display/MXNET/Reproducing+test+results

**Comment by marcoabreu** [comment] 2018-07-21 09:32
```
======================================================================

FAIL: test_operator_gpu.test_spatial_transformer_with_type

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 175, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 708, in test_spatial_transformer_with_type

    check_consistency(sym, ctx_list, grad_req="add")

  File "/work/mxnet/python/mxnet/test_utils.py", line 1354, in check_consistency

    raise e

  File "/work/mxnet/python/mxnet/test_utils.py", line 1349, in check_consistency

    equal_nan=equal_nan)

  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 229691.785771 exceeds tolerance rtol=0.000010, atol=0.000010.  Location of maximum error:(0, 2, 1, 0), a=-5.896435, b=-1.091782

 a: array([[[[ 0.86260644, -0.58269032, -0.9129366 , ...,  0.        ,

           0.        ,  0.        ],

         [-0.31708283, -0.38723805, -1.35227876, ...,  0.        ,...

 b: array([[[[ 0.69660542,  0.01495369, -0.62585958, ...,  0.        ,

           0.        ,  0.        ],

         [-0.10513522,  0.03817245, -1.14077367, ...,  0.        ,...

-------------------- >> begin captured stdout << ---------------------

Train Err: ctx 1 vs ctx 0 at data



--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=460980419 to reproduce.

--------------------- >> end captured logging << ---------------------

```

**Comment by larroy** [comment] 2018-07-21 10:32
@ddavydenko did you try to run the test in docker? using the ci/build.py tool and associated container?  this should provide a very similar environment minus hardware differences. But you can always start the same instance type. The base OS is quite vanilla, just docker and nvidia docker installed.

**Comment by anirudh2290** [comment] 2018-07-21 15:14
@ddavydenko its failing for NOCUDNN stage. You will have to build with USE_CUDA=ON and USE_CUDNN=OFF.

**Comment by ddavydenko** [comment] 2018-07-23 17:44
Thanks, @anirudh2290, I built with USE_CUDNN=0 and indeed I got this test consistently failing with such MXNet build. I checked on the CI pipeline and this test seems to be failing under "Python3: MKLDNN-GPU-NOCUDNN". I don't know right now what CUDNN has that makes this test work and makes it fail when there is no CUDNN support in MXNet. In the meantime I have a question: does it make sense to remove this test (and maybe others failing for the same reason) from CI step that uses MXNet without CUDNN in it?

**Comment by aaronmarkham** [comment] 2018-07-26 16:24
This same test caused my PR to fail CI yesterday: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11892/1/pipeline

**Comment by anirudhacharya** [comment] 2018-07-26 22:57
jenkins log file - http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-11856/runs/5/nodes/859/log/?start=0

```bash
======================================================================

FAIL: test_operator_gpu.test_spatial_transformer_with_type

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 707, in test_spatial_transformer_with_type

    check_consistency(sym, ctx_list)

  File "/work/mxnet/python/mxnet/test_utils.py", line 1354, in check_consistency

    raise e

  File "/work/mxnet/python/mxnet/test_utils.py", line 1349, in check_consistency

    equal_nan=equal_nan)

  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 14350.833283 exceeds tolerance rtol=0.000010, atol=0.000010.  Location of maximum error:(0, 3, 2, 6), a=3.242524, b=2.710094

 a: array([[[[-23.61268397, -14.63544932,   0.74020521, ...,   8.87566184,

          -10.74963933, -11.83532109],

         [ 20.2245003 ,   3.22738566,  21.24695322, ...,   4.78354851,...

 b: array([[[[-21.55476512, -13.13690641,   0.56911162, ...,   8.07749741,

           -9.78960317, -10.73026276],

         [ 18.3851834 ,   3.02351875,  19.34346791, ...,   4.4130619 ,...

-------------------- >> begin captured stdout << ---------------------

Train Err: ctx 1 vs ctx 0 at data
```

**Comment by Ishitori** [comment] 2018-08-08 17:54
I was able to reproduce the failing compiling MXNet from source with:

```
make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=0 
```

And then running it from project root folder:

```
export MXNET_TEST_SEED=914275233
nosetests -v tests/python/gpu/test_operator_gpu.py:test_spatial_transformer_with_type
```

**Comment by haojin2** [comment] 2018-09-14 22:46
The corresponding fix has been merged, please close the issue.

**Comment by haojin2** [comment] 2018-09-14 22:47
@anirudh2290 @eric-haibin-lin @nswamy @sandeep-krishnamurthy The corresponding fix has been merged, please close the issue.

**Closed** 2018-09-15 03:26 UTC
Labels: Disabled test, Flaky, Test
