### ISSUE TITLE
Data comparison is inconsistent with numpy

### ISSUE THREAD

**Issue by cs8105** [apache/incubator-mxnet#16964] opened 2019-12-03 07:05 UTC
In [88]: nd.array([0],dtype='int') < 1e-3                                                                                                                                                                                                   
Out[88]: 

[0]
<NDArray 1 @cpu(0)>

In [89]: np.array([0],dtype='int') < 1e-3                                                                                                                                                                                                   
Out[89]: array([ True])

In [90]:

**Comment by haojin2** [comment] 2019-12-04 21:08
Hi,
The behavior of nd is not guaranteed to be consistent as official NumPy.
If you're looking for NumPy-compatible behaviors, please try out the new NumPy-compatible interface, available in latest nightly versions & soon to be available in 1.6.0 release version:
```
>>> from mxnet import np
>>> np.array([0],dtype='int') < 1e-3
array([False])
```

**Comment by haojin2** [comment] 2019-12-05 04:40
@ptrendx I think it's a data type issue:
```
>>> from mxnet import np
>>> np.array([0],dtype='float') < 1e-3
array([ True])
```
I guess `1e-3` was casted to integer in the backend...

**Comment by sxjscience** [comment] 2019-12-06 21:21
I think the root cause would be the same as https://github.com/apache/incubator-mxnet/issues/16653

**Comment by yzhliu** [comment] 2020-04-30 06:02
@Tommliu is working on this.

**Comment by yzhliu** [comment] 2020-05-22 18:31
closed by #18277

**Closed by yzhliu** 2020-05-22 18:31 UTC
Labels: Numpy, WIP, v2.0
