### ISSUE TITLE
Strange behaviour/possible bug with mxnet::cpp::Symbol::Variable name argument

### ISSUE THREAD

**Issue by nikudyshko** [apache/incubator-mxnet#12966] opened 2018-10-24 20:15 UTC
## Description 
In a nutshell: network doesn't train if I change prefix in Symbol::Variable name argument from "w" and "b" (lines 38, 39 in example [mlp_cpu.cpp](https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/mlp_cpu.cpp)) to anything with length greater than 1 char (for example: to "ws"/"bs" or "qwe"/"rty") 

## Environment info 
Windows 10 64-bit, Visual Studio 2017 Community Edition (ver. 15.8.4) 
MXnet built from source (ver. 1.3.0) with cmake (ver. 3.13.0) and VS2017 (ver. 15.8.4) 
I'm using cpp package 

## Minimum reproducible example 
[mlp_cpu.cpp](https://github.com/apache/incubator-mxnet/blob/master/cpp-package/example/mlp_cpu.cpp) 

## Steps to reproduce 
1. Change lines 38, 39 to something like this: 
`   weights[i] = Symbol::Variable("ws" + std::to_string(i));`
`   biases[i] = Symbol::Variable("bs" + std::to_string(i));` 
2. Compile and run. 

## What have you tried to solve it? 
1. Temporary solution is simple - use only 1 char prefixes (actualy - there are 2 chars, because of string termination char) 

I think, that it somehow related to .InferArgsMap function, but that's not for sure. 

Probably, related to #8126

**Comment by andrewfayres** [comment] 2018-10-25 17:54
Thanks for the issue. Adding some labels to help get the correct eyes on this.

@mxnet-label-bot [c++, bug]

**Comment by ddavydenko** [comment] 2018-10-27 01:50
@mxnet-label-bot [Training]

**Comment by ddavydenko** [comment] 2018-10-27 01:51
@nikudyshko , it seems you are using C++ API for training the model. Would you mind sharing your use case? Namely, what made you chose C++ API for training purposes over, let's say, Python API?

**Comment by ddavydenko** [comment] 2018-10-27 01:56
@leleamol , could you please take a look into this issue?

**Comment by leleamol** [comment] 2018-10-29 17:57
@nikudyshko, @ddavydenko  I spent some time experimenting with this issue. This is an interesting issue.  If I use 2 or 3 characters in following lines to name the variable (e.g ws or wst, bs or bst) then the training fails.
weights[i] = Symbol::Variable("ws" + std::to_string(i));
biases[i] = Symbol::Variable("bs" + std::to_string(i));

However, if I use 1 or more than 3 characters then the training proceeds correctly.
I looked at implementations c++ package API implementations briefly and nothing stood out.  I would have to dive deeper.  Would also need to see if it is reproducible in python.

Will provide an update.

**Comment by leleamol** [comment] 2018-10-30 19:05
@nikudyshko , I compared this C++ implementation with python implementation.  (The excerpt given below). I noted following:

1.  In python API,  while creating "FullyConnected" layer, the names of 'weights' and 'biases' are automatically generated, if not specified. These names are of the format fc_weight and fc_bias
2. User can specify the names of "weights" and "biases" while creating FullyConnected layer using mx.sympo.FullyConnected. However, the names are required to end with "weight", "bias" , "gamma", etc.  The program (mentioned in the excerpt) prints following error.
```
'Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern' % name)
ValueError: Unknown initialization pattern for 2wt. Default initialization is now limited to "weight", "bias", "gamma" (1.0), and "beta" (0.0).Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern
```
This indicates that there are some rules or requirements need to be followed for naming the weights and biases for FullyConnected layers. I have tagged couple of experts who might provide more insight.  
@eric-haibin-lin @nswamy 

Excerpt of the program that creates mlp symbol in python.

```
data = mx.symbol.Variable('data')
wname = 'wt';
w1 = mx.sym.Variable(str(1) + wname);
w2 = mx.sym.Variable(str(2) + wname);
w3 = mx.sym.Variable(str(3) + wname);
fc1 = mx.symbol.FullyConnected(data, weight= w1, name='fc1', num_hidden=128)
act1 = mx.symbol.Activation(fc1, name='relu1', act_type="relu")
fc2 = mx.symbol.FullyConnected(act1, weight=w2, name = 'fc2', num_hidden = 64)
act2 = mx.symbol.Activation(fc2, name='relu2', act_type="relu")
fc3 = mx.symbol.FullyConnected(act2, weight=w3, name='fc3', num_hidden=10)
softmax = mx.symbol.SoftmaxOutput(fc3, name = 'sm')
```

**Comment by leleamol** [comment] 2018-10-30 23:13
The issue is similar to the issue #8108

**Comment by nikudyshko** [comment] 2018-11-01 00:04
@ddavydenko Sorry for my late answer, was AFK for few days. I'm developing application, that will be a part of software package for measurement complex from my lab and there is probability that it will require on-line learning. Whole package will be written on C++ so using cpp-api is the only option.

**Comment by leleamol** [comment] 2018-11-03 00:02
@nikudyshko The following lines in symbol.hpp are causing this behavior.
https://github.com/apache/incubator-mxnet/blob/e33da520641489363a710752e4fa7245a84aaa68/cpp-package/include/mxnet-cpp/symbol.hpp#L277

If the names of "weight" and "bias" variables are not 3 or 4 character long, then gradients for these variables are not upgraded. Hence the training fails. We need to fix this issue.

However, this can be worked around either by having the names of these variables more than 4 character long. Or passing the "std::map<std::string, OpReqType>" to Symbol::SimpleBind() function.
The std::map<std::string, OpReqType> map contains the symbol names for which we would like to update the gradients. Entries in this map will be

```
std::map<std::string, OpReqType> grad_req_type;

// ws1, bs1, ws2, bs2 are the names of weights and bias variables for layer 1 and 2
grad_req_type["ws1"] = OpReqType::kWriteTo
grad_req_type["bs1"] = OpReqType::kWriteTo
grad_req_type["ws2"] = OpReqType::kWriteTo
grad_req_type["bs2"] = OpReqType::kWriteTo

```

**Comment by nikudyshko** [comment] 2018-11-03 19:28
Thank you for your explanations. Not sure if this issue should be closed, so I leave it up to moderators.

**Comment by leleamol** [comment] 2019-01-04 21:34
@mxnet-label-bot  Can we close this issue since the fix has been merged with PR #13284

**Comment by piyushghai** [comment] 2019-01-17 20:38
@lanking520  Can you close this issue ? The issue is already fixed and verified.

**Comment by lanking520** [comment] 2019-01-17 21:06
@nikudyshko Close this issue for now. Please feel free to reopen if issue persist.

**Closed by lanking520** 2019-01-17 21:06 UTC
Labels: Bug, C++
