### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by chunhanl** [apache/incubator-mxnet#16240] opened 2019-09-22 22:11 UTC
## Description
Links under README -> Content are broken
[Tutorials](https://mxnet.incubator.apache.org/tutorials/) 
[Design Notes](https://mxnet.incubator.apache.org/architecture/index.html)
[Installation](https://mxnet.incubator.apache.org/install/index.html)
[Pretrained Model](http://mxnet.incubator.apache.org/api/python/gluon/model_zoo.html)

**Comment by JiaoPaner** [comment] 2019-09-23 15:07
Why hasn't anyone answered this question yet?

**Comment by kriswo** [comment] 2019-09-23 17:54
These broken links results in having no instructions to build MXNet from source for end users.

The issue is related to whomever is maintaining https://mxnet.incubator.apache.org/ as Google's links are also broken.  So anyone who Googles "build mxnet from source" gets broken links.

**Comment by roywei** [comment] 2019-09-23 18:04
I think it may due to our new website launch. Everything is still there on the new website, you may want to navigate and search directly on new website.

Installation: https://mxnet.incubator.apache.org/get_started
Built from source: https://mxnet.incubator.apache.org/get_started/ubuntu_setup
Tutorials: https://mxnet.incubator.apache.org/api/python/docs/tutorials/
Design: https://mxnet.incubator.apache.org/api   -> MXNet Architecture

It may take a few days for google to pick it up.

**Comment by roywei** [comment] 2019-09-23 18:05
similar issue https://github.com/apache/incubator-mxnet/issues/16249

**Comment by kriswo** [comment] 2019-09-23 18:10
There are also broken links on the website: https://mxnet.incubator.apache.org/api/cpp

That links to URLs like this: https://mxnet.incubator.apache.org/install/build_from_source

Which are broken.

**Comment by JiaoPaner** [comment] 2019-09-24 03:17
BTW，the new website is slower than before and many information is missing such as installation

**Comment by aaronmarkham** [comment] 2019-09-24 12:40
@JiaoPaner Sounds like you're having a network issue. Thomas and I worked on this site while traveling all over and even using satellite while on an airplane, so I'm pretty sure the site is fine with regard to being available. 
If you continue to have issues connecting to the website, please report it in a separate issue since this one will be closed when my link-fixing PR is merged. Any site availability is actually going to be an Apache infra ticket, and I can help with that.
I'm not a big fan of the weak link being a jquery dependency from a remote site (even google), so I'll move that to be hosted locally. That'll help somewhat.

**Comment by JiaoPaner** [comment] 2019-09-24 14:49
@aaronmarkham Thanks for your reply. The website is fine when I used VPN.The major reason is Great Fire Wall due to can not access google.com includes ajax.googleapis.com, locally jquery.js can solve it as you said, after all there are many Chinese developers use mxnet.

**Comment by igolan** [comment] 2019-09-24 15:04
The new website has a lot of bugs/missing documentations.
Few examples:
[Searching for broadcast_add does not return Symbol/ndarray broadcast_add methods](https://mxnet.incubator.apache.org/api/python/docs/search.html?q=broadcast_add) ( I also couldn't find it in the menu)
[In Symbol.sqaure , it refers to square methods but the link is to the same page ("Convenience fluent method for square().")](https://mxnet.incubator.apache.org/api/python/docs/api/symbol/_autogen/mxnet.symbol.Symbol.square.html#mxnet.symbol.Symbol.square)

(Also written in #16249 )

**Comment by aaronmarkham** [comment] 2019-09-24 15:23
@igolan You may want to report that as a separate issue since many people can contribute fixes and this issue will get closed soon. We don't want to lose track of what you've noticed.
The other one you mention will also get closed as the subject and core issue is related to google indexing and not a particular issue on the website. (I've opened a ticket with Apache infra about that one.)
Your issue could just be that something is missing and hopefully a patch can be supplied to add that in or fix the reference - it sounds like you found two issues, so split them up - especially if the fixes are likely to be distinct.

**Comment by Kh4L** [comment] 2019-09-25 11:16
Additional broken links: the two links on this page https://mxnet.incubator.apache.org/api/python/docs/tutorials/packages/symbol/index.html

**Closed** 2019-09-25 12:41 UTC
Labels: Website, website-beta

**Comment by pcsso** [comment] 2019-09-25 15:37
Most of the links on the [C++ build page](https://mxnet.incubator.apache.org/api/cpp) are still broken.

**Comment by aaronmarkham** [comment] 2019-09-25 16:00
> Most of the links on the [C++ build page](https://mxnet.incubator.apache.org/api/cpp) are still broken.

Strange. I'm looking into that.

**Comment by WIll-Xu35** [comment] 2019-09-26 01:13
The model zoo link returned by google is also broken. [https://mxnet.incubator.apache.org/model_zoo/index.html?highlight=model](url)
