### ISSUE TITLE
mxnet.ndarray.stack : PLEASE UPDATE DOC

### ISSUE THREAD

**Issue by y12uc231** [apache/incubator-mxnet#11925] opened 2018-07-28 18:27 UTC
![image](https://user-images.githubusercontent.com/5621640/43359560-f5e031be-9258-11e8-911d-59ad42e87640.png)

This is not how stack is working. Gives the following error when I execute the example pf stack(x,y):-
AssertionError: Positional arguments must have NDArray type, but got [1, 2]
 
I am using 1.2.

**Comment by haojin2** [comment] 2018-07-29 22:41
Can you post the exact instructions you used here?
This is what I got:
```
>>> import mxnet as mx
>>> a = mx.nd.array([1,2])
>>> b = mx.nd.array([3,4])
>>> mx.nd.stack(a, b)

[[ 1.  2.]
 [ 3.  4.]]
<NDArray 2x2 @cpu(0)>
```
Maybe what you did was:
```
>>> import mxnet as mx
>>> a = [1,2]
>>> b = [3,4]
>>> mx.nd.stack(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 39, in stack
AssertionError: Positional arguments must have NDArray type, but got [1, 2]
```?

**Comment by y12uc231** [comment] 2018-07-29 22:46
Yup, I did the second thing, which is exactly mentioned in the doc.

**Comment by mdespriee** [comment] 2018-07-30 11:50
@y12uc231 all arrays in the doc are (obviously) assumed to be NDArrays... It's even mentioned in your screenshot. So, stop yelling in all-caps in the first place, and try again with NDArrays

**Comment by eric-haibin-lin** [comment] 2018-07-31 01:31
@y12uc231 Hi, thanks for the feedback. Indeed it's not very clear. And even worse, it's a common problem for all operator examples. The problem is that the example is written once, and shown in python/scala/R documentation, so we tried to make it more language agnostic but unfortunately becomes very misleading...

**Comment by nswamy** [comment] 2018-08-15 04:37
Thanks @liyujiel, he added a Python example for stack now.  Closing the issue

**Closed by nswamy** 2018-08-15 04:37 UTC
Labels: Unclear Error/Doc
