### ISSUE TITLE
Gluon raises error if the user does not call nd.waitall()

### ISSUE THREAD

**Issue by sxjscience** [apache/incubator-mxnet#9167] opened 2017-12-21 20:45 UTC
The following program will raise an error if I directly run it using `python simple_program.py`. The syste I use is the latest Deep Learning AMI (CUDA9.0).

```python
import mxnet as mx
from mxnet import gluon
from mxnet.gluon import nn
from mxnet.gluon.nn import Block, HybridBlock


class TestBlock(Block):
    def __init__(self, prefix=None, params=None):
        super(TestBlock, self).__init__(prefix, params)
        with self.name_scope():
            self.L1 = nn.Dense(10)

    def forward(self, x):
        return self.L1(x)


test_block = TestBlock()
test_block.initialize(ctx=mx.gpu(), verbose=True)
```
```
[20:43:03] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [20:43:03] /home/travis/build/dmlc/mxnet-distro/mxnet-build/mshadow/mshadow/./stream_gpu-inl.h:115: Check failed: err == CUBLAS_STATUS_SUCCESS (1 vs. 0) Create cublas handle failed

Stack trace returned 8 entries:
[bt] (0) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x28980c) [0x7f8dd7bd780c]
[bt] (1) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x24193e6) [0x7f8dd9d673e6]
[bt] (2) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x24308b7) [0x7f8dd9d7e8b7]
[bt] (3) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2430a46) [0x7f8dd9d7ea46]
[bt] (4) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x242d26b) [0x7f8dd9d7b26b]
[bt] (5) /home/ubuntu/anaconda3/envs/mxnet_p36/bin/../lib/libstdc++.so.6(+0xafc5c) [0x7f8e0214bc5c]
[bt] (6) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f8e033956ba]
[bt] (7) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f8e030cb3dd]

[20:43:03] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [20:43:03] /home/travis/build/dmlc/mxnet-distro/mxnet-build/mshadow/mshadow/./stream_gpu-inl.h:115: Check failed: err == CUBLAS_STATUS_SUCCESS (1 vs. 0) Create cublas handle failed

Stack trace returned 8 entries:
[bt] (0) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x28980c) [0x7f8dd7bd780c]
[bt] (1) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x24193e6) [0x7f8dd9d673e6]
[bt] (2) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x24308b7) [0x7f8dd9d7e8b7]
[bt] (3) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2430a46) [0x7f8dd9d7ea46]
[bt] (4) /home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x242d26b) [0x7f8dd9d7b26b]
[bt] (5) /home/ubuntu/anaconda3/envs/mxnet_p36/bin/../lib/libstdc++.so.6(+0xafc5c) [0x7f8e0214bc5c]
[bt] (6) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f8e033956ba]
[bt] (7) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f8e030cb3dd]

terminate called after throwing an instance of 'dmlc::Error'
terminate called recursively
  what():  driver shutting downAborted (core dumped)
```
The following one will not raise error any more.
```python
import mxnet as mx
from mxnet import gluon
from mxnet.gluon import nn
from mxnet.gluon.nn import Block, HybridBlock


class TestBlock(Block):
    def __init__(self, prefix=None, params=None):
        super(TestBlock, self).__init__(prefix, params)
        with self.name_scope():
            self.L1 = nn.Dense(10)

    def forward(self, x):
        return self.L1(x)


test_block = TestBlock()
test_block.initialize(ctx=mx.gpu(), verbose=True)
mx.nd.waitall()
```
I feel that it's not very user friendly as the user cannot run this kind of simple testing code.

**Comment by zhiz21** [comment] 2018-03-20 03:10
proposed labels: "Gluon", "Python", "Bug"

**Comment by apeforest** [comment] 2018-07-04 16:35
@sxjscience I will look into this

**Comment by apeforest** [comment] 2018-07-05 16:59
This issue seems to be the same as [Issue 8997](https://github.com/apache/incubator-mxnet/issues/8997). @cjolivier01 Could you please confirm that? thx

**Comment by apeforest** [comment] 2018-07-19 20:34
@sxjscience I can no longer reproduce this issue. Please help to verify. Thanks!

**Comment by sandeep-krishnamurthy** [comment] 2018-07-20 22:50
Resolving as it is not reproducible. Please reopen if issue still persists.

**Closed by sandeep-krishnamurthy** 2018-07-20 22:50 UTC
Labels: Bug, Gluon, Python
