### ISSUE TITLE
Is NDArray creatiton thread safe

### ISSUE THREAD

**Issue by Redfriday** [apache/incubator-mxnet#12756] opened 2018-10-08 03:56 UTC
We use mxnet to do online prediction, the program randomly core when NDArray destructs, we may allocate NDArray parallelly in different thread, is NDArray creatiton not thread safe? Below code may be executed parallelly .

     mxnet::cpp::NDArray::Load(_network_param_path, nullptr, &network->params);
     // Create new ndarray according to the batch size for inputs.
      network->params["data"] = mxnet::cpp::NDArray(
                  mxnet::cpp::Shape(_batch_size, _dim),
                  mxnet::cpp::Context::cpu(), false);
      mxnet::cpp::NDArray::WaitAll();

**Comment by vrakesh** [comment] 2018-10-08 06:51
@Redfriday thanks for the query, requesting a more detailed reproducible example, with environment details, including operating system, and machine specifications.
@mxnet-label-bot [Question]

**Comment by marcoabreu** [comment] 2018-10-08 11:52
Hello,
In general, mxnet is not threadsafe. It goes as far as not even being safe to be called using a mutex.

Any interaction with mxnet has to happen with the same sticky thread in a single threaded fashion. Speak, if you use thread 1000 the first time you interact with mxnet, you always have to use thread 1000. This is called a dispatcher pattern.

Many people like to synchronize threads by using a mutex, like thread 1000, 1001, 1002 etc. This will not work because we have thread local variables that won't be present if you call with different threads.

Thus, you should create a dedicated thread for any interaction with mxnet and pipe your commands through that thread.

**Comment by Redfriday** [comment] 2018-10-08 12:10
@marcoabreu  Thank you, that is to say ndarray construct and destruction must be in one pthread?

**Comment by Redfriday** [comment] 2018-10-08 12:28
Got it, thank you very much.

**Comment by piyushghai** [comment] 2018-10-09 05:09
@sandeep-krishnamurthy Can you close this issue ? The Query has been answered.

**Closed** 2018-10-09 05:35 UTC
Labels: Question
