### ISSUE TITLE
[Discussion] 1.5.1 Patch Release

### ISSUE THREAD

**Issue by samskalicky** [apache/incubator-mxnet#15613] opened 2019-07-19 18:45 UTC
Let's start a discussion here about the known issues with 1.5.0 to put into a patch release. 

Create (or locate existing) issue/pull request for the item, note the issue/pull request number.
Comment in this issue: 1) the above issue number, 2) one sentence of what the item is about and why it's important.
Indicate whether you'd be willing to help out on the item.
Share the ETA if you're driving the item and have an guesstimate on when it will be done.

cc @apache/mxnet-committers

**Comment by samskalicky** [comment] 2019-07-19 18:46
Theres a problem with the WarpCTC plugin in 1.5.0 #15612. A PR has been created with a fix #15601

**Comment by ThomasDelteil** [comment] 2019-07-19 18:48
Reports of inference errors on 1.5.0:
https://discuss.mxnet.io/t/mxnet-1-5-0-is-not-downward-compatible-to-mxnet-1-4-1/4474
https://github.com/apache/incubator-mxnet/issues/15281

**Comment by roywei** [comment] 2019-07-19 18:52
Possible issue with asnumpy(), but not able to reproduce yet https://github.com/apache/incubator-mxnet/issues/15431

**Comment by roywei** [comment] 2019-07-19 18:52
license issues need to be fixed before next release https://github.com/apache/incubator-mxnet/issues/15542

**Comment by roywei** [comment] 2019-07-19 19:43
FYI https://github.com/apache/incubator-mxnet/issues/15281#issuecomment-513350879 is fixed in 1.5.0

**Comment by roywei** [comment] 2019-07-19 21:32
FYI https://github.com/apache/incubator-mxnet/issues/15337 is also resolved

**Comment by keerthanvasist** [comment] 2019-07-19 22:05
@mxnet-label-bot add [discussion]

**Comment by iblis17** [comment] 2019-07-20 06:10
I will track Julia stuffs that need to be backported here:
- [ ] https://github.com/apache/incubator-mxnet/pull/15609
- [ ] https://github.com/apache/incubator-mxnet/pull/15608

**Comment by iblis17** [comment] 2019-07-20 14:22
Hi, I just created a label "Backport 1.5" (https://github.com/apache/incubator-mxnet/labels/Backport%201.5).
I think we can create a single PR to collecting the stuffs that need to be backported, use this label as a checklist, and keep that PR open until we want to make a release candidate.

**Comment by marcoabreu** [comment] 2019-07-22 12:46
I'd prefer if we use multiple PRs which only contain cherry-picks from master. That way, we don't squash and keep the references.

**Comment by iblis17** [comment] 2019-07-23 06:28
ah, okay

**Comment by szha** [comment] 2019-07-26 20:22
@samskalicky thanks for starting the discussion. @PatricZhao @TaoLv could you drive this release?

**Comment by pengzhao-intel** [comment] 2019-07-28 04:37
It's great to lead the release. @TaoLv @juliusshufan will be working on this.

**Comment by roywei** [comment] 2019-07-31 17:08
nightly test failure need to be fixed:
https://github.com/apache/incubator-mxnet/issues/15374

**Comment by sandeep-krishnamurthy** [comment] 2019-07-31 23:56
https://github.com/apache/incubator-mxnet/pull/15672

**Comment by samskalicky** [comment] 2019-08-05 22:49
@TaoLv Can #15737 be fixed in 1.5.1?

**Comment by TaoLv** [comment] 2019-08-06 05:43
> @TaoLv Lets include #15692 in the 1.5.1 release to fix #15737

Thanks for reporting. Added it to https://cwiki.apache.org/confluence/display/MXNET/1.5.1+Release+Plan+and+Status

**Comment by wkcn** [comment] 2019-08-06 23:47
Hi, I’m fixing the bug of two C APIs `MXEnginePushAsyncND` and `MXEnginePushSyncND`
https://github.com/apache/incubator-mxnet/pull/15751

It will be finished this week.

**Comment by TaoLv** [comment] 2019-08-07 02:14
Thanks for proposing, @wkcn . 
Is this bug firstly introduced in the 1.5.0 release?  Why do you think it should be included into the 1.5.1 patch release?

**Comment by wkcn** [comment] 2019-08-07 02:41
@TaoLv Yes, it is a bug in 1.5.0 release https://github.com/apache/incubator-mxnet/blob/v1.5.x/src/c_api/c_api.cc#L1537

It need to be fixed,  otherwise users couldn't use these two C APIs in the release version of MXNet.

**Comment by TaoLv** [comment] 2019-08-07 02:45
I mean does it also exist in v1.4.x releases?

**Comment by wkcn** [comment] 2019-08-07 02:48
@TaoLv It doesn't exist in v1.4.x release. The bug was introdueced firstly in v1.5.x release.

**Comment by TaoLv** [comment] 2019-08-07 05:44
Thanks for the clarification. Do you have a github issue for that? I add it to the track list.

**Comment by wkcn** [comment] 2019-08-07 06:36
@TaoLv I have added the issue https://github.com/apache/incubator-mxnet/issues/15774

**Comment by TaoLv** [comment] 2019-08-07 06:48
@wkcn, thanks for your report and contribution! The issue and your fix are added to https://cwiki.apache.org/confluence/display/MXNET/1.5.1+Release+Plan+and+Status.

**Comment by KellenSunderland** [comment] 2019-08-07 17:43
I'd like to backport a few TensorRT patches we've contributed to master.  No functional changes but they'll provide support for many additional models that would otherwise not be supported.

**Comment by samskalicky** [comment] 2019-08-07 19:01
https://github.com/apache/incubator-mxnet/issues/15784 needs to be fixed in 1.5.1, big impact for simple_bind

**Comment by roywei** [comment] 2019-08-07 20:37
we also need to update mshadow on 1.5.x branch https://github.com/apache/incubator-mxnet/pull/15600

**Comment by TaoLv** [comment] 2019-08-08 01:42
> I'd like to backport a few TensorRT patches we've contributed to master. No functional changes but they'll provide support for many additional models that would otherwise not be supported.

Thank you @KellenSunderland . Could you help to list them to the cwiki page?

**Comment by TaoLv** [comment] 2019-08-08 01:42
> #15784 needs to be fixed in 1.5.1, big impact for simple_bind. The fix is in #15620. @TaoLv please include this too. Thanks!

Sure. I will do that.

**Comment by TaoLv** [comment] 2019-08-08 01:42
> we also need to update mshadow on 1.5.x branch #15600

@szha is this needed?

**Comment by TaoLv** [comment] 2019-08-08 02:12
> nightly test failure need to be fixed:
> #15374
> 
> http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/NightlyTestsForBinaries/detail/master/395/pipeline/

@roywei @lebeg Could you help to check if the issue has been fixed via https://github.com/apache/incubator-mxnet/pull/15452? If so,  I will include the fix to the 1.5.1 patch release. Thanks!

**Comment by samskalicky** [comment] 2019-08-08 04:43
> > we also need to update mshadow on 1.5.x branch #15600
> 
> @szha is this needed?

@TaoLv without this when you checkout the v1.5.x branch the 3rdparty/mshadow directory is empty and mxnet fails to compile. This is definitely needed.

**Comment by TaoLv** [comment] 2019-08-08 05:02
> > > we also need to update mshadow on 1.5.x branch #15600
> > 
> > 
> > @szha is this needed?
> 
> @TaoLv without this when you checkout the v1.5.x branch the 3rdparty/mshadow directory is empty and mxnet fails to compile. This is definitely needed.

Then you need backport this change to all of the release branches. Can this be mitigated by `git submodule sync` and `git submodule update --recursive --init`?
I'm afraid even if this change is picked to v1.5.x, users will get git complains when they try to pull the latest code if they are on a old commit.

**Comment by KellenSunderland** [comment] 2019-08-08 05:22
What's the issue with MShadow?  Did they have to do a force push / history re-write again?  We may indeed have to backport that to other release branches.

**Comment by TaoLv** [comment] 2019-08-08 14:03
@KellenSunderland  mshadow source code is donated and merged to MXNet. See https://github.com/apache/incubator-mxnet/pull/15600 and https://github.com/dmlc/mshadow/issues/373. So it's not a git submodule any more.

**Comment by wkcn** [comment] 2019-08-08 14:43
For the source downloaded before mshadow merged into MXNet, users need to remove 
the directory mshadow firstly, then git pull to update the code.

**Comment by samskalicky** [comment] 2019-08-08 15:35
@wkcn that doesnt work for me:

```
ubuntu@ip-172-31-76-214:~$ git clone --recursive https://github.com/apache/incubator-mxnet.git mxnet2
Cloning into 'mxnet2'...

ubuntu@ip-172-31-76-214:~/mxnet2$ git checkout v1.5.x
M	3rdparty/dlpack
M	3rdparty/dmlc-core
M	3rdparty/mkldnn
M	3rdparty/tvm
Branch v1.5.x set up to track remote branch v1.5.x from origin.
Switched to a new branch 'v1.5.x'
ubuntu@ip-172-31-76-214:~/mxnet2$ cd 3rdparty/
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ ls
ctc_include  dlpack  dmlc-core  googletest  mkldnn  mshadow  nvidia_cub  onnx-tensorrt  openmp  ps-lite  tvm
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ ls mshadow/
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ rm -rf mshadow/
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ git pull
Already up-to-date.
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ ls
ctc_include  dlpack  dmlc-core  googletest  mkldnn  nvidia_cub  onnx-tensorrt  openmp  ps-lite  tvm
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ git submodule update --recursive
Submodule path 'dlpack': checked out '10892ac964f1af7c81aae145cd3fab78bbccd297'
Submodule path 'dmlc-core': checked out '3943914eed66470bd010df581e29e4dca4f7df6f'
Submodule path 'mkldnn': checked out '41bee20d7eb4a67feeeeb8d597b3598994eb1959'
Submodule path 'tvm': checked out '21935dcbf56ad3bd66ebff9891a6bc3865b8106d'
Submodule path 'tvm/3rdparty/dlpack': checked out '5c792cef3aee54ad8b7000111c9dc1797f327b59'

Submodule path 'tvm/3rdparty/dmlc-core': checked out '82bf4c2e2af312b3d52513aa727483803a2f8734'
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ 
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ ls
ctc_include  dlpack  dmlc-core  googletest  mkldnn  nvidia_cub  onnx-tensorrt  openmp  ps-lite  tvm
ubuntu@ip-172-31-76-214:~/mxnet2/3rdparty$ 
```

**Comment by wkcn** [comment] 2019-08-08 22:58
Hi @samskalicky ,  I can download `mshadow` by `git submodule update --init --recursive`
```bash
➜  proj git clone https://github.com/apache/incubator-mxnet mxnet3
Cloning into 'mxnet3'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 97837 (delta 3), reused 3 (delta 0), pack-reused 97814
Receiving objects: 100% (97837/97837), 60.86 MiB | 610.00 KiB/s, done.
Resolving deltas: 100% (64993/64993), done.
➜  proj cd mxnet3
➜  mxnet3 git:(master) git checkout v1.5.x 
Branch 'v1.5.x' set up to track remote branch 'v1.5.x' from 'origin'.
Switched to a new branch 'v1.5.x'
➜  mxnet3 git:(v1.5.x) cd 3rdparty 
➜  3rdparty git:(v1.5.x) cd mshadow 
➜  mshadow git:(v1.5.x) ls
➜  mshadow git:(v1.5.x) cd ..
➜  3rdparty git:(v1.5.x) rm -rf 
➜  3rdparty git:(v1.5.x) git submodule update --init --recursive
Submodule '3rdparty/dlpack' (https://github.com/dmlc/dlpack) registered for path 'dlpack'
Submodule '3rdparty/dmlc-core' (https://github.com/dmlc/dmlc-core.git) registered for path 'dmlc-core'
Submodule '3rdparty/googletest' (https://github.com/google/googletest.git) registered for path 'googletest'
Submodule '3rdparty/mkldnn' (https://github.com/intel/mkl-dnn.git) registered for path 'mkldnn'
Submodule '3rdparty/mshadow' (https://github.com/dmlc/mshadow.git) registered for path 'mshadow'
Submodule '3rdparty/nvidia_cub' (https://github.com/NVlabs/cub.git) registered for path 'nvidia_cub'
Submodule '3rdparty/onnx-tensorrt' (https://github.com/onnx/onnx-tensorrt.git) registered for path 'onnx-tensorrt'
Submodule '3rdparty/openmp' (https://github.com/llvm-mirror/openmp) registered for path 'openmp'
Submodule '3rdparty/ps-lite' (https://github.com/dmlc/ps-lite) registered for path 'ps-lite'
Submodule '3rdparty/tvm' (https://github.com/dmlc/tvm) registered for path 'tvm'
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/dlpack'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/dmlc-core'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/googletest'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/mkldnn'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/mshadow'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/nvidia_cub'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/onnx-tensorrt'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/openmp'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/ps-lite'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/tvm'...
Submodule path 'dlpack': checked out '10892ac964f1af7c81aae145cd3fab78bbccd297'
Submodule path 'dmlc-core': checked out '3943914eed66470bd010df581e29e4dca4f7df6f'
Submodule path 'googletest': checked out 'eb9225ce361affe561592e0912320b9db84985d0'
Submodule path 'mkldnn': checked out '41bee20d7eb4a67feeeeb8d597b3598994eb1959'
Submodule path 'mshadow': checked out '1d79ecfdb4c9234537e1bf5148f44a1af54501ec'
Submodule path 'nvidia_cub': checked out 'c3cceac115c072fb63df1836ff46d8c60d9eb304'
Submodule path 'onnx-tensorrt': checked out '1e209e546061173ccc37b25bbca69a795c6c86e4'
Submodule 'third_party/onnx' (https://github.com/onnx/onnx.git) registered for path 'onnx-tensorrt/third_party/onnx'
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/onnx-tensorrt/third_party/onnx'...
Submodule path 'onnx-tensorrt/third_party/onnx': checked out '765f5ee823a67a866f4bd28a9860e81f3c811ce8'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'onnx-tensorrt/third_party/onnx/third_party/benchmark'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'onnx-tensorrt/third_party/onnx/third_party/pybind11'
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/onnx-tensorrt/third_party/onnx/third_party/benchmark'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/onnx-tensorrt/third_party/onnx/third_party/pybind11'...
Submodule path 'onnx-tensorrt/third_party/onnx/third_party/benchmark': checked out 'e776aa0275e293707b6a0901e0e8d8a8a3679508'
Submodule path 'onnx-tensorrt/third_party/onnx/third_party/pybind11': checked out 'a1041190c8b8ff0cd9e2f0752248ad5e3789ea0c'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang'
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang'...
Submodule path 'onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'openmp': checked out '37c72127e90360a020f351f18d9cccfc30e5145a'
Submodule path 'ps-lite': checked out '8a763892a973afc1acd3d4b469d05bb338a83a6e'
Submodule path 'tvm': checked out '21935dcbf56ad3bd66ebff9891a6bc3865b8106d'
Submodule 'HalideIR' (https://github.com/dmlc/HalideIR) registered for path 'tvm/3rdparty/HalideIR'
Submodule 'dlpack' (https://github.com/dmlc/dlpack) registered for path 'tvm/3rdparty/dlpack'
Submodule 'dmlc-core' (https://github.com/dmlc/dmlc-core) registered for path 'tvm/3rdparty/dmlc-core'
Submodule '3rdparty/rang' (https://github.com/agauniyal/rang) registered for path 'tvm/3rdparty/rang'
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/tvm/3rdparty/HalideIR'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/tvm/3rdparty/dlpack'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/tvm/3rdparty/dmlc-core'...
Cloning into '/mnt/wkcn/proj/mxnet3/3rdparty/tvm/3rdparty/rang'...
Submodule path 'tvm/3rdparty/HalideIR': checked out 'ec9585a5a5df3de91e8916ac2d27a4a509eac5fc'
Submodule path 'tvm/3rdparty/dlpack': checked out '5c792cef3aee54ad8b7000111c9dc1797f327b59'
Submodule path 'tvm/3rdparty/dmlc-core': checked out '82bf4c2e2af312b3d52513aa727483803a2f8734'
Submodule path 'tvm/3rdparty/rang': checked out 'cabe04d6d6b05356fa8f9741704924788f0dd762'

```

**Comment by TaoLv** [comment] 2019-08-09 15:53
@KellenSunderland Could you please include the TensorRT patches you just mentioned into the cwiki? https://cwiki.apache.org/confluence/display/MXNET/1.5.1+Release+Plan+and+Status

Thanks for your support!

**Comment by TaoLv** [comment] 2019-08-12 02:10
@iblis17 Could you help to pick #15608 #15609 to the v1.5.x branch?

**Comment by KellenSunderland** [comment] 2019-08-13 04:57
For some reason not able to edit the cwiki?

Proposals for fixes are: 
https://github.com/apache/incubator-mxnet/pull/15645
https://github.com/apache/incubator-mxnet/pull/15666
https://github.com/apache/incubator-mxnet/pull/14898
https://github.com/apache/incubator-mxnet/pull/15344

**Comment by TaoLv** [comment] 2019-08-13 05:31
Thank you @KellenSunderland . I just included these patches to the table on cwiki. Please help take a look: https://cwiki.apache.org/confluence/display/MXNET/1.5.1+Release+Plan+and+Status
BTW, do you know someone with TensorRT background can help to pick them to the v1.5.x branch? Because I'm wondering if they need be ported in a certain order.

**Comment by KellenSunderland** [comment] 2019-08-13 16:15
No problem Tao, I can probably cherry-pick them a bit later today.

**Comment by KellenSunderland** [comment] 2019-08-13 16:35
First two cherry-picked PRs:
https://github.com/apache/incubator-mxnet/pull/15875
https://github.com/apache/incubator-mxnet/pull/15874

**Comment by ChaiBapchya** [comment] 2019-08-19 14:41
Benchmark doc fix PR https://github.com/apache/incubator-mxnet/pull/15769

**Comment by samskalicky** [comment] 2019-08-21 00:00
@TaoLv I'd like to pull in the following PRs, they are necessary fixes for some of my use-cases:
https://github.com/apache/incubator-mxnet/pull/15245
https://github.com/apache/incubator-mxnet/pull/15917

**Comment by apeforest** [comment] 2019-08-21 00:06
This PR fixes a memory misalignment bug in topk operator introduced recently. Please add it to 1.5.1 patch release:
https://github.com/apache/incubator-mxnet/pull/15948

Thanks

**Comment by TaoLv** [comment] 2019-08-28 14:59
> First three cherry-picked PRs:
> #15875
> #15874
> #15877

@KellenSunderland, the 3 PRs were already merged to v1.5.x. Please update for the other two if we still need them.

**Comment by TaoLv** [comment] 2019-08-28 14:59
> Benchmark doc fix PR #15769

@ChaiBapchya, thank you for the report. Could you please cherry pick it to the v1.5.x branch and tag me in the PR?

**Comment by TaoLv** [comment] 2019-08-28 15:00
> @TaoLv I'd like to pull in the following PRs, they are necessary fixes for some of my use-cases:
> #15245
> #15917

@samskalicky , please pick them to v1.5.x and tag me in the PR. I will update the cwiki page accordingly.

**Comment by TaoLv** [comment] 2019-08-28 15:01
> This PR fixes a memory misalignment bug in topk operator introduced recently. Please add it to 1.5.1 patch release:
> #15948
> 
> Thanks

@apeforest Any update? Is it still true that we can pick this to v1.5.x?

**Comment by KellenSunderland** [comment] 2019-08-30 04:13
Added:
https://github.com/apache/incubator-mxnet/pull/16043

**Comment by iblis17** [comment] 2019-09-11 04:24
> @iblis17 Could you help to pick #15608 #15609 to the v1.5.x branch?

@TaoLv Just can I just push to the v1.5.x branch direcetly?

**Comment by marcoabreu** [comment] 2019-09-11 06:16
No, please create pull requests instead

**Comment by apeforest** [comment] 2019-09-11 06:26
Haven't we already passed code freeze?

**Comment by TaoLv** [comment] 2019-09-11 08:17
Yes, we have passed code freeze and the rc0 was already tagged. Front-end packaging is in progress. One can still commit code change to the v1.5.x branch but that will be not included in the vote for rc0.

**Comment by lostella** [comment] 2019-09-11 12:54
1.5.0 apparently broke sampling operators on Linux, see #16135. A PR is open for this #16139. I hope this has a chance to make it to 1.5.1.

**Comment by eric-haibin-lin** [comment] 2019-09-20 00:47
If we have a chance for another RC, we should port https://github.com/apache/incubator-mxnet/pull/15240 and https://github.com/apache/incubator-mxnet/pull/15342

**Comment by iblis17** [comment] 2019-09-22 07:21
No idea why my backporting PR got closed (#16142).

**Comment by strawberrypie** [comment] 2019-10-25 14:39
Any news on 1.5.1?

**Comment by eric-haibin-lin** [comment] 2019-10-25 17:31
released: https://github.com/apache/incubator-mxnet/releases/tag/1.5.1

**Closed by eric-haibin-lin** 2019-10-25 17:31 UTC
Labels: Discussion
