### ISSUE TITLE
An error occurred while calculating the square of ndarray by using gpu context

### ISSUE THREAD

**Issue by shitou112** [apache/incubator-mxnet#9455] opened 2018-01-16 14:17 UTC
#### 1. When I use a**2 to compute square, I encounter an error. 
```
Input: a = nd.array([-1], mx.gpu())
       a ** 2

Output: [ nan]
        <NDArray 1 @gpu(0)>
```
#### 2. However, when using ctx=mx.cpu(), the result is right.
```
Input: a = nd.array([-1], mx.cpu())
       a ** 2

Output: [ 1.]
        <NDArray 1 @cpu(0)>
```

#### 3. when I use a*a to compute square, the result is also right.
```
Input: a = nd.array([-1], mx.gpu())
       a * a

Output: [ 1.]
        <NDArray 1 @gpu(0)>
```

**Comment by reminisce** [comment] 2018-01-18 18:28
Since running operators in Python is async with backend, you need to wait until the computation of pow is finished. Try this: `(a**2).asnumpy()`.

**Comment by shitou112** [comment] 2018-01-22 14:11
![01](https://user-images.githubusercontent.com/19506054/35224695-d29bb190-ffc0-11e7-9255-f6924184b662.png)

I try asnumpy() function. But the result is wrong.

**Comment by reminisce** [comment] 2018-01-22 19:49
That's very strange. I couldn't reproduce the problem you encountered. Does it happen to other versions of MXNet on your machine?

**Comment by shitou112** [comment] 2018-01-23 06:53
Thank you a lot. I upgrade mxnet and the result is right.

**Comment by tolkien16** [comment] 2018-01-23 14:03
Hi

**Comment by vdantu** [comment] 2018-02-27 22:58
@sandeep-krishnamurthy : please label this "Question" and close this. This seems to have been resolved.

**Closed** 2018-02-27 23:29 UTC
