### ISSUE TITLE
Flaky test for test_operator.test_reduce

### ISSUE THREAD

**Issue by anirudh2290** [apache/incubator-mxnet#10476] opened 2018-04-10 01:52 UTC
Try to use MXNET_TEST_SEED=1117986172
```
======================================================================
FAIL: test_operator.test_reduce
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/experimentals/spidyDev_mxnet/tests/python/unittest/common.py", line 157, in test_new
    orig_test(*args, **kwargs)
  File "/home/ubuntu/experimentals/spidyDev_mxnet/tests/python/unittest/test_operator.py", line 1826, in test_reduce
    mx.symbol.max, test_none_axis=test_none)
  File "/home/ubuntu/experimentals/spidyDev_mxnet/tests/python/unittest/test_operator.py", line 1799, in test_reduce_inner
    assert equal_backward
AssertionError:
-------------------- >> begin captured logging << --------------------
common: INFO: Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=754316987 to reproduce.
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1117986172 to reproduce.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 22.731s

FAILED (failures=1)
```

**Comment by marcoabreu** [comment] 2018-04-10 05:56
Duplicate of https://github.com/apache/incubator-mxnet/issues/9845

**Closed by marcoabreu** 2018-04-10 05:56 UTC
