### ISSUE TITLE
Flaky LeakyRelu Test

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#10421] opened 2018-04-05 16:20 UTC
Failed in http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10285/8/pipeline

```
======================================================================

FAIL: test_operator.test_leaky_relu

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 528, in test_leaky_relu

    check_numeric_gradient(y, [xa], numeric_eps=eps, rtol=rtol, atol=atol, dtype=dtype)

  File "/work/mxnet/python/mxnet/test_utils.py", line 914, in check_numeric_gradient

    ("NUMERICAL_%s"%name, "BACKWARD_%s"%name))

  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 1.131078 exceeds tolerance rtol=0.000100, atol=0.001000.  Location of maximum error:(2, 1), a=1.082420, b=1.081167

 NUMERICAL_x: array([[1.0943413 , 0.04511327, 0.14789402, 0.29626304],

       [0.14711171, 1.0299683 , 0.513196  , 0.24553388],

       [0.10631979, 1.0824203 , 0.04339963, 0.6210804 ]], dtype=float32)

 BACKWARD_x: array([[1.0940626 , 0.04511051, 0.14786199, 0.29625115],

       [0.14712255, 1.0296007 , 0.51318413, 0.24551794],

       [0.10629743, 1.081167  , 0.04339443, 0.6207933 ]], dtype=float32)

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1436539337 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by haojin2** [comment] 2018-04-05 17:16
The difference between the target and the actual result is really small, after some research I found this is caused by a too tight rtol (1e-4 instead of default 1e-2). A fix for this is delivered in #10422

**Closed** 2018-04-05 19:58 UTC
Labels: Flaky, Test
