### ISSUE TITLE
USE_BLAS=MKL fails due to mshadow requiring openblas

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#11769] opened 2018-07-16 16:21 UTC
Seems like you should be able to just use MKL. Docs suggest as much, but this doesn't work.

**Comment by aaronmarkham** [comment] 2018-07-16 21:51
More context: https://github.com/apache/incubator-mxnet/pull/11049#discussion_r202511708
Here's the error.
```
cmake -G "Visual Studio 15 Win64" .. -DUSE_CUDA=0 -DUSE_CUDNN=0 -DUSE_NVRTC=0 -DUSE_OPENCV=1 -DUSE_OPENMP=1 -DUSE_PROFILER=1 -DUSE_BLAS=mkl -DUSE_LAPACK=1 -DUSE_DIST_KVSTORE=0 -DCUDA_ARCH_NAME=All -DUSE_MKLDNN=1 -DCMAKE_BUILD_TYPE=Release
Got this error.
CMake Error at cmake/Modules/FindOpenBLAS.cmake:82 (MESSAGE):
Could not find OpenBLAS
Call Stack (most recent call first):
3rdparty/mshadow/cmake/mshadow.cmake:26 (find_package)
CMakeLists.txt:246 (include)
```

**Comment by azai91** [comment] 2018-09-18 21:15
https://github.com/dmlc/mshadow/blob/master/cmake/mshadow.cmake#L11

Will look into what functions are not supported.

**Comment by stereomatchingkiss** [comment] 2019-03-06 04:26
os : win10 64bits
compiler : vc2015 64 bits update 3(this version cannot build with openBLAS, lots of link issue)
cuda : no cuda, cpu only
opencv : no opencv
mxnet version : 1.3.1(1.4.0 cannot compile on window, please read #14203 )

The mshadow.cmake generated by cmake under the folder 3rdparty\mshadow\cmake got command like this

```
if(USE_MKL_IF_AVAILABLE)
  if(NOT MKL_FOUND)
    find_package(MKL)
  endif()
  if(MKL_FOUND)
    if(USE_MKLML_MKL)
      set(BLAS "open")
    else()
      set(BLAS "MKL")
    endif()
  endif()
endif()
```

After uncheck USE_MKLML_MKL I can compile mshadow with mkl with cpp_package, but 

1. the install project do not work
2. when I execute the program, it keep complain "Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll."

**Comment by pengzhao-intel** [comment] 2019-08-04 01:10
The MKLDNN cmake and makefile is updated recently. I think the issue is resolved.
Closing now and feel free to reopen if any issue is found.

**Closed by pengzhao-intel** 2019-08-04 01:10 UTC
Labels: Build, MKL, MKLDNN
