### ISSUE TITLE
cpp-package predict  error at 'int best_idx = predicted.At(0, 0)' whether the ndarray.hpp have a bug?

### ISSUE THREAD

**Issue by abner2015** [apache/incubator-mxnet#14732] opened 2019-04-18 07:35 UTC
The example from 

> https://github.com/apache/incubator-mxnet/tree/master/cpp-package/example/inference

when i use the cpp package inference the image , occur the error :

> ### vector subscript out of range
at the  line :`int best_idx = predicted.At(0, 0)` 
debug code at `ndarray.hpp' :
 
`inline size_t NDArray::Offset(size_t h, size_t w)  const {
  return (h * GetShape()[1]) + w;
}
`
whether hava a bug in ndarray.hpp?

>  **and GetShape()[0] is right?**

**Comment by frankfliu** [comment] 2019-04-18 16:02
@mxnet-label-bot add [C++, example]

**Comment by leleamol** [comment] 2019-05-23 00:09
@abner2015 
Can you please post the error that you are getting after running this example?

**Comment by abner2015** [comment] 2019-05-23 06:48
@leleamol

> @abner2015
> Can you please post the error that you are getting after running this example?

see content above

**Comment by leleamol** [comment] 2019-05-25 00:46
@abner2015 I could not reproduce this issue.The example ran correctly without any errors that you had mentioned.
It would be helpful if you paste the error that you have obtained.

**Comment by leleamol** [comment] 2019-05-25 00:46
@mxnet-label-bot add [Pending Requester Info]

**Comment by leleamol** [comment] 2019-06-07 17:55
There is a potential for index out of range. Thanks @abner2015  for pointing this out.
I have created a PR to address this issue.
#15179

**Comment by leleamol** [comment] 2019-06-07 22:11
#15179 is merged.

The issue can be closed.

**Comment by zachgk** [comment] 2019-06-11 22:17
I am closing this issue as it should be resolved as part of #15179. @abner2015, please reopen if the problem persists.

**Closed by zachgk** 2019-06-11 22:17 UTC
Labels: C++, Example, Pending Requester Info
