### ISSUE TITLE
Does global pooling support padding?

### ISSUE THREAD

**Issue by TaoLv** [apache/incubator-mxnet#9714] opened 2018-02-06 13:44 UTC
Currently, when do global pooling in mxnet (with param.global_pool=True):
- input kernel size will be reset as input size (H, W);
- stride size will be reset to 1 for 1D, to (1, 1) for 2D;
- padding size will be set as what users input;
- output shape will be (N, C, 1) or (N, C, 1, 1) for 2D;

Please kindly find pooling code [here](https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/pooling-inl.h#L101):
```
    pool(s, in_data[pool_enum::kData].dptr<DType>(),
         in_data[pool_enum::kData].shape_,
         out_data[pool_enum::kOut].shape_,
         param_.global_pool?
           TShape(ishape.data()+ishape.ndim()-param_.kernel.ndim(), ishape.data()+ishape.ndim())
           : param_.kernel,  // reset kernel size for global pooling
         param_.pad,  // padding size
         param_.global_pool? TShape(param_.kernel.ndim()) : param_.stride, // reset stride size
         param_.pool_type,
         req[pool_enum::kOut],
         out_data[pool_enum::kOut].dptr<DType>());
```

To my understanding, global pooling should aways be no padding or with padding size 0 and just do computation on the whole image or feature map. If user inputs a padding size (2, 2) to a global average pooling, I doubt that the current implementation will give a wrong output. (Maybe the result is the average of (-2, -2) to (H-2, W-2) in input image or feature map).

If global pooling with padding is a supported feature in mxnet, I think I need to change the code of mkldnn pooling to align with that. Otherwise, maybe we need change code to reset padding size to zero if a non-zero padding size is given to global pooling.

A simple test case is attached for your information.
[test_pool.txt](https://github.com/apache/incubator-mxnet/files/1699227/test_pool.txt)

**Comment by piiswrong** [comment] 2018-02-06 19:04
Global pooling shouldn't support padding. If it's not checked we need to add checking

**Comment by TaoLv** [comment] 2018-02-07 01:18
@piiswrong OK. I can help to fix that.

**Comment by karan6181** [comment] 2018-02-27 20:24
@sandeep-krishnamurthy Can you please add this label
- C++
- Operator

Also, please close the issue since the issue is fixed I guess.
@TaoLv please feel free to re-open and comment if you can still reproduce the issue.
Thanks!

**Closed** 2018-03-19 07:28 UTC
Labels: C++, Operator
