### ISSUE TITLE
` list index out of range` and ` NativeOp doesn't support AddTo for output`

### ISSUE THREAD

**Issue by VikingMew** [apache/incubator-mxnet#7881] opened 2017-09-13 15:34 UTC
The code is for apply a masking to weights.

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Centos 7

Compiler: on pypi

Package used (Python/R/Scala/Julia): Py

MXNet version:0.11rc3

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: 2.7 anaconda

## Error Message:
`
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/u/anaconda2/lib/python2.7/site-packages/mxnet/operator.py", line 194, in backward_entry
    in_grad=tensors[2], out_grad=tensors[3])
  File "/home/u/PycharmProjects/rnn_word_lm_ptb/mx_rnn/rnn_cell.py", line 92, in backward
    dy = out_grad[0]
IndexError: list index out of range
[16:29:46] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [16:29:46] src/operator/custom/./native_op-inl.h:114: Check failed: req[i] != kAddTo (3 vs. 3) NativeOp doesn't support AddTo for output

Stack trace returned 10 entries:
[bt] (0) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xec23c) [0x7fd56bda323c]
[bt] (1) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x1e315b) [0x7fd56be9a15b]
[bt] (2) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xf98e64) [0x7fd56cc4fe64]
[bt] (3) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe356a3) [0x7fd56caec6a3]
[bt] (4) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe12a57) [0x7fd56cac9a57]
[bt] (5) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe12e8b) [0x7fd56cac9e8b]
[bt] (6) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe13f0d) [0x7fd56cacaf0d]
[bt] (7) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe38938) [0x7fd56caef938]
[bt] (8) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe390d2) [0x7fd56caf00d2]
[bt] (9) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(MXExecutorBackwardEx+0x1df) [0x7fd56ca841bf]

Traceback (most recent call last):
  File "cwrnn_ptb.py", line 153, in <module>
    monitor=Monitor(1, lambda x: x,"^((?!backward)(?!reshape)(?!grad).)*$")
  File "/home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/module/base_module.py", line 487, in fit
    self.forward_backward(data_batch)
  File "/home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/module/base_module.py", line 192, in forward_backward
    self.backward()
  File "/home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/module/bucketing_module.py", line 426, in backward
    self._curr_module.backward(out_grads=out_grads)
  File "/home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/module/module.py", line 613, in backward
    self._exec_group.backward(out_grads=out_grads)
  File "/home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 547, in backward
    exec_.backward(out_grads=out_grads_slice)
  File "/home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/executor.py", line 231, in backward
    ctypes.c_int(is_train)))
  File "/home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:29:46] src/operator/custom/./native_op-inl.h:114: Check failed: req[i] != kAddTo (3 vs. 3) NativeOp doesn't support AddTo for output

Stack trace returned 10 entries:
[bt] (0) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xec23c) [0x7fd56bda323c]
[bt] (1) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x1e315b) [0x7fd56be9a15b]
[bt] (2) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xf98e64) [0x7fd56cc4fe64]
[bt] (3) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe356a3) [0x7fd56caec6a3]
[bt] (4) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe12a57) [0x7fd56cac9a57]
[bt] (5) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe12e8b) [0x7fd56cac9e8b]
[bt] (6) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe13f0d) [0x7fd56cacaf0d]
[bt] (7) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe38938) [0x7fd56caef938]
[bt] (8) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe390d2) [0x7fd56caf00d2]
[bt] (9) /home/hchen/anaconda2/lib/python2.7/site-packages/mxnet/libmxnet.so(MXExecutorBackwardEx+0x1df) [0x7fd56ca841bf]
`

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

`class NumpyMask(mx.operator.NumpyOp):
    def __init__(self):
        super(NumpyMask, self).__init__(False)

    def list_arguments(self):
        return ['data','mask']

    def list_outputs(self):
        return ['output']

    def infer_shape(self, in_shape):
        data_shape = in_shape[1]
        output_shape = in_shape[1]
        return [data_shape, data_shape], [output_shape]

    def forward(self, in_data, out_data):
        x = in_data[0]
        mask = in_data[1]
        y = out_data[0]
        y[:] = x * mask

    def backward(self, out_grad, in_data, out_data, in_grad):
        dx = in_grad[0]
        dy = out_grad[0]
        mask = in_data[1]
        dx[:] = dy
        dx = dx * mask
`

**Comment by szha** [comment] 2017-12-22 22:45
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by jesterhazy** [comment] 2018-03-19 22:24
duplicate of #1983. Try using CustomOp instead.

**Closed** 2018-03-19 22:27 UTC
Labels: Need Triage
